### ISSUE TITLE
resource log diagnostic settings generation should allow being disabled intentionally

### ISSUE THREAD

**Issue by khaliddermoumi** [Azure/ResourceModules#1001]
## Description

Across the resource implementations, resource log diagnostic settings are included. While this is sometimes what the user actually wants, sometimes it is not. For example, often people will want to set the resource log diagnostic settings via policies, and not at resource deployment time. This is why it should be supported that the generation of the diagnostic settings can be disabled intentionally.
Currently, you can avoid that the diagnostic settings are being set by not setting any of a couple of values, f. e. (from keyvault):
```
resource keyVault_diagnosticSettings 'Microsoft.Insights/diagnosticsettings@2021-05-01-preview' = if ((!empty(diagnosticStorageAccountId)) || (!empty(workspaceId)) || (!empty(eventHubAuthorizationRuleId)) || (!empty(eventHubName))) {
// ...
}
```
I believe a better option for the API of the module is to set or "not set" the diagnostic settings explicitly, via an object parameter:
```
diagnosticSettings = {
  storageAccountId: '...'
  workspaceId: '...'
  ...
}
```
and pass this into the module as the "diagnosticSettings" object param.

**Comment by rahalan** [comment]
@khaliddermoumi not sure what difference in the outcome your proposed solution will change. Please elaborate. Thanks.

**Comment by khaliddermoumi** [comment]
Hi @rahalan, this issue isn't a feature request, nor a bug, it is about the API design (interface design).

Please note that I was using v 0.3 at the time of filing the issue. 
Back then, setting "diagnostic settings" was not obvious in the interface of a module. For example a key vault:
```bicep
module kv '....' = {
  name: '...'
  params: {
    name: '...'
    enablePurgeProtection: false
    enableSoftDelete: true
    enableVaultForDiskEncryption: true
    eventHubName: '...'
    keys: []
    workspaceId: '...'
    tags: {}
  }
}
```
In this interface, you need to remember, or be aware that "workspaceId" and "eventHubName" are part of the "diagnostic settings", and need to be set or removed, if you want diagnostic settings. In this case, devs frequently forget f. e. unsetting these values, if they do not want diagnostic settings, as it is not obvious, you don't "see" the intention of these parameters in the interface.
As an example on what one would expect, take f. e. the portal. If you want to set diagnostic settings, you click on "diagnostic settings", and then set log analytics workspace, event hub, etc. If you want to remove "diagnostic settings", you click on "diagnostic settings", and then remove the setting as a whole. I would say, in the portal, the intention of these settings is clear, as they are all organized under "diagnostic settings. In the 0.3.1 version of CARML, this wasn't obviuous.

Now, with v0.4, many parameters have been renamed, f. e. "workspaceId" is now "diagnosticWorkspaceId", so this isn't as much as a problem as it was back then.
I personally would still say that it would be even better if you aligned all these properties under a "diagnosticSettings" object, like I proposed in this issue:
```bicep
diagnosticSettings = {
  storageAccountId: '...'
  workspaceId: '...'
  ...
}
```
So you would immediately see all what is part of this setting.

I hope this is clearer now, please let me know if I need to be clearer.
Feel free to rename etc. this issue if you want.

**Comment by rahalan** [comment]
We try to avoid complex objects as parameters were possible, so we will stick with the solution as it is currently. Unfortunately we are not able to remove diagnostic settings, as ARM is not supporting that.
