### ISSUE TITLE
Add location to outputs on all modules which support it

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1010]
## Description

As more complex deployments would require certain resources to be deployed into the same region as some other components, it would be better to dynamically be able to reference the location of where a module has been deployed, rather than reusing the RG.location, deployment.location or even use a param directly. 

Suggestion:
- Add `location` as a parameter for all modules which support it
- Update module design guideline adding `location` as a new output for modules which support it.
- Add to the global.module.test.ps1 to check for location output where targetScope = 'blank' or 'resourceGroup' (not thought through how this would work for child resources).

**Comment by MrMCake** [comment]
Note that not all resources support a location. Just pointing it out as you mention 'Add `location` as a parameter for **all** modules'
