### ISSUE TITLE
Check optional vs required parameter description Feature Request

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1034]
## Description

Verify the description for Optional parameters is correct, i.e. parameter description should start with "Optional" if a default value is provided.

Verify the description for Required and Conditional parameters is correct, i.e. if the parameter description starts with "Required" or "Conditional" no default value should be provided.

For each of these scenarios a Pester test should be created.

**Comment by MariusStorhaug** [comment]
Is this not already done?
https://github.com/Azure/ResourceModules/blob/b1af5ff3629d3c243aeb04ce88e48f4effb80a1f/arm/.global/global.module.tests.ps1#L692
