### ISSUE TITLE
Azure Key Vault - Can't set enablePurgeProtection to false via ARM templates

### ISSUE THREAD

**Issue by cpear** [Azure/ResourceModules#1038]
## Description
The property "enablePurgeProtection" cannot be set to false when deploying an ARM template. This is similar to a bug fixed with the CLI tool. https://github.com/Azure/azure-cli/issues/13006

We are attempting to deploy a Key Vault instance to Azure via an ARM template. The deployment is part of an Azure DevOps release. 

### Steps to reproduce

1. Create an ARM template with a Key Vault instance.
2. Set the property enablePurgeProtection to false.
3. Create a CI/CD pipeline in AzDO.
4. Create a Release and add an ARM Template Deployment Task.
4. Attempt a release.

### Screenshots
![image](https://user-images.githubusercontent.com/4096556/155432701-47cde740-9b72-4383-a40e-7e2a78f76d29.png)

**Comment by MrMCake** [comment]
Hey @cpear, 

I'd like to understand the issue a bit better. Is there any chance the key vault instance was already deployed once with `enablePurgeProtection` enabled? Once it was set, the property cannot be changed again.

However, upon first deployment I can confirm that it is possible to set the value. For instance, each of our key vault deployments in CARML has the `enablePurgeProtection` value set to `false` by default and is deployed with set value.

Can you try to deploy the keyvault with a different name and see if it is still failing?

**Comment by mckenn55** [comment]
I work with @cpear.  Here is the the entire JSON ARM Template:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
      {
          "type": "Microsoft.KeyVault/vaults",
          "apiVersion": "2021-11-01-preview",
          "name": "myrandomname",
          "location": "[resourceGroup().location]",
          "properties": {
              "sku": {
                  "family": "A",
                  "name": "standard"
              },
              "tenantId": "[subscription().tenantId]",
              "accessPolicies": [
                  {
                      "tenantId": "[subscription().tenantId]",
                      "objectId": "12345678-abcd-1234-abcd-1234567890ab",
                      "permissions": {
                          "keys": [
                              "get",
                              "create",
                              "delete",
                              "list",
                              "update",
                              "import",
                              "backup",
                              "restore",
                              "recover"
                          ],
                          "secrets": [
                              "get",
                              "list",
                              "set",
                              "delete",
                              "backup",
                              "restore",
                              "recover"
                          ],
                          "certificates": [
                              "get",
                              "list",
                              "delete",
                              "create",
                              "import",
                              "update",
                              "managecontacts",
                              "getissuers",
                              "listissuers",
                              "setissuers",
                              "deleteissuers",
                              "manageissuers",
                              "recover"
                          ],
                          "storage": [
                              "get",
                              "list",
                              "delete",
                              "set",
                              "update",
                              "regeneratekey",
                              "setsas",
                              "listsas",
                              "getsas",
                              "deletesas"
                          ]
                      }
                  }
              ],
              "enableSoftDelete": false,
              "enablePurgeProtection": false,
              "enabledForDeployment": false
          }
      }
    ]
}
```

**Comment by mckenn55** [comment]
Good Morning,

You are correct, I do not work with this repository's code, I work with @cpear.  The ARM template code I posted was from our AzDO pipeline and was the cause of the error @cpear mentioned at the beginning of this thread.  Looking at the documentation [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2021-10-01/vaults?tabs=json), I believed that enablePurgeProtection was a boolean with valid values of true or false. Thank you for clarifying.

https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2021-10-01/vaults?tabs=json

**Comment by MrMCake** [comment]
I think the paint takeaway is this statement: `Enabling this functionality is irreversible - that is, the property does not accept false as its value.`

**Comment by cpear** [comment]
@MrMCake You are making a mistake. Look at the link I posted. This exact issue was corrected for the CLI. Why would you enable setting it to false via the CLI and not the ARM template?

Please review the thread:
https://github.com/Azure/azure-cli/issues/13006

**Comment by cpear** [comment]
@houk-ms Can you please look at this issue?

**Comment by jlichwa** [comment]
@majastrz is above makes sense. I assume it should be possible to set it to false.

**Comment by houk-ms** [comment]
@evelyn-ys, CLI Keyvault module owner to take a look at the behavior in CLI.

**Comment by MrMCake** [comment]
Hey @cpear, please note that this repository is about a template library and is in no way linked to the Azure Service (nor to the Product Group API) itself. In the library we're working with the same limitations as everybody else and I'd ask you to (for example) raise your issue in the [Azure KeyVault community](https://feedback.azure.com/d365community/forum/285c5ae0-f524-ec11-b6e6-000d3a4f0da0). I appreciate your input - it's just not the correct place. :)

**Comment by jlichwa** [comment]
@mckenn55 I'm from Key Vault and service supports false on management for all interfaces besides ARM templates, where is the right repository for ARM templates to correct issue

**Comment by mckenn55** [comment]
> @mckenn55 I'm from Key Vault and service supports false on management plane for all interfaces besides ARM templates, where is the right repository for ARM templates to raise issue

I'm an end user working with @cpear and I ran into the issue initially with him.  I think @MrMCake or @houk-ms would need to direct us as to where to raise this issue so that it may be addressed.

**Comment by jlichwa** [comment]
@mcken55 I will validate with engineering team what can be an issue here
