### ISSUE TITLE
ExpressRoute connection not working because of vpnSHaredKey

### ISSUE THREAD

**Issue by julioas09** [Azure/ResourceModules#1046]
## Description

When trying to deploy the Connection module configured for ExpressRoute it is failing becuae: ""Shared Key cannot be set for Connection of type expressRoute".

The problem is in this piece of code within the module:

```
resource connection 'Microsoft.Network/connections@2021-02-01' = {
  name: name
  location: location
  tags: tags
  properties: {
    virtualNetworkGateway1: {
      id: localVirtualNetworkGatewayId
    }
    virtualNetworkGateway2: virtualNetworkGatewayConnectionType == 'VNet2VNet' ? virtualNetworkGateway2Id : null
    localNetworkGateway2: virtualNetworkGatewayConnectionType == 'Ipsec' ? localNetworkGateway2Id : null
    peer: virtualNetworkGatewayConnectionType == 'ExpressRoute' ? peer : null
    enableBgp: enableBgp
    connectionType: virtualNetworkGatewayConnectionType
    routingWeight: routingWeight
    sharedKey: virtualNetworkGatewayConnectionType == 'ExpressRoute' ? vpnSharedKey : null <======================
    usePolicyBasedTrafficSelectors: usePolicyBasedTrafficSelectors
    ipsecPolicies: empty(customIPSecPolicy.ipsecEncryption) ? customIPSecPolicy.ipsecEncryption : customIPSecPolicy_var
  }
}
```

### Steps to reproduce

1. Just try to deploy an ER connection

### Screenshots

New-AzDeployment: /home/vsts/work/_temp/d4172424-035e-4333-9239-3897ff1a93b4.ps1:19
Line |
  19 |  $res = New-AzDeployment @DeploymentInputs
     |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 13:29:50 - The deployment
     | 'rsg-hubvnet-pre-weu1-01-eng-20220225T1302377326Z' failed with
     | error(s). Showing 1 out of 1 error(s). Status Message: At
     | least one resource deployment operation failed. Please list
     | deployment operations for details. Please see
     | https://aka.ms/DeployOperations for usage details. (Code:
     | DeploymentFailed)  - {   "error": {     "code":
     | "CannotSetSharedKeyForExpressRouteConnectionType",    
     | "message": "Shared Key cannot be set for Connection
     | /subscriptions/8e00e930-09da-4db2-8eef-f684269773f1/resourceGroups/rsg-hubvnet-pre-weu1-01-eng/providers/Microsoft.Network/connections/cnn-exprsroute-pre-weu1-01 of type ExpressRoute.",

**Comment by MrMCake** [comment]
This seems to be fixex in main. The currenlt implementation is `sharedKey: virtualNetworkGatewayConnectionType == 'ExpressRoute' ? null : vpnSharedKey`
