### ISSUE TITLE
Ensure minimum validation parameter file set for all modules

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1063]
## Description

The first planned step is to provide for each module a 'minimum-set' parameter file, limited to the top-level resource required parameters, vs. a 'maximum-set' parameter file, including all possible properties, child resources and extension resources. 

1. List modules that are still tested through one parameter file only. Then for each module:
2. Add a `min.parameters.json` parameter file in the .parameters folder to test only the required parameters.
3. Verify the `parameters.json` parameter file includes all possible properties, child resources and extension resources.

**Comment by rahalan** [comment]
Duplicate #401
