### ISSUE TITLE
Virtual Machine should allow configuring boot diagnostics with "managed" storage account

### ISSUE THREAD

**Issue by khaliddermoumi** [Azure/ResourceModules#1107]
## Description

A VM can be created with boot diagnostics enabled. Diagnostics data is written to a storage account.
There is a feature to not specify a custom storage account, and instead use a storage account managed by Azure. This is probably the better option than using your own storage accounts because of the limitations (your storage account needs an open firewall, and many options for it are not supported). 
The current module does not allow this configuration, instead you must always specify a custom storage account.
It would make much sense to add this feature, as it is probably the best way to activate boot diagnostics.
Inside an ARM template, you would specify the feature like this:
```json
"diagnosticsProfile": {
   "bootDiagnostics": {
      "enabled": true
   }
}
```
So you actually just need to enable the feature, and not specify an existing storage account.

**Comment by MrMCake** [comment]
@khaliddermoumi good idea & good catch. We'll move it into today. If you happen to have implemented that yourself and would like to share, Pull Requests are always welcome :)

**Comment by khaliddermoumi** [comment]
Thanks for asking! I haven't implemented this yet, as I am currently extremely busy with work etc. But I may be able to manage to do this in 1-2 weeks. 
So if you need this fix right now, I can't help, but maybe later?
