### ISSUE TITLE
Wiki restructuring - Solution creation

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1120]
## Description

- [ ] #1519
- [ ] #1518
- [x] #1514 
- [x] Add links to solutions using CARML:
  - AKS Accelerator
  - AVS Accelerator
  - https://github.com/Azure/DevOps-Self-Hosted
- [ ] #1520

**Comment by MrMCake** [comment]
Regarding the ADO universal packages I guess it will be a pipeline orchestration example. We actually have a PR open for the general multi-repo approach (pipeline orchestration) and can then I guess add to it :)

**Comment by MariusStorhaug** [comment]
Would it also make sense to add a chapter on "layering" with the diagrams showing the different layers and how that fits together?

Similar to this:
![image](https://user-images.githubusercontent.com/17722253/163125523-e9453825-9b3c-4caa-a261-0b792a714437.png)

![image](https://user-images.githubusercontent.com/17722253/163125573-daadcb7a-cf06-4501-9f21-fbf386646a03.png)

**Comment by rahalan** [comment]
@eriqua , can you and @MariusStorhaug please elaborate more on the description

**Comment by eriqua** [comment]
This comes out of the workshop feedback. The solution creation wiki page currently includes samples of how to leverage published modules (from template specs or the private bicep registry) and combine them to create a simple solution.

The risk is for the code provided in that page to get stale. For this reason, the page should instead be linked to the samples folder containing code which should be continuously tested and thus known working (ref #1184).

In addition, the solution creation page should contain:
- guidance on how to create a solution (e.g. identify required modules, identify deployment order, choose between pipeline vs template orchestration, go to module readme and check required param, etc)
- be linked to external repos using CARML (e.g. AKS)

@MariusStorhaug I agree with the layering page. Probably something for the context section. I'd suggest a different issue for that though.

cc @MrMCake @rahalan @MariusStorhaug please advise if still unclear

**Comment by MrMCake** [comment]
Linked to #1375 . Added a first couple tips + references to other workloads

**Comment by rahalan** [comment]
@rahalan split into more issues (one per task)

**Comment by MariusStorhaug** [comment]
@rahalan Remember to split this up. We will need to triage these on Tuesday.
- Add example for ADO universal packages - Assign to Sebastian Gräf

**Comment by MariusStorhaug** [comment]
Closed as this will be covered by other issues.
