### ISSUE TITLE
Container Registry: Parameter file with private endpoint cannot be removed

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1126]
The pipeline for the private registry deployment using the `parameters.json` cannot remove registry since introduction of private endpiont test: [reference](https://github.com/Azure/ResourceModules/actions/runs/1973810095). 

> Note: It's not the pipeline, but the resource is stuck in state 'deleting'
> Note: The deployment works perfectly.

**Comment by eriqua** [comment]
This fails since private endpoint has been added to the parameter set. It should have been proven to work before being merged. 
I'd suggest to remove the functionality again and work on the issue in a dev branch meanwhile. We shouldn't have failing modules merged to main.

**Comment by eriqua** [comment]
The order of removal should consider removing private endpoints before the actual target resource. This should be the case for all modules. 
In this case the removal of the PE resource `Microsoft.Network/privateEndpoints/carmlazacrx001-registry` should happen before the removal of the ACR resource `Microsoft.ContainerRegistry/registries/carmlazacrx001`. Addressing this as part of issue #1315
