### ISSUE TITLE
Upcoming BREAKING Change: Renaming folder `arm` to `modules`

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1127]
## Description

Folder /arm/ needs to be changed to /modules/

**Attention**: there are many references to this folder (documentation, logic, pipelines, ...)

**Comment by akata72** [comment]
I really think modules is a more descriptive name for the folder containing modules than "arm".

**Comment by MrMCake** [comment]
+1 for modules/library

**Comment by rahalan** [comment]
Team decides for 'modules'

**Comment by MariusStorhaug** [comment]
WIP

**Comment by MariusStorhaug** [comment]
@SeSeicht, seems I cannot assign you to the issue.
