### ISSUE TITLE
Availabilityset pipeline test fails (missing ppg in platform dependencies?)

### ISSUE THREAD

**Issue by akata72** [Azure/ResourceModules#1134]
The pipeline for testing the availabilityset fails as it is expecting a proximityplacementgroup that is not deployed during the platform dependencies deployment. (it works fine if I create the ppg manually first). Suspect that this might be missing in the pipeline for deploying platform dependencies.

**Comment by ahmadabdalla** [comment]
@akata72 thanks for raising the issue. Just to provide a bit of context. Yes I just looked at the [ado dependency pipeline](https://github.com/Azure/ResourceModules/blob/main/.azuredevops/platformPipelines/platform.dependencies.yml) config for ADO and it is missing ppg compared to the [gha dependency pipeline](https://github.com/Azure/ResourceModules/blob/main/.github/workflows/platform.dependencies.yml). Will have that fixed.
