### ISSUE TITLE
Microsoft.Web/sites App configurations only valid for Function App

### ISSUE THREAD

**Issue by mvbugge** [Azure/ResourceModules#1146]
## Description

Deployment of web app cannot run with given config. 

### Steps to reproduce

1. Deploy Microsoft.Web/sites
2. Deploy with `kind='app'`
3. Publish web app and run web app
4. The config properties 'FUNCTIONS_WORKER_RUNTIME' and 'FUNCTIONS_EXTENSION_VERSION' these properties makes the app service think it is an Azure Function and fails to run.

### Screenshots

![image](https://user-images.githubusercontent.com/32770168/158622077-4d076f50-61af-43ad-9c04-7a178dcdaea5.png)

**Comment by mvbugge** [comment]
The solution should ideally allow setting other configurations. See [https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-web?tabs=bicep](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-web?tabs=bicep)

**Comment by MrMCake** [comment]
Related to #1132 #1117

**Comment by MrMCake** [comment]
Will be covered by #1258
