### ISSUE TITLE
Microsoft.ManagedIdentity should output ObjectId

### ISSUE THREAD

**Issue by rkuehfus** [Azure/ResourceModules#1148]
Managed Identity outputs principle ID and should be objectID

![image](https://user-images.githubusercontent.com/17836524/158641864-c31e60f6-ff07-4e7c-88a4-1a160ab7fb59.png)

https://github.com/Azure/ResourceModules/tree/main/arm/Microsoft.ManagedIdentity/userAssignedIdentities#outputs

**Comment by MrMCake** [comment]
Hey @rkuehfus , to be fair, the name of the Azure Resource is `principalId` ;) 

![image](https://user-images.githubusercontent.com/5365358/158900180-68b4650b-6067-499d-bf0b-1740f95f4727.png)

Let's have a discussion about that some time - that is, how general rule we want to apply to output names. For example, should it be the name of the Azure Resource (API) as it is now, or should it be something that is closer to the consuming resource (in the above example `objectId`)

**Comment by rahalan** [comment]
Not a bug. It is the name of the property of the Azure resource reference.
