### ISSUE TITLE
Vnet peering parameter 'enableRemotePeering' is only described in the parent readme, not in the child

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#1150]
## Description

Vnet peering parameter 'enableRemotePeering' is only described in the parent readme, not in the child

### Steps to reproduce

1.
2.

**Comment by MrMCake** [comment]
Should it? I'm just wondering as the child is effectively only 'a' perring. If it doesn't really care if it goes into one, or the other direction, right?

**Comment by MrMCake** [comment]
Further @rahalan, I assume you refer to the paramete `remotePeeringEnabled`. That only exists in the parent template as it just deploys the child twice (& reversed). If you agree, feel free to close the issue

**Comment by rahalan** [comment]
You are correct.
