### ISSUE TITLE
Add PIP to Load Balancer

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#1154]
## Description

Load Balancer is not creating a PIP on their own (if not provided), as other modules do.

**Comment by jontreynes** [comment]
The FW expects a already deployed Public IP for the IpConfiguration. Other modules, like the VM, are able to create their own, if none is provided. The FW should create one, if none is provided

**Comment by jontreynes** [comment]
it looks like this is the logic that is being used in other modules
https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.Network/natGateways/deploy.bicep#L136

**Comment by jontreynes** [comment]
Trying to see if this another place where we default creating the PIP

The logic here translates to
https://github.com/Azure/ResourceModules/blob/80087b330c2eae20e720a2d53cf24af2c90478a8/arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep#L41

if (pipconfiguration has publicIPPrefixId){
	if (!publicIPPrefixId)
		publicIPPrefixId = ''
	else
		publicIPPrefixId = ipConfiguration.pipconfiguration.publicIPPrefixId
}
else
	publicIPPrefixId = ''

**Comment by jontreynes** [comment]
should reference pip module

**Comment by jontreynes** [comment]
bastionhost has this logic

module publicIPAddress '.bicep/nested_publicIPAddress.bicep' = if (empty(publicIPAddressId)) {

**Comment by jontreynes** [comment]
[![Network: AzureFirewalls](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml)

**Comment by jontreynes** [comment]
So adding an existing public ip address already exists under the ipconfigurations parameter where you can provide a list of value objects like

```
            "value": [
                {
                    "name": "ipConfig01",
                    "publicIPAddressResourceId": "/subscriptions/<<subscriptionId>>/resourceGroups/validation-rg/providers/Microsoft.Network/publicIPAddresses/adp-<<namePrefix>>-az-pip-x-fw",
                    "subnetResourceId": "/subscriptions/<<subscriptionId>>/resourceGroups/validation-rg/providers/Microsoft.Network/virtualNetworks/adp-<<namePrefix>>-az-vnet-x-azfw/subnets/AzureFirewallSubnet"
                }
```

so we shouldn't introduce a new parameter, publicipaddressid. We need to check if ipconfigurations object contains a nonempty value for ipconfigurations.value.publicIPAddressResourceId.

If it does, then do not create a public ip
If not, then create a public ipaddress and associate it with the properties.ipconfigurations of azurefirewall

**Comment by jontreynes** [comment]
Shouldn't there be an option to for having a private ip for load balancer?

**Comment by jontreynes** [comment]
Notes from backlog:

I'll look into boolean for not defaulting public ip

By default, autogenerate public with possibility to override.

Table topic: public ip name - should it be assumed by the module - or should a user be able to input that.

**Comment by jontreynes** [comment]
Boolean included and ability to override public ip name #1392

**Comment by jontreynes** [comment]
The last merge #1392 only covered Azure Firewall.

TODO:
1. Provide List of modules that can use a Public IP
2. Update module with similar logic to the one provided in #1392 with additional use case parameter files

**Comment by jontreynes** [comment]
Current List

1) BastionHost
2) Load Balancer

**Comment by AlexanderSehr** [comment]
@jontreynes is still still active?

**Comment by AlexanderSehr** [comment]
Closing in favor of: https://github.com/Azure/bicep-registry-modules/issues/2452
