### ISSUE TITLE
Verify `@batch(1)` - Virtual Network Gateway

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#1155]
## Description

Test if `@batch(1)` is required for the PIP deployment. 
If not - remove it
If it is required - keep it and add an inline documentation why it is needed

Applicable resource type:
- Microsoft.Network/virtualNetworkGateways

**Comment by rahalan** [comment]
1.) duplicate task for all modules that are affected
2.) if @batch(1) is needed, add a inline comment why that is the case

**Comment by MrMCake** [comment]
This is already done
