### ISSUE TITLE
authorized keys in VMSS params files

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/ResourceModules#1157]
## Description

https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.Compute/virtualMachineScaleSets/.parameters/linux.parameters.json

and

https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.Compute/virtualMachineScaleSets/.parameters/linux.min.parameters.json

```
            "value": [
                {
                    "path": "/home/scaleSetAdmin/.ssh/authorized_keys",
                    "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdOir5eO28EBwxU0Dyra7g9h0HUXDyMNFp2z8PhaTUQgHjrimkMxjYRwEOG/lxnYL7+TqZk+HcPTfbZOunHBw0Wx2CITzILt6531vmIYZGfq5YyYXbxZa5MON7L/PVivoRlPj5Z/t4RhqMhyfR7EPcZ516LJ8lXPTo8dE/bkOCS+kFBEYHvPEEKAyLs19sRcK37SeHjpX04zdg62nqtuRr00Tp7oeiTXA1xn5K5mxeAswotmd8CU0lWUcJuPBWQedo649b+L2cm52kTncOBI6YChAeyEc1PDF0Tn9FmpdOWKtI9efh+S3f8qkcVEtSTXoTeroBd31nzjAunMrZeM8Ut6dre+XeQQIjT7I8oEm+ZkIuIyq0x2fls8JXP2YJDWDqu8v1+yLGTQ3Z9XVt2lMti/7bIgYxS0JvwOr5n5L4IzKvhb4fm13LLDGFa3o7Nsfe3fPb882APE0bLFCmfyIeiPh7go70WqZHakpgIr6LCWTyePez9CsI/rfWDb6eAM8= generated-by-azure"
                }
            ]
        },
```

### Steps to reproduce

n/a

**Comment by rahalan** [comment]
Is only the public part of the key. No security issue

**Comment by christiankuhtz** [comment]
I think you fundamentally understand my point. creds of any kind don't belong into this code, public key or not. And this cannot succeed as an example anyway and create a working code precisely because it is public key only.  This is an indication credscan isn't running on this repo and should be fixed.  Please address.  Thanks

**Comment by rahalan** [comment]
We will look further into this

**Comment by MrMCake** [comment]
Hey @christiankuhtz, I'm in no way a GitHub expert, but shouldn't this setting should but just that? 

![image](https://user-images.githubusercontent.com/5365358/163039285-7f005309-de01-4353-b978-8ce11ef94831.png)

If so, it is enabled since the repository's creation. However, I'll try and test if it actually works.

**Comment by rahalan** [comment]
Hi @christiankuhtz , as it is a public key CredScan has no problem with it. So it is fine by us. If you feel this should be addressed, please open an issue for CredScan.
Cheers, Rainer

**Comment by aavdberg** [comment]
@rahalan and @MrMCake I agree with @christiankuhtz this repository is a example for others to use and putting secret in code is a no no private and also in public repositories.

The same as exporting secrets in a module.
