### ISSUE TITLE
Feedback: Consider removing the ability to create "parent" resources from within "child" resource modules

### ISSUE THREAD

**Issue by krowlandson** [Azure/ResourceModules#1158]
## Description

The ability to create `child` and `extension` resources relating to the primary resource created by a module is a great value-add, however the ability to create `parent` resources can lead to confusion due to the following reasons:

- Providing two approaches will lead to inconsistency between implementations trying to achieve the same outcome, negating one of the desired outcomes of CARML regarding consistent code.
- The requirements to input complex objects to create parent resources is problematic due to the absence of schema support for objects in ARM JSON / Bicep which prevents IntelliSense from helping. This is made worse due to the way documentation is auto-generated using decorators, as these are unable to contain enough information needed for the documentation to fully explain what is required. Subsequently, you become reliant on looking up the original resource documentation and hoping that it directly translates to the module implementation.
- In situations where multiple `children` may rely on the same `parent` in the future, you need to either create a dependency where the new `children` are dependent on a `parent` created by another `child`, or refactor the code to explicitly declare the `parent`. We have also noticed that copying the same `complex object` input into each `child` resource can result in multiple instances of the `parent` being created, rather than the same `parent` being shared by those `children`.
- This also appears to further compound the problem of knowing which inputs are only conditionally `required`.

On this basis, our feedback is to consider updating the modules to only support a "top down" approach to creating resource within a module.

**Comment by MrMCake** [comment]
One example is the `Microsoft.Web/sites` resource type that is enable to create App Service Plans (=> Parent). There may be more. There may be more examples.
> Note: This does not include extension resources like NICs for VMs
