### ISSUE TITLE
Vulnerability Assessment  using a private endpoint storage account hangs  deployment 

### ISSUE THREAD

**Issue by kprotsko** [Azure/ResourceModules#1177]
https://github.com/Azure/ResourceModules/blob/2bba6013e392cf7ebb1b52f4b8b1cea6002df0aa/arm/Microsoft.Sql/managedInstances/vulnerabilityAssessments/deploy.bicep#L43

Configuring Vulnerability Assessment on  SQL Managed instance.    When storage account keys are not used and deploying to Storage account connected with a private endpoint this line causes the deploy to hang.   Commenting it out  allows the deploy to succeed.

**Comment by MrMCake** [comment]
Hey @kprotsko, thanks for the issue. We'll make sure to check it out. Will flag the issue as a bug.

**Comment by MrMCake** [comment]
Closing if favor of #1210
