### ISSUE TITLE
Adding PrincipalType property to RoleAssignments

### ISSUE THREAD

**Issue by Msanzdelrio** [Azure/ResourceModules#1178]
## Description

Include PrincipalType as part of the Role Assignment as per the documentation, if not set properly `you might get intermittent deployment errors, especially when you work with service principals and managed identities`. Link to documentation [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/scenarios-rbac#principal).

(Shared by an external contributor: mj.richardson@microsoft.com)

**Comment by MrMCake** [comment]
Agreed. We should do that asap. I just faced the same issue preparing a module for the public bicep registry.
