### ISSUE TITLE
Create a samples folder with solution examples/samples on root

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1184]
Create a samples folder with solution examples/samples on root

Replace `constructs` folder with `samples` folder:
- Create examples (solutions/constructs/architectural patterns) to show how to use CARML
- Create more solutions/constructs to consume to accelerate initiatives like construction sets (e.g. mini constructs that deploy small sets of modules)
- Provide deployable samples for common architectures. Keep these up to date. These are designed to be copied & modified, not referenced.

Reqs:
- Deployable solutions that have pipelines that trigger on changes in the repo. (Validate that the samples work after changes in the repo)
- Update wiki with new page under `Getting started` with links to the samples we have covered in the samples folder.

**Comment by MrMCake** [comment]
How is this different from the constructs folder? We should probably merge the two under a common name (alongside a readme to position its content)

**Comment by MariusStorhaug** [comment]
I.e. https://github.com/MariusStorhaug/IaCSolutions

**Comment by eriqua** [comment]
This would be covered by #2024. Moving back to needs triage to propose its closure as duplicated.
