### ISSUE TITLE
Microsoft.KeyVault/vaults module - networkAcls ipRules property mandatory

### ISSUE THREAD

**Issue by swilkodev** [Azure/ResourceModules#1196]
## Description

When using the Microsoft.KeyVault/vaults module, the networkAcls ipRules property is mandatory. If it is omitted an InvalidTemplate error occurs when running a what-if. 

*InvalidTemplate - Deployment template validation failed: 'The template variable 'networkAcls_var' is not valid: The language expression property 'ipRules' doesn't exist, available properties are 'bypass, defaultAction'.. Please see https://aka.ms/arm-template-expressions for usage details.'.*

The error was also confusing and took me a while to figure out the issue. It is also not consistent with other properties such as virtualNetworkRules.

### Steps to reproduce

1. Define a bicep file which uses the Microsoft.KeyVault/vaults module. Sample below uses the module from a private registry. 

```
module keyVaultModule 'br/ResourceModules:microsoft.keyvault.vaults:0.4.882' = {
  name: 'keyVaultDeploy'
  scope: rg
  params:{
    name: keyVaultName
    tags: tags
    vaultSku: 'standard'
    enablePurgeProtection: true
    enableRbacAuthorization: true
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      //ipRules: [] // Required else error occurs
    }
  }
}
```

2. Run the deployment with what-if, either using the CLI or Powershell. The error should occur.
3. Uncomment the ipRules property with an empty array as the value and run the deployment, the error will not occur.

The issue seems to be on https://github.com/Azure/ResourceModules/blob/05c38b0921f6d734a299f4911c73dbd804255f2a/arm/Microsoft.KeyVault/vaults/deploy.bicep#L156

The line should be 
```
ipRules: (!empty(networkAcls) && contains(networkAcls, 'ipRules')) ? networkAcls.ipRules : []
```

I've tested this locally and it worked. Happy to submit a PR, if your accepting them.

**Comment by swilkodev** [comment]
@rahalan submitted PR.

**Comment by eriqua** [comment]
@rahalan I assume this can be closed? 
We probably need an automation for closing issues when they are moved to the closed/done states in the respective boards.

**Comment by rahalan** [comment]
@eriqua yes, it can be closed. And the logic is already there, but someone need to move it into closed :-D
