### ISSUE TITLE
Microsoft.Web/sites add virtualNetworkSubnetId

### ISSUE THREAD

**Issue by cliverallen** [Azure/ResourceModules#1206]
Add virtualNetworkSubnetId to the module so that a subnet id can be specified.

Assign this to me and I can update it.

**Comment by MrMCake** [comment]
Hey @cliverallen, highly appreciate it, thanks. Just assigned the issue to you and added the corresponding lables.

**Comment by MrMCake** [comment]
Already resolved by #1258
