### ISSUE TITLE
SQL Managed Instances - Vulnerability Assessment with Storage Accounts using Private Endpoints

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/ResourceModules#1210]
## Description

When using Storage Accounts with Private Endpoints, we have to use Managed Identity of SQL MI to turn on Vulnerability Assessment.  With MSI, the need for you no longer need to set `storageAccountAccessKey` value.  When this value is set, the deployment never completes.

### Steps to reproduce

1.  Create a storage account with private endpoints
2.  Create SQLMI with MSI
3.  RBAC SQLMI MSI -> Storage Account as Blob Contributor
4.  Enable Vulnerability Assessment

The deployment hangs.

Resolution:

1. Remove `storageAccountAccessKey` setting:  https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.Sql/managedInstances/vulnerabilityAssessments/deploy.bicep#L43

Ask:  Can this be configurable based on a parameter so access key is optionally used if PE is not enabled?

**Comment by MrMCake** [comment]
Related of #1177

**Comment by fblix** [comment]
waiting for #1964 to be completed.
