### ISSUE TITLE
Microsoft.Sql/servers - Support for Vulnerability Assessments

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/ResourceModules#1211]
## Description

[Microsoft.Sql](https://github.com/Azure/ResourceModules/tree/main/arm/Microsoft.Sql)/servers deployment doesn't support vulnerability assessments.  Can this feature be added?  It would be similar to SQLMI.

**Comment by MrMCake** [comment]
@SenthuranSivananthan, definitely. It will be implemented as soon as any contributor has the capacity to implement it
