### ISSUE TITLE
Improve documentation to discuss different use cases for consuming CARML

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1226]
## Description

Add documentation for different ways of consuming CARML modules:
- elaborate on various scenarios
- pros and cons
- Recommendation on when to use different approaches
- Consider Persona in different approaches
- Consider adding a decision tree
- Cover ADO use-case as well

**Comment by eriqua** [comment]
Is this a duplicate of #1518 + #1514 ?

**Comment by AlexanderSehr** [comment]
This has been implemented in the [Solution Creation](https://github.com/Azure/ResourceModules/wiki/Solution%20creation) wiki page.
