### ISSUE TITLE
Pester test fails on markdown-style description decorators

### ISSUE THREAD

**Issue by akata72** [Azure/ResourceModules#1232]
## Description

If you use a markdown-style description decorator i.e like this;

```
@description('''Required. The name of the subnet where the userpools (workloads) are provisioned. The user node pool runs the application workload and the ingress controller to facilitate inbound communication to the workload
- This parameter is only used when the \'agentPools\' parameter is not provided. 
- The subnet used by each nodepool (if multiple defined) is normally defined in the \'agentPools\' parameter.
''')
param userPoolsSubnetName string
```

It seems that when running the Pester tests some logic will fail and the NEXT parameter will not be recognized and the "parameters section should contain all parameters from the template file" Pester test will fail like this; 

### Screenshot 

![image](https://user-images.githubusercontent.com/16230163/162250153-f9024cb6-39a8-4c0e-b020-9202c64d6b3c.png)

When I change the markdown-style description the problem goes away. :-)

**Comment by MrMCake** [comment]
Hey @akata72, thank you for raising the issue. We'll triage this and investigate this asap.

**Comment by MrMCake** [comment]
Hey @akata72, 

I just created a Pull Request with an update to the `Set-ModuleReadMe` script. Essentially it makes sure that `\n` is properly translated into an HTML `<p>` as this is the only format Markdown would accept inside tables.

I'd appreciate if you could give the changed function a spin and re-run the tests. Without the update, the markdown table would be ill-formatted what explains why the test would fail.
