### ISSUE TITLE
Use defaultResourceGroupName from global.variables in parameter JSON-Files

### ISSUE THREAD

**Issue by SeSeicht** [Azure/ResourceModules#1234]
## Description

There is a variable called `defaultResourceGroupName` in the `global.variables.yml` which is used from the deployment pipeline for example. 
But in the `parameters.json` the `validation-rg` is hardcoded. So, if you change the default value in the `global.variables` you would also need to change every parameters.json. 

So the variable should used everywhere or nowhere.

**Comment by ahmadabdalla** [comment]
Just some updates @SeSeicht the 'global.variables.yml' has now been updated and is at the root and can be used for both ADO and GHA pipelines. This doesn't solve the issue you mentioned above, and we do have a potential solution, we just need to see if we'll use that or another one.

In your fork for example, you can replace `validation-rg` with the token `<<resourceGroupName>>` and that will leverage the value used in the `global.variables.yml`

**Comment by MrMCake** [comment]
Linked to #1363 

Closing this one in favor - as it will likely resolve it too
