### ISSUE TITLE
Get ObjectID from tenant for Backup Management Service

### ISSUE THREAD

**Issue by SeSeicht** [Azure/ResourceModules#1240]
In the [dependency parameter-File]( https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json#L12) of the KeyVault is a hardcoded objectID. This objectID is **tenant-specific**. 

There should be a hint in the [wiki ](https://github.com/Azure/ResourceModules/wiki/Getting%20started%20-%20Setup%20environment#4-deploy-dependencies)that this objectID has to be changed before running the pipeline. 
Or the ID should be dynamic.

**Comment by MrMCake** [comment]
For the time being I added an entry to the 'elements to update' table in the [wiki](https://github.com/Azure/ResourceModules/wiki/Getting%20started%20-%20Setup%20environment#5-update-module-parameter-files).

**Comment by ahmadabdalla** [comment]
Similar issue https://github.com/Azure/ResourceModules/issues/937

**Comment by SeSeicht** [comment]
> Similar issue #937

you are right. Will close this issue!
