### ISSUE TITLE
Module readmes - Add different combinations/configuration examples in module readme

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1248]
## Description

To provide a better dev experience for solution devs when consuming modules, there should be multiple common examples of how a module is configured in the example section i.e. AppGateway which have at least 3 different combinations for separate use cases of the app gateway.

**Comment by rahalan** [comment]
closed with issue [ResourceModules/arm/Microsoft.Storage/storageAccounts at main · Azure/ResourceModules (github.com)](https://github.com/Azure/ResourceModules/tree/main/arm/Microsoft.Storage/storageAccounts#deployment-examples)
