### ISSUE TITLE
Verify `@batch(1)` - NetApp Accounts

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1250]
## Description

Test if `@batch(1)` is required for the PIP deployment. 
If not - remove it
If it is required - keep it and add an inline documentation why it is needed

Applicable resource type:
- Microsoft.NetApp/accounts
- Microsoft.NetApp/accounts/capacityPools

**Comment by MrMCake** [comment]
https://github.com/Azure/ResourceModules/actions/runs/2157206249
