### ISSUE TITLE
Private Endpoints - Should be consistent to always deploy private DNS

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1254]
## Description

The general rule should be that when a Private Endpoint is deployed it should also configure private DNS. This issue is to investigate all the resources that can deploy a Private Endpoint and see if they are missing the DNS configuration in the module. If found, create an issue per module to fix it.

Example what should be there for all modules:

https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.KeyVault/vaults/.bicep/nested_privateEndpoint.bicep#L39

---
Update 14/7/2022

The current implementation requires the following:

- [x] #1666

Setup `privateDnsZoneGroups` on all modules testing pe implementation, which are:
- [x] #1688
- [x] #1692
- [x] #1975
- [x] #1901
- [x] #1982
- [x] #1991
- [x] #2008
- [x] #2000
- [x] #1701
- [x] #1691
- [x] #1969
- [x] #1966
- [x] #1893
- [x] #1698
- [x] #1671
- [x] #1695
- [x] #1971
- [x] #1895
- [x] #2004
- [x] #2006

Ref: https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns

**Comment by MrMCake** [comment]
We should probably also re-evalute the implementation to make sure everything is there (before we roll changes out on-scale)

**Comment by eriqua** [comment]
All modules supporting Private Endpoint deployment have been aligned to also integrate with existing private DNS zones. Closing.
