### ISSUE TITLE
Wiki - Add info on target audience for CARML

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1256]
## Description

Add to the first paragraph of the intro page who the target audience is for CARML. Set expectations early that this is not intended to be a learning tool for Bicep. It is meant as a tool for experienced Solution Architects and DevOps engineers to build solution with. Any new tool, toolkit, framework will have an introductory or learning period. CARML is no different.

Taken from a colliding task and should be brought in:
Rephrasing the first paragraph in the wiki. Provide pointers to existing resources. Outline purpose and audience in clear language. Later in the article -> Link to Microsoft Learn Bicep courses.

**Comment by eriqua** [comment]
Did the recently added Wiki page [Logical layers and personas](https://github.com/Azure/ResourceModules/wiki/The%20context%20-%20Logical%20layers%20and%20personas) address this feature request?

**Comment by eriqua** [comment]
Moving back to needs triage to have visibility on the above question :D
