### ISSUE TITLE
Private Endpoint - Consistent parameter implementation

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1271]
## Description

Parameters for Private Endpoints are inconsistent when you configure private endpoint as a module parameter vs the parameters in Private Endpoints module. E.g.

[Private Endpoint params in Container Registry module](https://github.com/Azure/ResourceModules/tree/main/arm/Microsoft.ContainerRegistry/registries#parameter-usage-privateendpoints):
- `name`
- `subnetResourceId`
- `service`
- `privateDnsZoneResourceIds`
- `customDnsConfigs`

[Private Endpoint params in the Private Endpoint module](https://github.com/Azure/ResourceModules/tree/main/arm/Microsoft.Network/privateEndpoints#parameters):
- `enableDefaultTelemetry`
- `groupId`
- `location`
- `lock`
- `name`
- `privateDnsZoneGroups`
- `roleAssignments`
- `serviceResourceId`
- `tags`
- `targetSubnetResourceId`

**Comment by eriqua** [comment]
As part of this issue: discuss if specifying the servicename through the parameter file or if hardcording that to the specific module. See discussion in PR #1367
