### ISSUE TITLE
Microsoft.Network - Subnetting is complex. Provide clarity

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1276]
## Description

Azure Resource Reference matching to readme.md properties object for Azure Virtual network. Add an example of how to build subnet. The `properties` in the subnet isn't in line with Azure Resource Reference (ARR). No clear reason to break with the guidelines of staying close to the ARR.

Suggestion:
- Add an example into the readme for the subnet object/array

**Comment by rahalan** [comment]
Issue is based on resource provider level implementation. Update Documentation to highlight not to use the subnet module separately, because that will delete and redeploy all subnets
