### ISSUE TITLE
Microsoft.Web/sites - `AppInsightID` and `AppInsightObject` both marked as optional

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1279]
## Description

`AppInsightID` and `AppInsightObject` both marked as optional; however, this is conditionally true depending on if one of these parameters is used and is not intuitive. This is true amongst dependent parameters.

We should plan to verify conditional parameter categories and label them as Conditional (currently Optional). This is true for all modules.

**Comment by rahalan** [comment]
There are more examples of this type of issue. Maybe just to highlight in the documentation, hard to achieve this kind of logic in Bicep

**Comment by rahalan** [comment]
Should we 1.) introduce conditional parameters and 2.) how should we handle that? - @MrMCake can you please elaborate

**Comment by eriqua** [comment]
@MariusStorhaug, @MrMCake, @rahalan I cannot find any occurrence of `AppInsightObject` in the repo. Probably due to a recent restructure of the module. 

Concerning the high level feature request about Conditional parameters, they are now widely used in modules.

Should this issue be closed?
