### ISSUE TITLE
[Feature Request]: Network ACLs to allow multiple different VNets

### ISSUE THREAD

**Issue by fblix** [Azure/ResourceModules#1287]
### Description

Currently (at least for the StorageAccounts Module) it is afaik not possible to add subnets of two different VNets to the NetworkACLs section.

Currently it looks like this (line 157 in Microsoft.Storage/storageAccounts/deploy.bicep):

```bicep
var virtualNetworkRules = [for index in range(0, (empty(networkAcls) ? 0 : length(networkAcls.virtualNetworkRules))): {
  id: '${vNetId}/subnets/${networkAcls.virtualNetworkRules[index].subnet}'
}]
```

idea would be to change it to this:

```bicep
var virtualNetworkRules = [for index in range(0, (empty(networkAcls) ? 0 : length(networkAcls.virtualNetworkRules))): {
  id: networkAcls.virtualNetworkRules[index].subnetId
}]
```

This would enable the user to add subnets not based on a name (that is additionally limited to the current vnet used by the variable `vNetId` ) but based on the full resourceId.

Your thoughts? - Happy to discuss this :)

**Comment by MrMCake** [comment]
Great suggestion @fblix . A foreach should do the trick too as Bicep doesn't fail on empty arrays (anymore):

```bicep
var virtualNetworkRules = [for virtualNetworkRule in networkAcls.virtualNetworkRules: {
  id: virtualNetworkRule.subnetId
}]
```

**Comment by fblix** [comment]
@MrMCake just tried this out, the usage of the for loop doesnt work here.

It throws an error since the property virtualNetworkRules does not exist if networkAcls is null:
`
  WARNING: Deployment template validation failed: 'The template variable 'virtualNetworkRules' is not valid: The language expression property 'virtualNetworkRules' doesn't exist, available properties are ''.. Please see https://aka.ms/arm-template-expressions for usage details.'.
`
See here: https://github.com/Azure/ResourceModules/runs/6025097692?check_suite_focus=true

**Comment by fblix** [comment]
@MrMCake I've generalized the approach a bit. Have a look at the PR if you want :)
