### ISSUE TITLE
[Bug Report]: incorrect resource name for Virtual Network diagnostic settings

### ISSUE THREAD

**Issue by tyconsulting** [Azure/ResourceModules#1288]
### Describe the bug

the name for the vnet diagnostic settings in the `virtualNetworks` module is incorrectly named as `appServiceEnvironment_diagnosticSettings` [HERE](https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.Network/virtualNetworks/deploy.bicep#L219)

### To reproduce

N/A

**Comment by MrMCake** [comment]
Hey @tyconsulting , thanks for the issue. Just opened a PR to get it sorted.
