### ISSUE TITLE
Add support for children having different tags than parent

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1299]
### Description

Currently the implementation for tags, is that all child resources inherit the tags of their parent. That could be a good approach if there are no other specific tags required for children. Also not sure why children would necessarily have the same tags as its parent.

Suggestion on implementation on parent deploy.bicep file:

```bicep
module parentType_childType 'childPath/deploy.bicep' = [for (child, index) in modules: {
   ...
   params: {
      tags: contains(child, 'tags') ? child.tags : tags
      ...
  }
}]

**Comment by AlexanderSehr** [comment]
Can be closed in favor of https://github.com/Azure/bicep-registry-modules/issues/2515
