### ISSUE TITLE
Other Items

### ISSUE THREAD

**Issue by segraef** [Azure/ResourceModules#13]
## Description

- be conscious about naming and avoid creating too many repositories
- make use of GitHub packages
- make use of Tags/Releases
- Sanitization Check
- Migrate Global Module Unit Test workflows
- Deploy to Azure Button
- Auto-Readme creation workflow
- remain linkage between ES and Modules @SomilGanguly 

## References
https://github.com/equinor/AzModules/blob/bicepifi/docs/Module-Guidelines.md#module-outputsreturns

**Comment by MariusStorhaug** [comment]
Can we find what of this has been done and split this into actionable isolated issues?

**Comment by segraef** [comment]
All points covered in 0.1-0.3 already.
