### ISSUE TITLE
[Feature Request]: Create issues for modules in missing modules table

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1319]
### Description

A list of all potential modules can be found here: [Excel](https://github.com/Azure/ResourceModules/files/7938614/CARMLModules.xlsx)

**Comment by rahalan** [comment]
the team feels that creating all those issues may be a bit too much. How instead automate a list of missing resources/children to follow a lean approach?

**Comment by rahalan** [comment]
Will serve new modules on a "is needed" basis
