### ISSUE TITLE
Inconsistent naming of NSGs IDs in compute/virtualmachines

### ISSUE THREAD

**Issue by AaronSaikovski** [Azure/ResourceModules#1323]
### Describe the bug

In the file ResourceModules/arm/Microsoft.Compute/virtualMachines/deploy.bicep
is currently
**networkSecurityGroupId**: contains(nicConfiguration, '**nsgId')** ? (!empty(nicConfiguration.nsgId) ? nicConfiguration.nsgId : '') : ''

but should be: 
**networkSecurityGroupId**: contains(nicConfiguration, '**networkSecurityGroupId')** ? (!empty(nicConfiguration.networkSecurityGroupId) ? nicConfiguration.networkSecurityGroupId : '') : ''

### To reproduce

see desc

**Comment by MrMCake** [comment]
We could even go a step further and call it  `networkSecurityGroupResourceId`. 

In any case I agree that we should update this, but will remove the label `bug` and replace it with `enhancement`.

Thanks for the submission @AaronSaikovski

**Comment by MrMCake** [comment]
Closed as PR was closed
