### ISSUE TITLE
[Bug Report]: Microsoft.Web/Sites intermittent deployment failures (missing dependency resource)

### ISSUE THREAD

**Issue by fblix** [Azure/ResourceModules#1333]
### Describe the bug

When trying to update the Microsoft.Web/Sites module(s), intermittent failures occur when running the pipeline to test-deploy the module.

The failure message is:
```
Status Message: Cannot find ServerFarm with name adp-adp-az-asp-x-001. (Code: NotFound)
 - Cannot find ServerFarm with name adp-adp-az-asp-x-001. (Code:)
 -  (Code:NotFound)
 -  (Code:)
```

Reason for this failure is, that the Microsoft.Web/sites resource gets linked to the serverfarm resource and if the sites resource gets removed, the serverfarm resource gets removed with it. It is then obviously missing on the next deployment run.

This behavior mostly happens between runs, but since Microsoft.Web/sites has 4 different test-deployments that happen, the bug also occurs if one of the agent-setups takes longer than the other.
For example, if one test-deployment is already completed (including the removal) and the one of them starts late, the late-starter will fail with the same bug. 

We would need some kind of logic to ensure the serverfarm resource is present before running the test-deployment for the Microsoft.Web/sites module.

### To reproduce

1. Run the dependency pipeline (make sure the serverfarm resource gets deployed)
2. Run the Microsoft.Web/Sites module-pipeline for the publishing flow (including the test-deploy step and with resource cleanup enabled)
3. Wait 5 minutes
4. Run the Microsoft.Web/Sites module-pipeline again.

**Comment by MrMCake** [comment]
@fblix this was mitigated today by deploying a dummy function app into the dependency resource to prevent that the serverfarm ends up being removed. See #1330

Linked to #243
