### ISSUE TITLE
[Feature Request]: Add pipeline runtime parameters to test e.g. only pester tests

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#1372]
### Description

Add pipeline runtime parameters to test e.g. only pester tests.

If one is only working on Pester tests it is a bit unfortunate that one has also to run the deployment tests.

However, when adding such a parameter we have to make sure a module is still only published if all tests ran (-> Including the deployment tests). This could be achived by adjusting the publish-job condition to only run if 'needs.xzy' is in status succeeded. Thus, if a dependency would be skipped (and hence the status would indicate it as such) the publish would still not run.

**Comment by MrMCake** [comment]
Tested a first implementation. While it is definetely possible with Azure DevOps, GitHub actions don't support conditional dependencies: https://github.com/Azure/ResourceModules/actions/runs/2457364409

As a result it is for example not possible to 'skip' the static validation, as the deployment validation will then refuse to run

**Comment by rahalan** [comment]
Team decides to implement as @MrMCake suggested
