### ISSUE TITLE
[Feature Request]: Add wiki documentation for direction on where to add prereq resources for a module

### ISSUE THREAD

**Issue by jontreynes** [Azure/ResourceModules#1416]
### Description

Add wiki documentation for direction on where to add prereq resources for a module

Example use case:
1. I want to create an additional PIP to be used as a prereq resource for Azure Firewall for adding multiple Pips to Azure Firewall. In order to do so, I need documentation to help me understand where tp add this additonal IP

Rough draft of documentation (@MrMCake helped draft this)
1. You'd need to add a parameter file to a corresponding folder in 'utilities/pipelines/dependencies'
2. And then reference it in the GitHub platform.dependencies.yml pipeline
3. As well as the Azure DevOps platform.dependencies.yml pipeline

**Comment by eriqua** [comment]
Since the new dependencies approach is currently 90% done, I wouldn't suggest to work on this issue anymore. Moving back to needs triage to discuss its closure.

**Comment by rahalan** [comment]
Team decides to close the issue, as the dependency pipeline will be gone soon.
