### ISSUE TITLE
[Feature Request]: The disk encryption set module should also support RBAC when granting the SP access to a referenced key vault.

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#1421]
### Description

The module `arm\Microsoft.Compute\diskEncryptionSets\deploy.bicep` has a feature implemented in which the MSI of the disk encryption set grants itself access policies to the key vault containing the encryption key.
However, this won't work if the key vault is configured to use RBAC access instead. We should implement a similar solution like in the [Synapse-Workspace module](https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Synapse/workspaces/.bicep/nested_cmkRbac.bicep) that also supports both.

**Comment by ahmadabdalla** [comment]
@MrMCake @eriqua even when enabling the permissions for the DES identity to the KV via Azure RBAC. The DES still thinks its lacking permissions;
![image](https://user-images.githubusercontent.com/28486158/190877465-fdd1685b-0b9f-46ac-a24e-9ebd547d28d3.png)

![image](https://user-images.githubusercontent.com/28486158/190877591-6f0e59d7-3816-4768-994d-c75122e70de3.png)

Subsequent DES deployments are not breaking though. I also could not find documentation that calls out that Azure RBAC permissions on the KV are supported for DES. So I think it is better if we can get an answer on that before we publish the DES module with this feature.. Thoughts?

Please check the feature branch ==> https://github.com/Azure/ResourceModules/tree/users/ahmad/1421_desRbac/modules/Microsoft.Compute/diskEncryptionSets

**Comment by MrMCake** [comment]
I've seen a similar effect when working on the CMK implementation for other modules. It was usually not well documented and more try and error than anything else. I'll try to look it up and add a link.

**Comment by MrMCake** [comment]
[This](https://github.com/Azure/ResourceModules/blob/users/alsehr/1791_CognitiveServices_Accounts/modules/Microsoft.CognitiveServices/accounts/.test/encr/dependencies.bicep#:~:text=%7D-,resource%20keyPermissions%20%27Microsoft.Authorization/roleAssignments%402022%2D04%2D01%27%20%3D%20%7B,%7D,-%40description() is an approach we use for e.g. Cognitive Services CMK:

```Bicep
resource keyPermissions 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
    name: guid('msi-${keyVault::key.id}-${location}-${managedIdentity.id}-Key-Reader-RoleAssignment')
    scope: keyVault::key
    properties: {
        principalId: managedIdentity.properties.principalId
        roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '12338af0-0e69-4776-bea7-57ae8d297424') // Key Vault Crypto User
        principalType: 'ServicePrincipal'
    }
}
```

**Comment by ahmadabdalla** [comment]
@AlexanderSehr I guess we can close this issue now? Based on the latest disk encryption set module changes?

**Comment by AlexanderSehr** [comment]
I believe so, yes. Thanks @ahmadabdalla
