### ISSUE TITLE
[Feature Request]: Granularity of Dependency Pipeline on a given Module PR

### ISSUE THREAD

**Issue by jontreynes** [Azure/ResourceModules#1425]
### Description

Is there a reason why every single dependency portion of the pipeline must run as part of the checker for this PR? It takes a long time for a PR involving the dependency pipeline to run its checks

[[Modules] 1154 Add Public IP to Azure Firewall by jontreynes · Pull Request #1392 · Azure/ResourceModules (github.com)](https://github.com/Azure/ResourceModules/pull/1392)

![image](https://user-images.githubusercontent.com/19974635/169608517-c4ec1963-5bec-44f2-8a0e-93e2851d0630.png)

By chance have we thought about this - and this may be a monstrosity of pipelines
`1 dependency pipeline per module` - this is to decouple the status checks

Where, for example: Consider Azure firewall only has one resource type dependency: virtual network 

The azurefirewall dependency pipeline would only need to run perhaps deploy resource group, deploy virtual network

Eventually we're going to want to get into the use case of not just min.parameters.json and max - but maybe 5 use case examples for parameter.n.json where n is a use case that requires n updates to dependency code (which would trigger this whole check you see in the screenshot). We may need to grow out of just one dependency pipeline for all module pr checks

If we wanted this example to be more modular we could have... even more pipelines

deploy.resourcegroup.pipeline, deploy.virtualnetwork.pipeline

dependency.azfirewall.pipeline which calls deploy.resourcegroup.pipeline, deploy.virtualnetwork.pipeline
dependency.bastion.pipeline which calls deploy.resourcegroup.pipeline, deploy.virtualnetwork.pipeline

It's a lot to maintain, but the benefits are that the PR checks don't have to run every single "dependency" in dependency pipeline that is not actually a dependency

Another piece to consider: One reason the current dependency azure pipeline may take a long time to run is because it requires an approval for every stage. The reason there's an approval on each stage is simply because the dependency github workflow may invoke a resource locking error.

It may be bearable if the dependency pipeline did not need to wait for approvals and we instead resolve the resource locking through automation - or simply just have one tool to run our dependency pipeline - github actions or azure pipelines. After all, the dependency pipeline is an internal tool.

**Comment by MrMCake** [comment]
The PR checks seems to be something Github automatically registers. If you check the dependency pipeline it actually has no trigger whatsoever. So for whatever reason the dependency pipeline is automatically listed - it is not by design.
However, if changing the dependency pipeline it is anyways recommended to run the pipeline once to make sure the changes did not break anything & work.
Last but not least, this is resolved as soon as we re-invented the dependency pipeline as part of the #329 issue

**Comment by jontreynes** [comment]
@MrMCake  thank you for the context. 

Yea, I guess that makes sense that we have to run the WHOLE thing especially for dependent resources. One example which is a worst case scenario:

Consider a user removes resource group validation-rg, all proceeding deployments will fail and the user should be blocked from merging the PR

I think "universal logic that allows modules to deploy their own dependencies instead. Ideally even in their own resource group (for Rg-Level resources) so that we can just remove the resource group instead of individual resources from it." would resolve this issue. I'll note this as a duplicate to #329

**Comment by MrMCake** [comment]
Hey @jontreynes , thanks for the extensive documentation. With the issue you referensed (and are currently creating PoCs for) we're actually moving one steps closer to this. The point with testing 'upstream' is definitely a good one, as we discussed this issue too - without a good solution yet. Hence I suggest we follow up, once the first step is done.
