### ISSUE TITLE
[Feature Request]: Automate Static Validation documentation

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1428]
### Description

We should improve the documentation of the Pester tests we run.

A standard Wiki page listing them is probably not the best choice as the list can soon get stale.

Discuss extending the pipeline generating the Wiki from docs with a function retrieving the test description from the global tests file and printing the list to an automatically generated Wiki page.

E.g. from the It: 
```
It "[<moduleFolderName>] outputs' description should start with a capital letter and contain text ending with a dot." -TestCases $deploymentFolderTestCases {
...
It '[<moduleFolderName>] All parameters in parameters files exist in template file (deploy.json)' -TestCases $deploymentFolderTestCases {
...
It '[<moduleFolderName>] All required parameters in template file (deploy.json) should exist in parameters files' -TestCases $deploymentFolderTestCases {
```
generate and publish
```
This is the list of Pester tests:
- Outputs' description should start with a capital letter and contain text ending with a dot.
- All parameters in parameters files exist in template file (deploy.json)
- All required parameters in template file (deploy.json) should exist in parameters files
```

**Comment by MrMCake** [comment]
I agree with the idee. This could be an update to one of the docs - probably a separate markdown document to not run into conflicts. The grouping could be done via the 'Describe' & 'Context' containers - while we should proably do a sweep to make sure all test descriptions make sense.
