### ISSUE TITLE
[Feature Request]: Discuss if ditching the feature to allow autogenerated unique names for resources

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1443]
### Description

Some modules e.g. vm, evhns, storage account, allow resource names to be autogenerated if no name value is provided.

To allow deployment idempotency, the unique name uses the resourcegroup id as input of a `uniqueString` function.

The problem of this approach is that two resources of the same type cannot be deployed to the same resource group due to the collision of the autogenerated name.

Discuss if this feature provides actual value and if not remove the functionality from the modules using it, cleaning up the code and converting the corresponding name parameter as Required.

---------------------------------
Update: modules with an empty default name:

- [x] Remove autogenerated unique name Microsoft.Storage\storageAccounts\deploy.bicep
- [x] Remove autogenerated unique name Microsoft.ServiceBus\namespaces\deploy.bicep
- [x] Remove autogenerated unique name Microsoft.Network\ddosProtectionPlans\deploy.bicep
- [x] #1756
- [x] Remove autogenerated unique name Microsoft.Consumption\budgets\deploy.bicep
- [x] Remove autogenerated unique name Microsoft.Compute\proximityPlacementGroups\deploy.bicep

**Comment by MrMCake** [comment]
Upvote for removing. The name generation can be implemented in the consuming deployment/template.

**Comment by rahalan** [comment]
Team decides to remove this feature from a module level
