### ISSUE TITLE
[Bug Report]: Locks are implemented as a single string instead of a string array

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1445]
### Describe the bug

A resource can have multiple locks and hence should be implemented that way. For example a resource may have both a 'read-only' and 'no delete' tag.

### To reproduce

Any resource deployment that supports locks has this issue.

**Comment by eriqua** [comment]
Does read-only allow deletion?

**Comment by eriqua** [comment]
Tested a read-only lock on a rg. I'm not able to delete it 
![image](https://user-images.githubusercontent.com/56914614/170872492-dd6118b0-d1fe-4296-b19b-24e97be6e585.png)

Although it's possible to apply more than one lock on the same resource I wonder what the actual use case is if one lock seems to include the other (open for discussion)

**Comment by MrMCake** [comment]
> Tested a read-only lock on a rg. I'm not able to delete it ![image](https://user-images.githubusercontent.com/56914614/170872492-dd6118b0-d1fe-4296-b19b-24e97be6e585.png)
> 
> Although it's possible to apply more than one lock on the same resource I wonder what the actual use case is if one lock seems to include the other (open for discussion)

Saw that too. Then again I wonder if we should make assumptions on a users behalf. From a usage perspective it doesn't really change (still supports auto-complete) but is closer to the Azure Resource Reference.

**Comment by eriqua** [comment]
I think it's at least something we may want to discuss. If this does not add true functionality I wonder if it's worthy to add complexity (replacing a parameter string with an array) and introduce a breaking change for all the modules. True that if we want to do that it's better soon than later, but I'm not 100% sure if that is needed.

**Comment by MrMCake** [comment]
Fair point. I'll bring it up with the team next week on Thursday then and will block its merge until then.

**Comment by MariusStorhaug** [comment]
Not sure I agree to the bug tag, as the functionality does work but is limiting. This seems to be a feature improvement to me.

Also curious to learn the scenarios where this is needed. Have a nagging voice in my head asking for a lean approach to this. If no-one needs it, why develop it?
