### ISSUE TITLE
Typo in jobs.ValidateModulePester.yml - Swapped assignment of deploymentSpId and tenantId

### ISSUE THREAD

**Issue by thomas-aure** [Azure/ResourceModules#1457]
### Describe the bug

It looks like the **deploymentSpId** and the **tenantId** assignment has been swapped here. 
Not sure what problem it might cause, but I just noticed this while troubleshooting another problem. The snippet below is from the jobs.ValidateModulePester.yml file.

`
if (-not [String]::IsNullOrEmpty('$(ARM_TENANT_ID)')) {
                $enforcedTokenList['**deploymentSpId**'] = '$(ARM_TENANT_ID)'
            }
            if (-not [String]::IsNullOrEmpty('$(DEPLOYMENT_SP_ID)')) {
                $enforcedTokenList['**tenantId**'] = '$(DEPLOYMENT_SP_ID)'
            }
`

### To reproduce

Check the code.

### Code snippet

I would assume it should be like this; 
`
if (-not [String]::IsNullOrEmpty('$(ARM_TENANT_ID)')) {
                $enforcedTokenList['**tenantId**'] = '$(ARM_TENANT_ID)' }
if (-not [String]::IsNullOrEmpty('$(DEPLOYMENT_SP_ID)')) {
                $enforcedTokenList['**deploymentSpId**'] = '$(DEPLOYMENT_SP_ID)' }
`

**Comment by akata72** [comment]
PR #1469
