### ISSUE TITLE
[Feature Request]: Document generic guidance on how to update an "internalized" instance of CARML to the latest version

### ISSUE THREAD

**Issue by matebarabas** [Azure/ResourceModules#1459]
### Description

Provide guidance and high-level steps including but not limited to:
- How do I update my "internalized" instance of CARML and its modules to the latest available version?
- Types of changes
  - Changes to the CI framework
  - Design changes to all modules
  - Specific updates to modules
  - etc.
- When/how a CARML customer would need to update their module version, considering they've applied customizations.

**Comment by elanzel** [comment]
Adding a temp section in branch [users/ee/1459_internalizedCarml](https://github.com/Azure/ResourceModules/tree/users/ee/1459_internalizedCarml) 

Following a possible review of the Wiki index as faceted navigation and removing duplicates :
	• Home
	• Overview (or The context = CARML overview page)
		○ The library (+ link to https://github.com/azure/ResourceModules/wiki/The%20library)
		○ The CI environment (+ link to >> https://github.com/azure/ResourceModules/wiki/The%20CI%20environment)
	• Users Quickstart Guide
		○ Getting started
			§ Scenario 1: Consume module library only ( + link to solution creation)
			§ Scenario 2: Onboard module library and CI environment ( + link to solution creation*)
		○ Fetching latest updates
			§ Scenario 1: Consume module library only
			§ Scenario 2: Onboard module library and CI environment
	• Contribution Guide
		○ Contributing to the documentation  
		○ Contributing to the module library (+ links to other contribution pages needed: contribution flow, module readme, etc)
		○ Contributing to the CI environment
	• Interoperability
	• Known issues


	*=Deploy Template in module usage section https://github.com/azure/ResourceModules/wiki/The%20library%20-%20Module%20usage#deploy-template can be merged with solution creation examples https://github.com/azure/ResourceModules/wiki/Solution%20creation#examples ?

**Comment by elanzel** [comment]
@matebarabas
can you have a look if it contains what you meant to have in place?
Then i'll need someone for a review of the English i think
