### ISSUE TITLE
[Feature Request]: Optimize performance of `Set-EnvironmentOnAgent`

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1466]
### Description

We can apply several optimizations like
- Move the `Get-Module -ListAvailable`
- Add the installed Az modules to the path: `$Env:PSModulePath += ":/usr/share/az_7.3.2"` (should be done in a dynamic way to account for newer versions)
- Should be tested for both ADO & GH as they use the same installed software

**Comment by MariusStorhaug** [comment]
@MrMCake Suggest doing some kind of sort on folders starting with az_ in the usr/share/ folder for linux machines, and C:\Modules\ for windows, ref the code from the Azure/Powershell action source code. https://github.com/Azure/powershell/blob/b953340ea4fa4af9573e6b96baba1ce7d28ca5a8/lib/Utilities/Utils.js#L33

**Comment by MrMCake** [comment]
> @MrMCake Suggest doing some kind of sort on folders starting with `az_*` in the `usr/share/` folder for linux machines, and `C:\Modules\` for windows, ref the code from the Azure/Powershell action source code. https://github.com/Azure/powershell/blob/b953340ea4fa4af9573e6b96baba1ce7d28ca5a8/lib/Utilities/Utils.js#L33

@MariusStorhaug Currently the script has a disclaimer 'Optimized for Linux' as all installations are using Linux commands. Should we anyways support both for the PowerShell cmdlets, or go all in and only handle linux?
