### ISSUE TITLE
[Bug Report]: Bicep compilation fails due to CLI version on ubuntu-agents

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1471]
### Describe the bug

With the latest CLI version (2.37.0) used by the ubuntu-20.04 agents, a bug was introduced that renders the output of the `'az bicep build --f (..) --stdout'` command empty, unless an additional `'--no-restore'` flag is passed along with it. 

This is very bad, as the function is used by all our Pester tests (alongside some other logic).

This bug was already brought up here
- https://github.com/Azure/azure-cli/issues/22621

And a Pull Request to fix it is open here
- https://github.com/Azure/azure-cli/pull/22685

For the time being, we can either try to downgrade the CLI version in our pipeline (to e.g. 2.28.0), use the `'--no-restore'` flag (which may have side-effects) or wait until the PR is merged and the agents updated.

### To reproduce

Run any template with the `'az bicep build --f (..) --stdout'` command. The result will be empty.

### Code snippet

```Bicep
az bicep build --f (..) --stdout
```

**Comment by akata72** [comment]
Thanks for reporting this. This was the bug I was chasing.  :-)
