### ISSUE TITLE
[Feature Request]: Missing parameter test case on resource locks for NetworkWatcher

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1488]
### Description

The resource `Microsoft.Network/networkWatchers` is missing a test on locks.

Based on readme review on PR #1446 - Readme file did not contain updates on locks, assuming there is no test for this.

**Comment by MrMCake** [comment]
@MariusStorhaug  I excluded the lock on purpose as we do not have the removal enabled.
