### ISSUE TITLE
[Feature Request]: Disuss the default 'passing locks between modules' behavior

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1493]
### Description

Building on top of
- #239 and
- #1446

It turned out there is a missing alignment how to treat locks across all module references.

Up until now we agreed
- Children should not receive the lock from their parent via our template (as this is done automatically in Azure) unless specified otherwise in the parameter file
- Cross-module referenced modules should receive the lock from the invoking module (e.g. PIP for VM) unless specified otherwise in the parameter file

However, regarding the 2nd point, it is unclear how to treat 'Extension' resources such as Private Endpoints. Technically, they are cross-referenced, but that doesn't mean it necessarily makes sense to lock them automatically with the invoking module/

**Comment by rahalan** [comment]
Team agrees on the suggestion
