### ISSUE TITLE
[Feature Request] Create Azure DevOps example for pipeline-orchestration

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#1514]
### Discussed in https://github.com/Azure/ResourceModules/discussions/1474

<div type='discussions-op-text'>

<sup>Originally posted by **JQUINONES82** June  3, 2022</sup>
https://github.com/azure/ResourceModules/wiki/Solution%20creation

It would be nice to have an example for Azure Devops as there is only a Github reference</div>

**Comment by MrMCake** [comment]
Note, difference approaches. E.g.
- Azure DevOps Pipeline Orchestration using the Mulit-Repository approach
- Azure DevOps Pipeline Orchestration using the Azure DevOps Artifacts

**Comment by segraef** [comment]
> Note, difference approaches. E.g.
> 
> * Azure DevOps Pipeline Orchestration using the Mulit-Repository approach
> * Azure DevOps Pipeline Orchestration using the Azure DevOps Artifacts

Currently we have [PO GH (Multi)](https://github.com/azure/ResourceModules/wiki/Solution%20creation#pipeline-orchestration), do we also want PO (Single/Multi) ADO, PO ADO (Artifacts), TO GH, as well as TO ADO? I suppose TO was never with Multi, Multi was always only for PO as far as I remember.

**Comment by segraef** [comment]
MR PO via ADO ready, doco in progress

**Comment by eriqua** [comment]
@segraef can this issue be closed?

**Comment by AlexanderSehr** [comment]
Resolved in #1862
