### ISSUE TITLE
[Feature Request]: Align all modules to cross referenced approach

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1531]
### Description

This is a requirement for release 0.6
Modules still using nested modules should cross reference existing modules instead. The following modules need to be aligned:

- [x] Resource Groups referencing Locks @eriqua
    > Note: A resource's scope must match the scope of the Bicep file for it to be deployable. You must use modules to deploy resources to a different scope. This is the reason for the nested module. If an alternative cannot be found, document the exception.
    > Note: Solved by #1547 
- [x] Disk Encryption referencing KeyVault Access Policies @eriqua
    > Note: solved by #1548 
- [x] Azure Firewall referencing PIP @eriqua 
    > Note: solved by #1549
- [x] VirtualMachines referencing NIC
    > Note: Removed from the list. The VM module references a nested template that in turns cross references both PIP and NIC modules to be able to deploy n-NICs with m-PIPs each. The team agrees the implementation will stay as it is until eventually issue #1410 will be worked on and closed.
- [x] API management referencing Authorization Servers
    > Note: removed from the list. Not related to cross-reference. It's a duplicated nested child resource due to keyvault secret retrieval needed.

**Comment by MrMCake** [comment]
One comment @eriqua , the VirtualMachines modules actually does reference the NIC module - though it may not look like that on first sight.

What it does is reference a nested template that deploys n-PIPs (using a cross-module reference) and a NIC (using a cross-module reference).

**Comment by eriqua** [comment]
All modules have been worked on. Closing.
