### ISSUE TITLE
[Feature Request]: [ReadMe] list cross referenced modules (and test readme)

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1550]
### Description

Some users may want to keep only modules they are interested in when cloning/forking or downloading a CARML release. They may want to remove all the others. They need to know which modules are cross referenced by the modules they want to keep, to prevent module failures.

Readmes should list cross referenced modules so that users know which modules they should keep together with the ones they're primarily interested in.

Suggestion:
- Update Set-ModuleReadme with a new section `Cross Referenced Modules`
- Pupulate the section leveraging regex as all cross referenced modules in the template start with `module <symbolicName> '../../<PathToCrossReferencedModule>/deploy.bicep'`. Retrieve all `<PathToCrossReferencedModule>`.
- Update static validation: New Pester test to check if all cross referenced modules are listed in the readme file.

**Comment by MrMCake** [comment]
To detect the dependencides (I guess through multiple levels) we can use the utility [Get-LinkedLocalModuleList.ps1](https://github.com/Azure/ResourceModules/blob/main/utilities/tools/Get-LinkedLocalModuleList.ps1).
