### ISSUE TITLE
[Feature Request]: [Pipelines] update module pipelines trigger for changes on all cross referenced modules

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1551]
### Description

Update module pipelines for all modules cross-referencing other modules.
Add trigger for changes to all cross referenced modules in addition to the main one.

Example: the VM module pipeline shouldn't be triggered only on changes to the VM module but also on changes to the NIC and PIP modules

Discuss/brainstorm if that could cause any side effects (e.g. unwanted concurrent module pipeline runs).

**Comment by MrMCake** [comment]
We have to be careful not to trigger the same pipeline multiple times simulatiously

**Comment by MrMCake** [comment]
I guess it would require us to add some logic into the pipeline(s) that catches all dependencies and trigger the corresponding pipelines for the current branch. However, this will NOT solve the issue of conflicting pipeline runs.

**Comment by MrMCake** [comment]
If we'd go for 'maintaining' dependency triggers in each pipeline, we should implement a test to make sure this triggers are up to date (cc: @eriqua)

**Comment by MrMCake** [comment]
Tagged with 'needs further discussion' to discuss the concept (and potential solution ideas) with a bigger group

**Comment by rahalan** [comment]
Team agrees to solve it with the following solution: Triggers need to be maintained and should trigger all module pipelines that rely on a certain module that is changed. A test also needs to be implemented for a static validation if all the referenced modules are in the trigger (the logic for that is already in the script to generate ReadMe files).
