### ISSUE TITLE
[Bug Report]: Serverfarm is Optional for Site, but is not working without.

### ISSUE THREAD

**Issue by tjav** [Azure/ResourceModules#1557]
### Describe the bug

The microsoft.web/sites module is not creating a serverfarm if no serverfarm resources id is presented. Or the parameter should be required.

![image](https://user-images.githubusercontent.com/15814300/174577121-5b9c49d0-e9f6-403d-beec-77338c89c014.png)

### To reproduce

Deploy the sites module without serverfarmid
 

### Relevant log output

```Shell
Line |
 240 |              New-AzResourceGroupDeployment @DeploymentInputs
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 14:37:40 - The deployment 'DeployFA-20220614T1406081475Z'
     | failed with error(s). Showing 1 out of 1 error(s). Status
     | Message: Parameter ServerFarmId is null or empty. (Code:
     | BadRequest)  - Parameter ServerFarmId is null or empty.
     | (Code:)  -  (Code:BadRequest)  -  (Code:)   CorrelationId:
     | 6c38a053-5b79-49a4-8290-9093a62d31af
```

**Comment by itpropro** [comment]
I think we should make the parameter `serverFarmResourceId` required. Automatically creating a app service plan would be too much overhead with all the dependencies on the correct type like pricing implications and limitations on OS, features, etc..

**Comment by rahalan** [comment]
A solution could be to create a server farm, if none is specified (like we handle it with resources, that don't specify a PIP and then we create one)

**Comment by MrMCake** [comment]
@rahalan, we used to do that in this module, but like @itpropro stated, the overhead was quite big. For the time being I'd suggest to set the paramter to required and revisit it if we feel it's necessary. The status quo has to be fixed anyways.
