### ISSUE TITLE
[Feature Request] BREAKING change: Rename `.parameters` folder

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1577]
### Description

As we're getting closer to the dependency reimplementation and may use `.bicep` files instead of parameter files, we may want to prepare this change by renaming the parameter folder. 

I'd suggest `.deploymentTests` which should be generic enough to cover both parameter & dependency files (as it may take some time to work through all modules) - and avoid any confusion with e.g. the static validation that lives somewhere else (.global folder).

- Other suggestions
  - .tests
  - .validation 

The change itself should be relatively easy to implement and can be implemented for example side-by-side with the renaming of the `arm` folder #1127 .

### Update

We agreed upon using `'.test'`.

**Comment by itpropro** [comment]
Just adding my text from #1583:

[...] As for the folder rename, I think we should go with `.test` as folder name, as it would comply to most OSS frameworks and tools as well as development languages. Even if we have multiple types of tests in there, we can easily distinguish them by name or folder. [...]

**Comment by MrMCake** [comment]
@itpropro, we agreed on going with `.test` ✅
