### ISSUE TITLE
[Feature Request]: Align CognitiveServices CMK implementation once provider bug is fixed

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#1590]
### Description

Once the [compiler bug](https://github.com/Azure/bicep/issues/7066) for CognitiveServices, submitted to the Bicep team, is fixed,we should align its CMK implementation (e.g., by using `existing` resources) as per issue #1484.

**Comment by MrMCake** [comment]
Note to self: Should be revisted as the PG stated they fixed the issue no their end and it should be resolved with the next release (which likely happened by now)

**Comment by MrMCake** [comment]
Re-Implemented and [tested](https://github.com/Azure/ResourceModules/actions/runs/3343292731/jobs/5536406587) the logic & the provider issue still exists in the latest API Version. Will re-test with the next release.
