### ISSUE TITLE
[Bug Report]: Fix trigger for ServiceFabric/Clusters

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1598]
### Describe the bug

Trigger for ServiceFabric/Clusters does not trigger in ADO, on changes to the modules files, as it is missing a relative folder path of /ARM/.

### To reproduce

1. Connect the ADO pipeline for ServiceFabric/Clusters
2. Do a change in the module files
3. See that the CI pipeline for the module does not automatically trigger.

**Comment by MrMCake** [comment]
Was resolved in PR #1601
