### ISSUE TITLE
[Bug]: Lock removal is not 100% robust 

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#1616]
### Description

The removal of locks is unfortunately not 100% robust in that some pipeline still fail due to locks applied to the resources. Usually when checking set resource after, the lock is actually removed - leaving the impression that it's still a timing issue.

As it is currently implemented, we remove a lock and wait for a couple seconds before we continue. This is done as (while a lock is already removed) it takes some time for Azure to get that.

Maybe we should increase the wait time - of find another way...

**Comment by rahalan** [comment]
Issues seems to be solved
