### ISSUE TITLE
[Bug Report]: Incorrect file reference path in documentation

### ISSUE THREAD

**Issue by arnoldna** [Azure/ResourceModules#1630]
### Describe the bug

Under the "Getting started Scenario 2 Onboard module library and CI environment" section item number 5 ([Update module parameter files](https://github.com/azure/ResourceModules/wiki/Getting%20started%20-%20Scenario%202%20Onboard%20module%20library%20and%20CI%20environment#5-update-module-parameter-file)) references a ".test" directory in the module file path. This directory does not exist in the modules.

### To reproduce

https://github.com/azure/ResourceModules/wiki/Getting%20started%20-%20Scenario%202%20Onboard%20module%20library%20and%20CI%20environment#5-update-module-parameter-file

**Comment by MrMCake** [comment]
@arnoldna , actually we do since a short while ago. #1612 . Once you fetch from upstream you should see the changed folder.

**Comment by arnoldna** [comment]
Resolved by commit [#1612](https://github.com/Azure/ResourceModules/pull/1612)
