### ISSUE TITLE
[Bug Report]: Microsoft.Sql administratorLogin is not designated as a secure string

### ISSUE THREAD

**Issue by mcarter106** [Azure/ResourceModules#1652]
### Describe the bug

Deployment Example 2 when deploying ResourceModules/modules/Microsoft.Sql/ has a get from key vault as shown below:
params: {
    name: '<<namePrefix>>-az-sqlsrv-x-001'
    lock: 'CanNotDelete'
    administratorLogin: kv1.getSecret('administratorLogin')
    administratorLoginPassword: kv1.getSecret('administratorLoginPassword')
    location: 'westeurope'

Using this template throws an error that the function can not be used because the administratorLogin is not designated as a secure string.  Either the parameter should be updated as a secure string or the example updated to be a general parameter.

### To reproduce

To reproduce the issue: 
Create a deployment using Deployment Example 2

### Code snippet

```Bicep
params: {
    name: '<<namePrefix>>-az-sqlsrv-x-001'
    lock: 'CanNotDelete'
    administratorLogin: kv1.getSecret('administratorLogin')
    administratorLoginPassword: kv1.getSecret('administratorLoginPassword')
    location: 'westeurope'
```

**Comment by rahalan** [comment]
Needs further investigation. A possible solution could be to set AdminLogin parameter sample as a simple string and not a keyvault reference

**Comment by MrMCake** [comment]
for reference: 
![image](https://user-images.githubusercontent.com/5365358/178601743-c12e7bc7-b95c-416b-994e-1dc3b103282d.png)
