### ISSUE TITLE
[Feature Request]: Add Customer Managed key option to CARML deployment

### ISSUE THREAD

**Issue by mcarter106** [Azure/ResourceModules#1653]
### Description

Many customers require a customer managed key for all resources.  If the option to enable a customer managed key could be enabled in the module that would be very helpful.

Thank you

**Comment by eriqua** [comment]
Hi @mcarter106 thanks a lot for opening an issue. 

We have CMK implemented for some modules already (e.g. storage accounts, automation accounts, data factory) and we're in the process of extending the coverage [Ref: e.g. issues #792, #1590 ].

Is there a module missing CMK implementation you are referring to in particular?

**Comment by tyconsulting** [comment]
Databricks is missing CMK. its a tricky situation, since CMK for Databricks workspaces must be enabled AFTER the creation of workspace

**Comment by rahalan** [comment]
Issue needs to be split up. One issue per module that is missing CMK. First step would be to assess, which modules are missing CMK implementation. After the assessment and the creation of issues per module, this one can be closed
