### ISSUE TITLE
[Bug Report]: Duplicate code Microsoft.Networking/networkSecurityGroups

### ISSUE THREAD

**Issue by JulienFloris** [Azure/ResourceModules#1663]
### Describe the bug

@MrMCake,
Is there a reason why there is duplicated code in [/Microsoft.Network/networkSecurityGroups/deploy.bicep](https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep)

This is introduced with pull request  #1102 

There is a input param "securityRules" that deploy the Security Rules in the Parent Resource and then for a second time with the same input param for the child resource. 
And both seem to deploy the exact same thing.

### To reproduce

.

**Comment by MrMCake** [comment]
I hope this makes sense. I will close the bug for now. Feel free to re-open it again if anything is unclear and I'll try to elaborate :)
