### ISSUE TITLE
Remaining Modules

### ISSUE THREAD

**Issue by segraef** [Azure/ResourceModules#168]
## Description

- [x] Microsoft.ContainerRegistry/registries @Msanzdelrio 
- [x] Microsoft.DataFactory/factories @segraef 
- [x] Microsoft.EventHub/namespaces/eventhubs @SomilGanguly 
- [x] Microsoft.ServiceFabric @SomilGanguly 
- [x] Microsoft.Compute/virtualMachines @eriqua 
- [x] Microsoft.DocumentDB (CosmosDB) @Msanzdelrio

**Comment by MrMCake** [comment]
Opened new issue #328 to fix and re-add Service Fabric
