### ISSUE TITLE
[Bug Report]: Network Application Gateway deployment validation is failing

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1717]
### Describe the bug

After updating the API version to a most recent one, the template is not valid anymore and the deployment validation fails on the Test-AzDeployment step with `ApplicationGatewayRequestRoutingRulePriorityCannotBeEmpty` error.

Update the module and the tests to support the `priority` setting which became mandatory in recently updated API version 2021-08-01. 

Ref ARR docs https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2021-08-01/applicationgateways?tabs=bicep

### To reproduce

Run the Network: ApplicationGateway pipeline

### Relevant log output

```Shell
"Code": "ApplicationGatewayRequestRoutingRulePriorityCannotBeEmpty",
    "Message": "Priority for the request routing rule /subscriptions/***/resourceGroups/validation-rg/providers/Microsoft.Network/applicationGateways/carml-az-apgw-x-001/requestRoutingRules/public443-appServiceBackendHttpsSetting-appServiceBackendHttpsSetting cannot be empty. All request routing rules should have a priority defined starting from api-version 2021-08-01",
    "Target": null,
    "Details": []
  }
```

**Comment by elanzel** [comment]
Issue already solved in a duplicated bug log entry:  https://github.com/Azure/ResourceModules/issues/1741
See PR #1743
