### ISSUE TITLE
Secrets in repositories and exporting secrets in modules

### ISSUE THREAD

**Issue by aavdberg** [Azure/ResourceModules#1796]
@rahalan and @MrMCake I agree with @christiankuhtz this repository is a example for others to use and putting secret in code is a no no private and also in public repositories.

The same as exporting secrets in a module.

_Originally posted by @aavdberg in https://github.com/Azure/ResourceModules/issues/1157#issuecomment-1220639778_

**Comment by AlexanderSehr** [comment]
Hey @aavdberg, I will close this issue as we almost concluded the rework to the new dependency approach (#1791) which also means we don't need the Public SSH Key for our Linux deployments anymore in code - instead the key is generated during a pipeline's run, used, and deleted without ever exposing the value in the code.
