### ISSUE TITLE
Documentation, Wiki and FAQ

### ISSUE THREAD

**Issue by segraef** [Azure/ResourceModules#19]
## Description

A common set of FAQs  and Wiki needs to be set up.
General documentation is required for

- What is a Module?
- [Module Dependencies?](https://dev.azure.com/servicescode/infra-as-code-source/_wiki/wikis/Wiki/3844/Module-Dependencies)
- What is a Module used for?
- How to deploy a Module (with PS, CLI, AzOps, TF, ...)?
- What is a Workload?
- How have Modules to do with Azure Landing Zones?
- How does this fit into CAF?
- What collaboration platform is recommended (GitHub/ADO)?
- What is IaC?
- Azure Resource Manager Reference?
- What are GitHub Actions and Workflows?
- Are Azure Pipelines supported?
- [How to contribute a Module?](https://github.com/Azure/Modules/wiki#how-to-contribute-a-module)
- How to structure a Module (ARM Template) according to an ARM Template syntax?
- How to structure a Module (Bicep Module) according to an ARM Template syntax?
- What are [Constructs](https://github.com/Azure/ResourceModules/tree/main/constructs)?

Other
- naming in general for parameters in modules to remain consistent naming structure within templates and files (input parameter as well as output parameters, camelcasing)

## References

https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/file
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/syntax
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/workloads#what-is-a-workload
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/extension-resource-types
https://docs.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code
https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/infrastructure-as-code
https://docs.microsoft.com/en-us/azure/architecture/framework/devops/automation-infrastructure

**Comment by ahmadabdalla** [comment]
++ Authoring / Design Principals

**Comment by ahmadabdalla** [comment]
Reading the [wiki](https://github.com/Azure/Modules/wiki#how-to-contribute-a-module). I think we are leaving wiggle room in the guidelines for different approaches to be followed, which can limit the standardization like automation. A good example is the web app that's in the guideline. 

functionApp [module] is good to have as a module, but cannot be deployed in isolation, same as sites, where they need to hook into their parents, respectively. So, what is the principal that needs to be followed so that we are able to deploy each component in isolation. And how much is too much for the levels of child resources?

**Comment by MrMCake** [comment]
Traditionally we took care of any required dependencies in the 'Master templates' that link to the ResourceModules as linked templates. 
E.g. One would link to the ResourceGroup deployment module, VNET,  etc. and use this template orchestration to deploy an entire estate.

Now, regarding the tests for the individual modules it's a different story. Here I see to options. Either:
1. Deploy a persistent set of resources to be referenced by all modules for testing (e.g. VNets, NSGs, LA, etc.) which works quite well as long as we're not talking about constly resources
2. Add some logic to each module that is capable to deploy its dependencies for testing and remove them after. While this approach provides the most isolution it's naturally more effort to create and maintain. However, one the plus site it would work also for scenarios for approach #1 would lack.

**Comment by ahmadabdalla** [comment]
How does an idea of having 'settings.json' look like?

```json
{
"dependencies": [
{
"type": "Microsoft.Network/networkSecurityGroups",
"resourceId": "x"
}
]
}
```

Or create a folder called "dependencies" and add parameter files for the dependency resource (I.e microsoft.network_networkSecurityGroups.parameters.json)

Just thinking out loud :)

**Comment by segraef** [comment]
The team covered a lot of content around the Modules hence closing for now.
Some points weren't met but could be potentially resumed in future.
