### ISSUE TITLE
[Bug Report]: KeyVault private endpoint does not create an A record

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#1977]
### Describe the bug

When deploying a KeyVault with an private endpoint, no A Record is created by Azure, which leads to an inaccessible KeyVault

### To reproduce

privateEndpoints: [
      {
        name: 'nodepools-to-akv'
        subnetResourceId: vnetNodePoolSubnetResourceId
        service: 'vault'
        privateDnsZoneResourceIds: [
          akvPrivateDnsZones.outputs.resourceId
        ]
      }
    ]

**Comment by cjnova** [comment]
I'm using tag 0.6.0 modules. It works perfectly. Removing later the keyvault also removes the A entry. Before to do the registration I have the privatezone created. Need to check with latest version.

**Comment by rahalan** [comment]
Error was on my end. When rewriting the privateDnsZone parameter, I made an "s" too much. 
![image](https://user-images.githubusercontent.com/61878316/190626817-f7d8fe41-8e10-4f03-a28f-845a63ca2ced.png)
