### ISSUE TITLE
[Feature Request]: Add module for Azure SQL Server encryptionProtector

### ISSUE THREAD

**Issue by tyconsulting** [Azure/ResourceModules#1980]
### Description

Currently there is no module for `Microsoft.Sql servers/encryptionProtector` resource. this is required for configuring SQL TDE using CMK. Bicep reference can be found [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers/encryptionprotector?pivots=deployment-language-bicep)

**Comment by tyconsulting** [comment]
reference ARM template: https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/sql/sql-encryption-protector-byok

 in order to configure CMK, you also need to have a `microsoft.sql/servers/keys` resource

**Comment by AlexanderSehr** [comment]
Already implemented by #3025
