### ISSUE TITLE
[Feature Request]: Merge the classic common parameter tests with the max parameter tests

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#1987]
### Description

As per a previous discussion, we should simplify our parameter tests and e.g. merge the 'max' tests into our 'common' tests (once the new dependency approach for a module is merged).

The reason is that we consider the 'common' test to test the module & ideally as many parameters as possible anyways which is the same purpose the 'max' tests serves.

When reviewing the correponding files it turned out that usually the current 'parameter.json' test files are just a subset of the 'max.parameter.json' test files.

- [x] Merge common and max tests for `AnalysisServices/servers`

**Comment by eriqua** [comment]
Closed by #4188
