### ISSUE TITLE
[Feature Request]: Add module Microsoft.PolicyInsights remediations

### ISSUE THREAD

**Issue by Azure-hacker** [Azure/ResourceModules#2009]
### Description

Quick win would be to add the Module Policy Insights into the collection of modules, as this could be required by some organizations to create remediations automatically.
https://docs.microsoft.com/en-us/azure/templates/microsoft.policyinsights/remediations?pivots=deployment-language-bicep

**Comment by rahalan** [comment]
Should operations be part of IaC? Team needs to discuss further.

**Comment by MrMCake** [comment]
It's a proper Resource Type - hence I see no need to 'not' have a module for it.

**Comment by eriqua** [comment]
@ahmadabdalla does PR #2544 close this issue as well?

**Comment by ahmadabdalla** [comment]
@eriqua indeed it does. Thanks for flagging it.

**Comment by ahmadabdalla** [comment]
@Azure-hacker Microsoft.PolicyInsights Remediation is now available [here](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.PolicyInsights/remediations)
