### ISSUE TITLE
[Feature Request]: Update module overview feature table with CMK feature

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2016]
### Description

The module overview feature table is available in the Wiki [here](https://github.com/Azure/ResourceModules/wiki/The%20library%20-%20Module%20overview)

Modules having CMK implemented should also be listed.

This issue is about:
- find a way to identify if CMK is implemented in each module
- update the script used to generate the overview [here](https://github.com/Azure/ResourceModules/blob/main/utilities/tools/Get-ModulesFeatureOutline.ps1)

**Comment by MrMCake** [comment]
Suggestion: Let's use the CMKName parameter to identify whether the feature is implemented or not. This parameter is used in 99% of the cases to identify CMK. The only exceptions I am aware of are cases like [CognitiveServices](https://github.com/Azure/ResourceModules/issues/1590) which are blocked by a provider bug

**Comment by AlexanderSehr** [comment]
Actually implemented for AVM in the AVM repository
