### ISSUE TITLE
Fix failing Synapse Workspaces

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2032]
Module pipeline failing on static validation. Template fails to compile with
`Error BCP270: The scope used for this declaration is ambiguous. A resource or module must only reference a single scope.`

**Comment by eriqua** [comment]
Looks related to https://github.com/Azure/bicep/issues/8403

**Comment by MrMCake** [comment]
For the time being, added to `Known Issues` in #2033
