### ISSUE TITLE
[Feature Request]: Uplift ACR module to use the latest API version 2022-02-01-preview

### ISSUE THREAD

**Issue by tyconsulting** [Azure/ResourceModules#2036]
### Description

Additional properties are introduced to API version 2022-02-01-preview: https://docs.microsoft.com/en-us/azure/templates/microsoft.containerregistry/change-log/registries#2022-02-01-preview

Please uplift the api version and add the newly introduced properties as parameters

**Comment by MariusStorhaug** [comment]
Hi @tyconsulting, is this resolving #2036 ?

**Comment by eriqua** [comment]
This looks solved by #2037. Back to triage to propose its closure.

**Comment by AlexanderSehr** [comment]
This parameter sounds very much like something we'd want for a Public Registry.
