### ISSUE TITLE
[Feature Request]: Consider publishing an actual 'latest' version too

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#2117]
### Description

Currently, we publish latest minor and latest patch, in addition to the default patch version. However, we don't actually provide a latest major. 

While it wouldn't be a best practice to use that version in production environments it would probably still be intersting for testing purposes and e.g. aligned with other means like the PS-Gallery.

**Comment by MariusStorhaug** [comment]
What is the use case we want to cover? Is there a requirement from somewhere/someone?

**Comment by AlexanderSehr** [comment]
Implemented with this [commit](https://github.com/Azure/ResourceModules/commit/ee9daa077d59a401f6ca43007b2403505aacb0ab)
