### ISSUE TITLE
[Bug Report]: Example Storage Account has typo in parameter

### ISSUE THREAD

**Issue by Robbertbbb** [Azure/ResourceModules#2122]
### Describe the bug

privateDnsZoneGroups should be privateDnsZoneGroup

### To reproduce

\bicep\modules\Microsoft.Storage\storageAccounts\.test\parameters.json

change privateDnsZoneGroups  > privateDnsZoneGroup

**Comment by milescattini** [comment]
Hey @Robbertbbb

This name follows the resource and API [naming convention](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/privateendpoints/privatednszonegroups?pivots=deployment-language-arm-template).

**Comment by Robbertbbb** [comment]
ah i see
then  line 88 in the 
https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Storage/storageAccounts/deploy.bicep
privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}

should be changed to from privateDnsZoneGroup > privateDnsZoneGroups

and 
https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Network/privateEndpoints/deploy.bicep
also changed to privateDnsZoneGroup

and 
https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/deploy.bicep
as well

all the other files.
 C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.AppConfiguration\configurationStores\deploy.bicep (1 hit)
	Line 223:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.AppConfiguration\configurationStores\readme.md (1 hit)
	Line 489:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Automation\automationAccounts\deploy.bicep (1 hit)
	Line 387:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Batch\batchAccounts\deploy.bicep (1 hit)
	Line 252:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Batch\batchAccounts\readme.md (2 hits)
	Line 263:         privateDnsZoneGroup: {
	Line 410:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Cache\redis\deploy.bicep (1 hit)
	Line 256:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Cache\redis\readme.md (1 hit)
	Line 403:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.CognitiveServices\accounts\deploy.bicep (1 hit)
	Line 256:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.CognitiveServices\accounts\readme.md (2 hits)
	Line 586:         privateDnsZoneGroup: {
	Line 727:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.ContainerRegistry\registries\deploy.bicep (1 hit)
	Line 343:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.ContainerRegistry\registries\readme.md (2 hits)
	Line 488:         privateDnsZoneGroup: {
	Line 655:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.DataFactory\factories\deploy.bicep (1 hit)
	Line 279:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.EventGrid\topics\deploy.bicep (1 hit)
	Line 153:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.EventGrid\topics\readme.md (2 hits)
	Line 321:         privateDnsZoneGroup: {
	Line 430:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.EventHub\namespaces\deploy.bicep (1 hit)
	Line 270:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Insights\privateLinkScopes\deploy.bicep (1 hit)
	Line  83:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Insights\privateLinkScopes\readme.md (1 hit)
	Line 301:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.KeyVault\vaults\deploy.bicep (1 hit)
	Line 289:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.KeyVault\vaults\readme.md (1 hit)
	Line 512:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.MachineLearningServices\workspaces\deploy.bicep (1 hit)
	Line 282:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.MachineLearningServices\workspaces\readme.md (2 hits)
	Line 442:         privateDnsZoneGroup: {
	Line 646:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Network\privateEndpoints\readme.md (1 hit)
	Line 249:     privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.RecoveryServices\vaults\deploy.bicep (1 hit)
	Line 280:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.RecoveryServices\vaults\readme.md (1 hit)
	Line 1365:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.ServiceBus\namespaces\deploy.bicep (1 hit)
	Line 344:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.SignalRService\webPubSub\deploy.bicep (1 hit)
	Line 132:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Sql\servers\deploy.bicep (1 hit)
	Line 186:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Sql\servers\readme.md (2 hits)
	Line 448:         privateDnsZoneGroup: {
	Line 652:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Storage\storageAccounts\deploy.bicep (1 hit)
	Line 289:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Synapse\privateLinkHubs\deploy.bicep (1 hit)
	Line  84:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Synapse\privateLinkHubs\readme.md (1 hit)
	Line 299:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Synapse\workspaces\deploy.bicep (1 hit)
	Line 283:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Synapse\workspaces\readme.md (1 hit)
	Line 605:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Web\sites\deploy.bicep (1 hit)
	Line 272:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Web\sites\readme.md (2 hits)
	Line 563:         privateDnsZoneGroup: {
	Line 830:         privateDnsZoneGroup: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Web\staticSites\deploy.bicep (1 hit)
	Line 153:     privateDnsZoneGroup: contains(privateEndpoint, 'privateDnsZoneGroup') ? privateEndpoint.privateDnsZoneGroup : {}
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Web\staticSites\readme.md (1 hit)
	Line 348:         privateDnsZoneGroup: {
Search "privateDnsZoneGroups" (112 hits in 35 files of 1108 searched)
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.AppConfiguration\configurationStores\readme.md (3 hits)
	Line  23: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 248:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Automation\automationAccounts\.test\parameters.json (2 hits)
	Line 158:                     "privateDnsZoneGroups": {
	Line 167:                     "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Automation\automationAccounts\readme.md (7 hits)
	Line  28: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 183:         privateDnsZoneGroups: {
	Line 514:         privateDnsZoneGroups: {
	Line 523:         privateDnsZoneGroups: {
	Line 723:           "privateDnsZoneGroups": {
	Line 732:           "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Batch\batchAccounts\readme.md (3 hits)
	Line  20: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 194:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Cache\redis\readme.md (3 hits)
	Line  22: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 286:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.CognitiveServices\accounts\readme.md (3 hits)
	Line  23: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 125:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.ContainerRegistry\registries\readme.md (3 hits)
	Line  24: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 226:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.DataFactory\factories\.test\parameters.json (1 hit)
	Line  88:                     "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.DataFactory\factories\readme.md (5 hits)
	Line  23: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 256:         privateDnsZoneGroups: {
	Line 446:         privateDnsZoneGroups: {
	Line 555:           "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.EventGrid\topics\readme.md (3 hits)
	Line  22: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 107:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.EventHub\namespaces\.test\parameters.json (1 hit)
	Line  98:                     "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.EventHub\namespaces\.test\pe.parameters.json (1 hit)
	Line 13:                     "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.EventHub\namespaces\readme.md (7 hits)
	Line  28: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 118:         privateDnsZoneGroups: {
	Line 438:         privateDnsZoneGroups: {
	Line 589:           "privateDnsZoneGroups": {
	Line 637:         privateDnsZoneGroups: {
	Line 668:           "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Insights\privateLinkScopes\readme.md (3 hits)
	Line  22: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 157:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.KeyVault\vaults\readme.md (3 hits)
	Line  25: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 349:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.MachineLearningServices\workspaces\readme.md (3 hits)
	Line  23: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 335:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Network\privateEndpoints\deploy.bicep (1 hit)
	Line  78: module privateEndpoint_privateDnsZoneGroup 'privateDnsZoneGroups/deploy.bicep' = if (!empty(privateDnsZoneGroup)) {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Network\privateEndpoints\privateDnsZoneGroups\deploy.bicep (1 hit)
	Line 38: resource privateDnsZoneGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2021-08-01' = {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Network\privateEndpoints\privateDnsZoneGroups\readme.md (3 hits)
	Line  1: # Network Private Endpoint Private DNS Zone Group `[Microsoft.Network/privateEndpoints/privateDnsZoneGroups]`
	Line 16: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Network\privateEndpoints\readme.md (2 hits)
	Line  20: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.RecoveryServices\vaults\readme.md (3 hits)
	Line   21: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line  863:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.ServiceBus\namespaces\.test\parameters.json (1 hit)
	Line 166:                     "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.ServiceBus\namespaces\.test\pe.parameters.json (1 hit)
	Line 16:                     "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.ServiceBus\namespaces\readme.md (7 hits)
	Line  21: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 187:         privateDnsZoneGroups: {
	Line 448:         privateDnsZoneGroups: {
	Line 629:           "privateDnsZoneGroups": {
	Line 749:         privateDnsZoneGroups: {
	Line 783:           "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.SignalRService\webPubSub\.test\parameters.json (1 hit)
	Line 79:           "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.SignalRService\webPubSub\.test\pe.parameters.json (1 hit)
	Line 16:           "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.SignalRService\webPubSub\readme.md (7 hits)
	Line  20: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 106:         privateDnsZoneGroups: {
	Line 442:         privateDnsZoneGroups: {
	Line 531:           "privateDnsZoneGroups": {
	Line 589:         privateDnsZoneGroups: {
	Line 623:           "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Sql\servers\readme.md (3 hits)
	Line  21: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 291:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Storage\storageAccounts\.test\encr.parameters.json (1 hit)
	Line 49:                     "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Storage\storageAccounts\.test\parameters.json (4 hits)
	Line  25:                     "privateDnsZoneGroups": {
	Line  34:                     "privateDnsZoneGroups": {
	Line  43:                     "privateDnsZoneGroups": {
	Line  52:                     "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Storage\storageAccounts\readme.md (13 hits)
	Line   22: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line  294:         privateDnsZoneGroups: {
	Line  411:         privateDnsZoneGroups: {
	Line  472:           "privateDnsZoneGroups": {
	Line  764:         privateDnsZoneGroups: {
	Line  773:         privateDnsZoneGroups: {
	Line  782:         privateDnsZoneGroups: {
	Line  791:         privateDnsZoneGroups: {
	Line  970:           "privateDnsZoneGroups": {
	Line  979:           "privateDnsZoneGroups": {
	Line  988:           "privateDnsZoneGroups": {
	Line  997:           "privateDnsZoneGroups": {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Synapse\privateLinkHubs\readme.md (3 hits)
	Line  20: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line  96:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Synapse\workspaces\readme.md (3 hits)
	Line  22: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 127:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Web\sites\readme.md (3 hits)
	Line  21: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 229:         privateDnsZoneGroups: {
  C:\data\git\temp\RABBIT_AZURE_TEMPLATES\bicep\modules\Microsoft.Web\staticSites\readme.md (3 hits)
	Line  20: | `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` | [2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints/privateDnsZoneGroups) |
	Line 108:         privateDnsZoneGroups: {

**Comment by milescattini** [comment]
Hey @Robbertbbb, 

My $0.02 is it depends on the context, you could be refering to one group, or more than one. 

-  The API endpoint uses a plural because it manages more than 1 private DnsZoneGroups - that is, its the endpoint that manages all prvate DNS Zone Groups.  
- Many of your listed examples are a variaton of  `privateEndpoint.privateDnsZoneGroup` or `contains(privateEndpoint, 'privateDnsZoneGroup') `, this is singular as its refering to the property of a privateEndpoint.

Its a little ideological - I'm not 100%, but can a private endpoint belong to more than 1 private dns zone group? I could imagine some scenarios where you have moer than one hub (say multi region/HA networking) where theoritically you would want . If this is the case then you'd need to consider updating all those individual references (i.e  `privateEndpoint.privateDnsZoneGroup`) to handle 1 or more groups

**Comment by Robbertbbb** [comment]
Hey @milescattini 

Thank you for your quick and full answers. 👍 
Using single or plural is either fine.
But the only thing is the example parameter files for the storage account uses plural and the private endpoint module expecting single.
It took me half a day to find out that parameter files example file incorrect.

**Comment by eriqua** [comment]
@milescattini @Robbertbbb since _Adding multiple DNS zone groups to a single Private Endpoint is not supported_ (see note in https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns#private-dns-zone-group) the `privateDNSzone` parameter in the private endpoint module was updated, but old references in some of the parameter files were not. Due to missing validation on elements of parameter objects we didn't notice this bug. Thanks @Robbertbbb for raising this. PR #2137 by @rahalan should fix this issue.
