### ISSUE TITLE
[Feature Request]: Update Microsoft.Network/publicIPAddresses to new API versions

### ISSUE THREAD

**Issue by cjnova** [Azure/ResourceModules#2129]
### Description

Update API version  with no new or updated properties for:

- Microsoft.Authorization/locks
- Microsoft.Network/publicIPAddresses

**Comment by cjnova** [comment]
Assign to me

**Comment by ahmadabdalla** [comment]
@cjnova assigned :)

**Comment by ahmadabdalla** [comment]
@cjnova Is this something you're still keen on updating? Please let us know how we can support you. Thank you

**Comment by AlexanderSehr** [comment]
We likely updated the API version since the issue's creation. We briefly checked and there seem to be no major missing properties to be found. If you're missing anything anyhow, please let us know by opening a new issue.
