### ISSUE TITLE
[Bug Report]: Fix all failing pipelines before Release 0.8

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2139]
### Describe the bug

This issue is intended to keep track of failing module validation pipelines to be fixed before the next release:

- [x] #2140
- [x] #2142
- [x] #2160
- [x] #2163
- [x] #2166
- [x] #2168
- [x] #2169
- [x] #2182
- [x] #2197
- [x] #2209
- [x] #2210
- [x] #2216
- [x] #2221
- [x] #2222
- [x] #2233
- [x] #2234
- [x] #2277
- [x] #2278
- [x] #2279
- [x] #2373

### To reproduce

Rerun failing pipelines

**Comment by rahalan** [comment]
Ongoing topic until next release
