### ISSUE TITLE
[Feature Request]: Enable Publishing to always publish if no version was found in the target location

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#2153]
### Description

Currently, a module is only published if git detects code changes for a module when comparing with Head^-1.

This can lead to some undesired behavior if you set up CARML for the first time, directly in main, and run the pipelines without any module changes. If that's the case, you won't be able to publish unless you apply a workaround such as a modification of the `version.json` file.

To mitigate this behavior we could add some logic to the publishing to the dedicated target locations (i.e., ACR, Template Specs, Universal Packages) that not only checks for changes, but also if there is already a version in that target location. If there is none, the pipeline could then decide to publish even if there are no module changes.

**Comment by eriqua** [comment]
Also as a separate issue, but related to the last point above, we should restrict the comparison logic which triggers the publishing to ignore changes to readme and test files as those should not impact the module version.

**Comment by AlexanderSehr** [comment]
Linked to #2401 2401
