### ISSUE TITLE
[Modules] Create new `Microsoft.Purview/accounts` module

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#2185]
Create a new CARML module for the `Microsoft.Purview/accounts` resource type as per the [service documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.purview/accounts?pivots=deployment-language-bicep) and our [contribution guide](https://github.com/Azure/ResourceModules/wiki/Contribution%20guide).

**Comment by ahmadabdalla** [comment]
@tyconsulting Please assign yourself to this issue. For some reason it isn't working for me to do that :)
