### ISSUE TITLE
[Feature Request]: Investigate ContainerInstances ContainerGroups required parameters

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2205]
### Description

The ContainerInstances ContainerGroups min test is using the `IPAddressPorts` parameter, although that is an optional parameter. min tests should only include required parameters. 

Investigate if IPAddressPorts is Optional or Required. Remove it from the min test in the former case, update the parameter description to Required otherwise. In either case update the module readme file.

> Note: The discussion started in PR #1874

**Comment by JPEasier** [comment]
@eriqua I will set the prameter to Required.
see deployment error:
````json
{
    "status": "Failed",
    "error": {
        "code": "MissingIpAddressPorts",
        "message": "The ports in the 'ipAddress' of container group 'jpecicgmin001' cannot be empty."
    }
}
````
