### ISSUE TITLE
[Feature Request]: Upgrade actions to use Node.js 16 warning - upgrade checkout action to v3

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2215]
### Description

GitHub actions recently started to throw the following warning

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
```

Ref: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Upgrade all references of actions/checkout in github workflows to use actions/checkout@v3

Ref: https://github.com/actions/checkout#checkout-v3

**Comment by ahmadabdalla** [comment]
@eriqua The `actions/checkout@v3` is good to go. However we cannot fully resolve this issue until the `azure/powershell@v1` action is also updated, which is still pending: See https://github.com/Azure/powershell/issues/58 where its being tracked.

![image](https://user-images.githubusercontent.com/28486158/197430544-18947645-c8bb-4ac2-9ce1-c7698fb783bd.png)

![image](https://user-images.githubusercontent.com/28486158/197430623-0bcb8b06-b2ab-4e0f-a657-d494950c2359.png)

We can create another ticket for the PowerShell update and mark it as blocked until its gets resolved by the action maintainer
