### ISSUE TITLE
[Feature Request]: Update the Private Endpoint Module API Version, Allowing Custom Name for the PE NIC

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#2219]
### Description

Currently we're using the following version for the Private Endpoints Module

<html>
<body>

Microsoft.Network/privateEndpoints | 2021-08-01
-- | --

</body>
</html>Microsoft.Network/privateEndpoints	[2021-08-01](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Network/2021-08-01/privateEndpoints)

We need to update to the latest version `2022-05-01` based on the documentation: https://learn.microsoft.com/en-us/azure/templates/microsoft.network/privateendpoints?pivots=deployment-language-arm-template

The new version supports enabling custom NIC name for the private endpoint, which removes the GUID that gets appended to the PE NIC name:

```json
"customNetworkInterfaceName": "string",
```

<html>
<body>

customNetworkInterfaceName | The custom name of the network interface attached to the private endpoint.
-- | --

</body>
</html>

**Comment by eriqua** [comment]
I'd suggest to wait for issue #1791 to 
- implement this change just once on all the modules supporting PE and 
- avoid merge conflicts on the open PRs

**Comment by ahmadabdalla** [comment]
Agreed. Thanks @eriqua

**Comment by rahalan** [comment]
should be included into release 0.8
