### ISSUE TITLE
[Feature Request]: Align CosmosDB deployment validation to other modules

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2231]
### Description

Related to issue #1564 
Discussion started in PR #1993 

Cosmos DB has 4 tests:

- 1 for a plain resource, where only the parent resource type is deployed together with diagnostic settings, locks and rbac
- 3 additional tests, testing each a different child resource: mongodb, gremlindb and sqldb

This seems a bit inconsistent with the majority of the other modules. The most consistent approach would be to have:

- a min test: similar to plain, but removing diagnostics, locks and rbac, hence testing only required parameters
- a common test: deploying gremlindb, sqldb and mongodb child resources together with additional features like locks, diagnostics and rbac. 
   > **Note**: That however depends on if the CosmosDB service allowes multiple types deployed at once

**Comment by AlexanderSehr** [comment]
Closing as with the AVM specs we defined since that a module must have a defaults & waf-aligned test - and may have any amount of additional scenario-specific test cases (including a max/common test)
