### ISSUE TITLE
[Feature Request]: Align DBforPostgreSQL flexibleServers deployment validation to other modules

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2232]
### Description

Related to issue #1564 and #1987
Discussion started in PR #1877 

DBforPostgreSQL flexibleServers  has 2 tests in addition to min, testing each very similar parameter sets. Discuss if valuable to keep public and private tests separated or if merge private and public tests into a more general common test, validating the majority of parameter inputs.

**Comment by AlexanderSehr** [comment]
Closing as we opted to leave the decision to the module owners
