### ISSUE TITLE
Fix DBForPostgresSQL pipeline

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2234]
Deployment validation failing for 2/3 module tests:

Private is failing due to
```
'Failed'.",     "details": [       {         "code":
       | "PrivateDnsZoneHasWrongZoneSuffix",         "message": "The
       | Private DNS Zone name provided is not valid. It has to end
       | with .postgres.database.azure.com."       }     ]
```

Public is failing due to generic conflict.

**Comment by MrMCake** [comment]
It appears this is a special case for this resource provider. When comparing the [parameter files](https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/dependencies/Microsoft.Network/privateDnsZones/parameters/postgres.parameters.json) it becomes relatively apparant ...
