### ISSUE TITLE
[Bug Report]: `Test-NamePrefixAvailability` not compatible with new dependencies approach

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#2242]
### Describe the bug

The script [Test-NamePrefixAvailability](https://github.com/Azure/ResourceModules/blob/main/utilities/tools/Test-NamePrefixAvailability.ps1) relies on the original JSON-Parameter files to find all names that must be unique and hence validated.

As we moved away from the JSON-Parameter files in favor of Bicep-Template files, we should also update this logic or remove its reference from the wiki as it will produce misleading results.

### To reproduce

Run the `Test-NamePrefixAvailability` function with for example a used storage account name.

**Comment by rahalan** [comment]
1.) add a note in utility docs
2.) fix it
