### ISSUE TITLE
Add Public Bicep Registery to Publish Action/Pipeline

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#225]
Add support for the '**public** bicep registry' to the publish actions (GitHub) and pipeline (Azure DevOps) to enable the modules consumption by other bicep resources

**Comment by MrMCake** [comment]
Pushed back until the public bicep registry is actually released

**Comment by MrMCake** [comment]
@rahalan I think this can be closed now as we know now that it's going to be a manual process.
