### ISSUE TITLE
Synapse Intial Workspace Admin not added 

### ISSUE THREAD

**Issue by ThorstenGH** [Azure/ResourceModules#2267]
### Describe the bug

Hi all,

 would like to add an AAD group to the Synapse workspace admin group with this template: modules\Microsoft.Synapse\workspaces\deploy.bicep

![image](https://user-images.githubusercontent.com/53176141/199682487-0d624e86-4967-4984-98bd-c40fc7af4d23.png)

My understanding is that the _initialWorkspaceAdminObjectID_ property should be the parameter to pass to achieve this Synapse RBAC assignment. However, when I try to do it, it does not do anything, only the service principal that runs the deployment is added (by default).   
(There is also no error message)

**code sample:**

```
param initialWorkspaceAdminObjectID string = <Object ID of an AAD Group or User>

module synapse  '../carml/Microsoft.Synapse/workspaces/deploy.bicep' = {
  name: synapseName
  params: {
    (...)
    initialWorkspaceAdminObjectID: initialWorkspaceAdminObjectID
  }
}
```

To me it seems that the underlying property "cspWorkspaceAdminProperties" of the Synapse provider does not work as intended.

```
resource workspace 'Microsoft.Synapse/workspaces@2021-06-01' = {
	(...)
  properties: {
    azureADOnlyAuthentication: azureADOnlyAuthentication ? azureADOnlyAuthentication : null
    cspWorkspaceAdminProperties: !empty(initialWorkspaceAdminObjectID) ? {
      initialWorkspaceAdminObjectId: initialWorkspaceAdminObjectID
    } : null
```

See also this related discussion:
 https://stackoverflow.com/questions/72289140/there-is-a-way-to-set-up-synapse-administrators-with-a-bicep-module 

### To reproduce

```
param initialWorkspaceAdminObjectID string = <Object ID of an AAD Group or User>

module synapse  '../carml/Microsoft.Synapse/workspaces/deploy.bicep' = {
  name: synapseName
  params: {
    (...)
    initialWorkspaceAdminObjectID: initialWorkspaceAdminObjectID
  }
}
```

**Comment by AlexanderSehr** [comment]
As per an internal discussion, this capability is currently not supported by the resource provider itself. Setting the Admin is a data-plane operation that would need to be exposed first.

There is a REST API call available which one could use via e.g. a deploymentScript to achieve this action regardless - but I'd considers this a workaround rather than a satisfying solution.

Will close this issue for now as there is not much we can do :/

**Comment by ThorstenGH** [comment]
Thank you Alexander for the investigation!

I think we will go with the az synapse command in a post deployment script as a workaround for now as mentioned in this article:

https://stackoverflow.com/questions/72289140/there-is-a-way-to-set-up-synapse-administrators-with-a-bicep-module
