### ISSUE TITLE
Improve modules to provide a combination of `contains()` and `empty()` checks on input parameter object elements

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2268]
### Discussed in https://github.com/Azure/ResourceModules/discussions/2214

<div type='discussions-op-text'>

<sup>Originally posted by **maxime-roy** October 13, 2022</sup>
Hi! 

I have a quick question for you, is there a particular reason the `contains()` function is used in the `Microsoft.Network/VirtualNetwork` module? With the current implementation, the module doesn't allow us to feed an empty string for a subnet property (like a NSG or a RT id ). This scenario could be useful where we send an array of subnet configuration to the module where not all subnets have a NSG, a route table or a NAT gateway linked to them.

It's something that I could submit a fix for, but I want to know if there was a particular reason it was done this way before working on it :) !

Here's an example for what the module prevents us to do: 

```
module virtualNetworkModule './modules/Microsoft.Network/virtualNetworks/deploy.bicep' = {
  name: 'deploy-virtualnetwork-${uniqueString(resourceGroup().name)}'
  scope: resourceGroup(networkResourceGroupName)
  params: {
    name: virtualNetworkName
    location: networkResourceGroupLocation
    lock: ''
    addressPrefixes: virtualNetworkAddressPrefixes
    subnets: [for subnet in virtualNetworkSubnets: {
      name: subnet.name
      addressPrefix: subnet.addressPrefix
      networkSecurityGroupId: (empty(subnet.networkSecurityGroupName) ?  '' : resourceId(resourceGroup().name, 'Microsoft.Network/networkSecurityGroups' , subnet.networkSecurityGroupName))
      routeTableId: (empty(subnet.routeTableName) ? '' : resourceId(resourceGroup().name, 'Microsoft.Network/routeTables' , subnet.routeTableName))
      serviceEndpoints: subnet.serviceEndpoints
      delegations: subnet.delegations
      privateEndpointNetworkPolicies: subnet.privateEndpointNetworkPolicies
      privateLinkServiceNetworkPolicies: subnet.privateLinkServiceNetworkPolicies
    }]
    tags: virtualNetworkTags
  }
  dependsOn: [
    networkSecurityGroupModule
    routeTableModule
  ]
}
```

Thank you! </div>

**Comment by eriqua** [comment]
Besides the discussion started as a feature request for the Vnet module, for consistency that would make sense to be implemented for all input parameter objects throughout the library.

**Comment by eriqua** [comment]
Current implementation checks if the input object contains the property. Example:
```
networkSecurityGroup: contains(subnet, 'networkSecurityGroupId') ? {
          'id': subnet.networkSecurityGroupId
        } : null
```

Proposed improvement checks both if the input object contains the property and if the property value is not empty. Example:
```
networkSecurityGroup: contains(subnet, 'networkSecurityGroupId') && !empty(subnet.networkSecurityGroupId) ? {
          'id': subnet.networkSecurityGroupId
        } : null
```

**Comment by rahalan** [comment]
The team is not sure, if idempotency is always possible with all different resource types. Needs further investigation. @AlexanderSehr , can you do some tests (starting with the vnet)? Thanks!

**Comment by maxime-roy** [comment]
@eriqua , @rahalan , @AlexanderSehr Thanks for looking into this! If you need more information or want to discuss about this, don't hesitate to contact me! I'll be glad to help you.

**Comment by AlexanderSehr** [comment]
Just also commented on the discussion. Fundamentally, the proposal makes sense to me - but I see a potential for errors when it commes to the default value, that is, the one to use if 
- a property was not provided OR
- it was provided, but is empty.

I could imaging that simply using `null` can lead to a "I don't do anything" behavior, which is definitely not what you want if you want to e.g. nullify a property and cannot set it to empty anymore.

**Comment by rahalan** [comment]
Needs to be tested: how the module will react (try with the Vnet). Check with the new implementation, if making it empty get rid of the object that was set before.

**Comment by ThojoUno** [comment]
Are there any examples of how people implement this module? It doesn't seem practical to hard-code the nsg resource id in the parameter file, and haven't found a way to dynamically generate properties in the bicep template. AzureBastionSubnet, GatewaySubnet, and AzureFirewallSubnet all break this code. thank you!

**Comment by AlexanderSehr** [comment]
We should test if this could be resolved with user-defined-types and their ability to specify something as 'optional'.

**Comment by ThojoUno** [comment]
It's for this reason, I haven't used the virtualNetwork module yet. I'm looking at lambda functions as the savior, but nothing to post yet regarding a solution.

**Comment by AlexanderSehr** [comment]
> Are there any examples of how people implement this module? It doesn't seem practical to hard-code the nsg resource id in the parameter file, and haven't found a way to dynamically generate properties in the bicep template. AzureBastionSubnet, GatewaySubnet, and AzureFirewallSubnet all break this code. thank you!

There are examples like the 'simple' deployment I did for a [Self-Hosted Agent solution](https://github.com/Azure/DevOps-Self-Hosted/blob/main/constructs/azureDevOpsScaleSet/templates/scaleset.deploy.bicep#L88-L121). Based on what you said @ThojoUno I strongly suspect you are refering to something a bit more elaborate than that ;)

Could you provide me with an example of what you'd like to achieve when you're referring to 'dynamically generating properties'?

Is it like you get an array of subnets from somewhere and would like to filter them / add / remove properties, etc. and then pass them into the module?

**Comment by AlexanderSehr** [comment]
With AVM, this responsibility was delegated to the module owners. Will archive this for now, but may be covered by spec in the future.
