### ISSUE TITLE
[Bug Report]: deploying vnet getting - AggregateTypeValidation / TemplateViolation

### ISSUE THREAD

**Issue by theMichaelB** [Azure/ResourceModules#2288]
### Describe the bug

Getting started using Resource Modules, trying to create a vnet using the [min](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.Network/virtualNetworks/.test/min) configuration. 
getting the error - 

`{"code": "InvalidTemplate", "target": "/subscriptions/b69f2302-5e6b-4d23-97f6-622c9d99a762/resourceGroups/ms.network.virtualnetworks-learn-rg/providers/Microsoft.Resources/deployments/pd4iykfzvvxku-test-learn", "message": "Deployment template validation failed: 'Template language version must be specified in order to use feature 'AggregateTypeValidation'.'.", "additionalInfo": [{"type": "TemplateViolation", "info": {"lineNumber": 0, "linePosition": 0, "path": ""}}]}`

using az bicep - 
```
ubuntu@DevBox:/data/lz-kube$ az bicep version
Bicep CLI version 0.12.1 (e43d137c2d)
```

This appears to be caused by this [issue](https://github.com/Azure/bicep/discussions/8878) in Bicep

### To reproduce

using the bison template [file](https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Network/virtualNetworks/.test/min/deploy.test.bicep) with `<<namePrefix>>` replaced. 

deploy using - 
`az deployment sub create -l uksouth -f main.bicep -n main0026`

### Relevant log output

```Shell
`{"code": "InvalidTemplate", "target": "/subscriptions/b69f2302-5e6b-4d23-97f6-622c9d99a762/resourceGroups/ms.network.virtualnetworks-learn-rg/providers/Microsoft.Resources/deployments/pd4iykfzvvxku-test-learn", "message": "Deployment template validation failed: 'Template language version must be specified in order to use feature 'AggregateTypeValidation'.'.", "additionalInfo": [{"type": "TemplateViolation", "info": {"lineNumber": 0, "linePosition": 0, "path": ""}}]}`
```

**Comment by theMichaelB** [comment]
This is my first run at using ResourceModules - I may be doing something stupid!

**Comment by AlexanderSehr** [comment]
By the way, you can see the unforunate effect in our pipeline overview: 
![image](https://user-images.githubusercontent.com/5365358/200399148-2cf91054-5b88-4bdb-8177-892314364641.png)

which is also still struggling with the second introduced Bicep bug: https://github.com/Azure/bicep/issues/8890

**Comment by AlexanderSehr** [comment]
Another note: To test deploy, I recommend using the script `utilities\tools\Test-ModuleLocally.ps1` as it automatically replaces tokens for you. You just have to setup you first invocation once. For example like this:

```PowerShell
# #########[ Function Test-ModulesLocally.ps1 ]#############
. 'C:\dev\ip\Azure-ResourceModules\ResourceModules\utilities\tools\Test-ModuleLocally.ps1'

$TestModuleLocallyInput = @{
    TemplateFilePath           = 'C:\dev\ip\Azure-ResourceModules\ResourceModules\modules\Microsoft.RecoveryServices\vaults\deploy.bicep'
    ModuleTestFilePath         = 'C:\dev\ip\Azure-ResourceModules\ResourceModules\modules\Microsoft.RecoveryServices\vaults\.test\common\deploy.test.bicep'
    PesterTest                 = $false
    ValidationTest             = $false
    DeploymentTest             = $true
    ValidateOrDeployParameters = @{
        Location          = 'westeurope'
        ResourceGroupName = 'validation-rg'
        SubscriptionId    = '11111111-1111-1111-1111-111111111111'
        ManagementGroupId = '11111111-1111-1111-1111-111111111111'
        RemoveDeployment  = $false
    }
    AdditionalTokens           = @{
        deploymentSpId = '11111111-1111-1111-1111-111111111111'
        tenantId       = '11111111-1111-1111-1111-111111111111'
        namePrefix     = 'randm'
    }
}
Test-ModuleLocally @TestModuleLocallyInput

```

**Comment by AlexanderSehr** [comment]
Alright, the latest release is out an the issue seems to be gone. @theMichaelB, please update and test again. I'll close the issue now :)
