### ISSUE TITLE
Missing kind property for Microsoft Web Site Module

### ISSUE THREAD

**Issue by stefanstranger** [Azure/ResourceModules#2304]
### Describe the bug

For the deployment of a Standard Logic App I need to use the Microsoft Web Site resource and configure the following kind properties.

![image](https://user-images.githubusercontent.com/2125385/200867462-7c54f2bb-4ec7-4296-bc20-cda6205a577b.png)

### To reproduce

use the CARM Module Microsoft Web Sites and try to set a kind property of 'functionapp, workflowapp'

**Comment by AlexanderSehr** [comment]
If you want to fix it in your local instance, you'd need to navigate to the Module's code, and adjust the [allowed values](https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Web/sites/deploy.bicep). Note however, as you're referencing the value from a container registry, the template must be published there too.I checked yesterday - and it's a lot more difficult to find out the full list of allowed values than you'd think. Which is probably also the reason not even the Bicep-Extension proposes you any values. Confused

**Comment by AlexanderSehr** [comment]
Note, this must be fixed both in the parent, as well as the child-resources.
