### ISSUE TITLE
[Feature Request]: Databricks module needs to have more granular parameters

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#2309]
### Description

Currently the Databricks module is using a parameter called workspaceParameters that is storing all available parameters in one complex object. It would be better to split it to each parameter. That would improve input parameter validation and also consistency with other modules. List of parameters: https://learn.microsoft.com/en-us/azure/templates/Microsoft.Databricks/2018-04-01/workspaces?pivots=deployment-language-bicep#workspacecustomparameters

**Comment by AlexanderSehr** [comment]
Aside from changing the object to the invididual parameters, we should also incoporate them into the tests and deploy for example a custom VNET which we then link, etc.
