### ISSUE TITLE
[Feature Request]: Implement Data Lake GEN2 functionality in Storage

### ISSUE THREAD

**Issue by annduda** [Azure/ResourceModules#2331]
### Description

Enable Data Lake Gen2 in Storage module (Premium, block blobs):
![image](https://user-images.githubusercontent.com/95341017/201689838-c326d54f-01b2-43a4-85d3-2f14d95deb3a.png)
https://learn.microsoft.com/en-us/azure/storage/blobs/create-data-lake-storage-account

**Comment by AlexanderSehr** [comment]
It appears we have to set a certain property with a certain SKU to enable DataLakeGen2. So we need to find out, what this property is, and then add/update it, if it is not existing.

**Comment by annduda** [comment]
Thanks Alex!
