### ISSUE TITLE
[Feature Request]: Update hardcoded value in web sites module

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2335]
### Description

Link to secret [here](https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Web/sites/.test/FunctionAppCommon/deploy.test.bicep#L67) is referring to a dependency resource in the validation-rg, deployed by the old dependencies pipeline approach. Validation-rg and related hosted resources will be deleted before release 0.8.

This issue is about:
- Moving the secret to a centrally managed kv in our test environment
- Updating the reference to the new url and adding a comment in the test to warn users to update the value in their own test environment

Updating the wiki to reference this additional manual step before running pipelines in the getting started section will be covered by issue #2291 and its related PR #2297

**Comment by AlexanderSehr** [comment]
Also includes updating the Getting Started Guide to intruct to create the manual dependency in the Key Vault
