### ISSUE TITLE
[Feature Request]: support for SFTP in Azure Storage

### ISSUE THREAD

**Issue by zydio** [Azure/ResourceModules#2378]
### Description

One month ago [SFTP support in Azure Storage went GA](https://learn.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-support).

There is an official [code sample](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.storage/storage-sftp/main.bicep) showing the use of the new `isSftpEnabled` property and related ones + the creation/authorization of SFTP user accounts.

CARML modules in the `Microsoft.Storage/storageAccounts` path currently lack this feature (checked in all branches).

**Comment by karthikvenkat17** [comment]
Fixed with PR # 2378
