### ISSUE TITLE
Outputs are missing @description

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#238]
In the json files, all outputs had the metadata to include a description. Although bicep supports that with the @description tag, the decompiler ignored that. We will need to add them again plus update the readme accordingly. This can probably done in a scripted way

**Comment by eriqua** [comment]
**Note**: After updating templates also corresponding readme files should be regenerated to include the description

**Comment by MrMCake** [comment]
Regex

> ^(?!@).*
> output
