### ISSUE TITLE
Modules: align locks to be applied on all deployed resources based on what specified at the parent resource level

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#239]

**Comment by MariusStorhaug** [comment]
Child resources automatically inherit the lock of the parent. Do we mean child resources or dependant resources, i.e public IP of a VM if we lock the VM?

**Comment by MrMCake** [comment]
In my opinion locks should only be applied to the resources that you deploy explicity, i.e. in case of VM also the Nic & IP. However, it should not be passed down to children by us, as the lock can be defined in the parameter file for those anyways

**Comment by eriqua** [comment]
@MrMCake @MariusStorhaug @rahalan can this issue be closed? I see that is the current implementation for e.g. vms and storage accounts

**Comment by rahalan** [comment]
@eriqua in that case, I guess yes
