### ISSUE TITLE
Discuss the need of a variables section in test templates

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2397]
Should dependencies resource names be defined in a variables section or directly in the resource section? Adding variables would lead to a bigger file but would avoid duplication in case multiple occurrences of the same name are needed

Suggestion is: Variables should be avoided in test files (dependencies.bicep and deploy.test.bicep) unless their value is required in multiple places. 
Further discussion is needed for the whole team to agree.

If agreed upon, this issue is about providing corresponding guidelines in the contribution guide wiki section.

**Comment by rahalan** [comment]
- [ ] create a disclaimer how to use test files (they should not be considered as solutions, but actual test files)
- [ ] variables should only used where really necessary (limit the usage as much as possible)
