### ISSUE TITLE
Merge AppService & WebApp modules under `Microsoft.Web/sites`

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#24]
Both modules have almost the same content with one major difference:
- The AppService module deploys a serverfarm (appServicePlan) directly and references its ID in the subsequent site deployment
- The WebApp module deploys no serverfarm but only requires you to provide its ID in the site deployment

Ideally we merge both together and provide an experience where the ID can be provided as an optional parameter. If provided it is used, if it is not provided, but a name for an AppServicePlan is, an AppServicePlan is deployed and its ID used

**Comment by segraef** [comment]
@MrMCake done?

**Comment by MrMCake** [comment]
Code awaiting in Fork

**Comment by MrMCake** [comment]
Done
