### ISSUE TITLE
Data Factory: Missing `ipConfigurations` for Private Endpoints

### ISSUE THREAD

**Issue by chris5287** [Azure/ResourceModules#2423]
The `Microsoft.DataFactory/factories` module uses the `Microsoft.Network/privateEndpoints` module internally to create private endpoints, but it fails to pass through the `ipConfigurations` property to allow static IP addresses to be specified :(

https://github.com/Azure/ResourceModules/blob/19c03e100c1cff02756a7cdcc3a3759ad4aee795/modules/Microsoft.DataFactory/factories/deploy.bicep#L267

**Comment by ChrisSidebotham** [comment]
I have validated this locally using the same behaviour with the Storage Accounts Module - Working on updating this for all modules using PE now
