### ISSUE TITLE
[PSRule] Integrate PSRule pre-flight checks with GH module validation workflows

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2426]
Together with PSRule validation checks on PRs and on schedule on the whole repo, checks should also be integrated with each module validation pipeline. 

This issue is about integrating checks with GH workflows, e.g., as a dedicated job running in parallel to the static validation and prior to the deployment validation.

A first implementation of this issue for, e.g., the KV module, is hosted by branch [hack/topic6](https://github.com/Azure/ResourceModules/tree/hack/topic6)

**Comment by eriqua** [comment]
Suggestion: apply the `needsfurtherdiscussion` label.

OPT1: implement the additional check on all PRs as non blocking
OPT2: implement the additional check on all PRs as blocking only after issue #2151 closure

**Comment by AlexanderSehr** [comment]
Question from #2453 : Should we move the `ps-rule.yaml` from root into `utilities/pipelines/staticValidation`.

@eriqua and myself discussed this already a little bit and the below notes are the short version:
- Root is the default, it is anyway possible to use specific configuration files from custom locations, but that would require to deviate from default and add options to all PSRule actions (now it's only the scheduled pipeline check, it will eventually be integrated also in module pipelines).
- Normally that is done for exceptions. So technically feasible but not sure if we should do it.

We should figure out the pros and cons and then come to conclusion. While I personally would like to keep `/` (root) as clean/empty as possible, I understand that the effort/added code involved to implement this may outwheigh the benefits.
