### ISSUE TITLE
Remove job - Removal step for resources not supporting tags (create custom scripts)

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#244]
The majority of resources are currently removed by applying a tag within the deployment step. 
This is not working for resources not supporting tags, which need to be managed differently.

**Comment by simonbMS** [comment]
List of resources that doesn't support tags:

- [ ] Microsoft.Authorization/policyAssignments
- [ ] Microsoft.Authorization/policyDefinition
- [ ] Microsoft.Authorization/policyExemptions
- [ ] Microsoft.Authorization/policySetDefinitions
- [ ] Microsoft.Authorization/roleAssignments
- [ ] Microsoft.Authorization/roleDefinitions
- [ ] Microsoft.Automanage/accounts
- [ ] Microsoft.Consumption/budgets
- [ ] Microsoft.Insights/diagnosticSettings
- [ ] Microsoft.ManagedServices/registrationDefinitions
- [ ] Microsoft.Management/managementGroups
- [ ] Microsoft.Security/azureSecurityCenter

**Comment by MrMCake** [comment]
As tags were retired we should create a new issue to tackle the remaining resources that still need custom scripts
