### ISSUE TITLE
[Feature Request]: azure firewall module support for Hub Deployment

### ISSUE THREAD

**Issue by GeraldGoldstein** [Azure/ResourceModules#2457]
### Description

having been using carml modules at customer site for some time now, the azure firewall module doesnt support deployment into a virtual wan hub, although the sku parameter is provided.

would be nice to have the azure firewall module updated to include stand-alone (VNet) deployment as well as Hub deployment. For now, have made my own module and using in place of the carml module.

**Comment by AlexanderSehr** [comment]
After an internal discussion, the idea is to keep both the managed & unmanaged firewall in one module but provide different test cases for e.g.:
- Firewall min
- Firewall common
- vWAN Firewall min
- vWAN Firewall common

This implementation will likely require a `union()` for the properties object (with its ups and downs)

**Comment by rahalan** [comment]
@fblix , the duplicate is closed as completed. Can we close this one? Thanks.
