### ISSUE TITLE
[Feature Request]: add module for Microsoft.Subscription/aliases@2021-10-01

### ISSUE THREAD

**Issue by GeraldGoldstein** [Azure/ResourceModules#2459]
### Description

module for deploying new subscirptions

**Comment by eriqua** [comment]
Hello @GeraldGoldstein, thanks for opining the issue. 

We currently have a blocker to continuously test this module in the validation environment. Please see issue #868 and related draft PR #1094. 

In the meantime, you can check if the implementation in branch https://github.com/Azure/ResourceModules/tree/users/alsehr/bicep_subscription/arm/Microsoft.Subscription/aliases is useful for you.

**Comment by rahalan** [comment]
Thanks for pointing out. Closed because of duplicate issue #868

**Comment by GeraldGoldstein** [comment]
thanks yes im using that code.
