### ISSUE TITLE
[Feature Request]: Remove `0.3.1` to `0.4.0` upgrade guidance wiki page

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2468]
### Description

Content in https://github.com/Azure/ResourceModules/wiki/Upgrade%20from%200.3.1%20to%200.4.0 may not be relevant anymore since we're in v0.8.0.
We should either clean it up or, maybe better, create an 'Archived' section where to place that and future outdated Wiki content.

**Comment by AlexanderSehr** [comment]
Following a discussion we opted to removed this page from the Wiki as it does not provide any more tangible value (especially as it only shows you how to upgrade to 0.4, while we're already at 0.9)
