### ISSUE TITLE
[Bug Report]: Problems adding an ip address into the network acl

### ISSUE THREAD

**Issue by gsuttie** [Azure/ResourceModules#2469]
### Describe the bug

If i try to add an ip address into the network acl part like so

networkAcls: {
        defaultAction: 'Deny'
        ipRules: [
          {
            value: 'xxx.xx.xxx.xx'
            action: 'Allow'
          }
        ]
      }

It doesn't work using the storage bicep file.

If I create my own then it works using:-

resource stor 'Microsoft.Storage/storageAccounts@2022-09-01' = {
  name: 'gregstoragetest'
  location: 'westeurope'
  sku: {
    name: 'Standard_ZRS'
  }
  kind: 'StorageV2'
  properties: {
    networkAcls: {
      defaultAction: 'Deny'
      ipRules: [
        {
          value: 'xxx.xx.xxx.xx'
          action: 'Allow'
        }
      ]
    }
  }
}

Outcome: Enabled from selected virtual networks and IP addresses - this should be ticked

### To reproduce

use the storage account bicep and try to create a new entry for an IP address to give it access so that :-

Outcome: Enabled from selected virtual networks and IP addresses - this should be ticked

### Code snippet

```Bicep
see above
```

**Comment by ChrisSidebotham** [comment]
Tested using the current version of the module with the following params:
```
targetScope = 'resourceGroup'

module storageAccount '../ResourceModules/modules/Microsoft.Storage/storageAccounts/deploy.bicep' = {
  name: 'storageDeploy'
  params: {
    name: 'cs2469issuetest'
    enableDefaultTelemetry: true
    allowBlobPublicAccess: false
    location: 'uksouth'
    storageAccountSku: 'Standard_LRS'
    storageAccountKind: 'StorageV2'
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Deny'
      ipRules: [
        {
          action: 'Allow'
          value: '1.1.1.1'
        }
        {
          action: 'Allow'
          value: '31.48.100.100'
        }
      ]
    }
  }
}
```
Deployment was successful as shown below

![image](https://user-images.githubusercontent.com/48600046/208418725-ef413cf7-99a5-4f2d-9539-f928aa628ab5.png)

Networking Details shown below 

![image](https://user-images.githubusercontent.com/48600046/208418507-ff1d5798-c154-46fe-89eb-33841324cdbb.png)

Are you able to provide further details to the error you have received?

**Comment by ChrisSidebotham** [comment]
@gsuttie - Are you able to provide the team further details for this error you have received?

**Comment by ChrisSidebotham** [comment]
@gsuttie - If there any other follow up required here? if not we will close this issue out over the coming week

**Comment by ChrisSidebotham** [comment]
Closing issue as tests incorporate IpAllowList
