### ISSUE TITLE
[Bug Report]: Update Microsoft.Web/sites API version

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2476]
### Describe the bug

Microsoft.Web/sites is failing on static validation due to outdated API versions for several child resources.

### To reproduce

Rerun Microsoft.Web/sites pipeline and verify the static validation logs

**Comment by ChrisSidebotham** [comment]
@krbar / @AlexanderSehr - Should this issue now be closed with the completion of #2526
