### ISSUE TITLE
[Feature Request]: Missing Event Grid subscription for Event Topics

### ISSUE THREAD

**Issue by samuelya** [Azure/ResourceModules#2479]
### Description

The event grid module allows you to create new event topics. However, there is no option to create an event subscription for Azure functions, web hocks, etc, As workaround, I updated the event grid topic module as follows

```bicep
@description('Topic subscriptions')
param topicSubscriptions array = []
```

```bicep
resource subscriptions 'Microsoft.EventGrid/eventSubscriptions@2022-06-15' = [for subscription in topicSubscriptions: {
  scope: topic
  name: subscription.name
  properties: subscription.properties
}]
```

**Comment by rahalan** [comment]
Great observation! We just need to make sure to add this as a child module, following CARML conventions.

**Comment by AlexanderSehr** [comment]
Just one comment from my side: As per the way CARML modules are written, the `eventSubscriptions` module itself shouldn't have an array to deploy n `eventSubscriptions` - but just one.

If you then want to deploy n `eventSubscriptions`, you should use a loop in the consuming deployment. The rationale here is, that many times (probably most) we deploy other resources alongside the main resource. And then it can become veeery tricky if you have to deal with an array of main resources. Like, for which element in the loop do I now deploy RBAC, if RBAC is specified, etc.

**Comment by ChrisSidebotham** [comment]
Just want to clarify on this currently the `Microsoft.EventGrid` modules support `systemTopics` which means we do actually need the child resource for `systemTopic/eventSubscriptions` .

The top level resource `eventSubscriptions` is for connecting to none systemTopics which is not currently supported as a CARML Module (We need work in this area)

**Comment by ChrisSidebotham** [comment]
Development started - Branch attached, will continue after festive break
