### ISSUE TITLE
[Bug Report]: Update backup resource type API version in VM module

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2482]
### Describe the bug

Microsoft.Compute/virtualMachines is failing on static validation due to outdated API versions for resource type [vaults/backupFabrics/protectionContainers/protectedItems]

### To reproduce

Rerun Microsoft.Compute/virtualMachines pipeline and verify the static validation logs

**Comment by ChrisSidebotham** [comment]
The issue here is tied to the Microsoft.RecoveryServices CARML Modules - Fix and PR applied to those modules user #2488 - Can we attach this to that PR and when complete I will add both Pipeline badges to the PR?
