### ISSUE TITLE
[Feature Request]: PS and Bicep Version check for Set-ModuleReadMe Script

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/ResourceModules#2483]
### Description

When working on code in the repository it is sometime hard to ensure all clients are running required versions. For example psversion 7.2 had some breaking changes so we now require version 7.3.1 we should add this to the script as a requirements check before any of the functions are processed. Here is a sample that we could build on to get this added:
```
# Check the version of PowerShell
$currentVersion = $PSVersionTable.PSVersion

# Compare the current version to the required version
if ($currentVersion -lt [version]"7.3.1") {
  # If the current version is lower than the required version, display an error message
  Write-Error "This script requires PowerShell version 7.3.1 or higher. Please upgrade to the latest version and try again."
} else {
  # If the current version is equal to or higher than the required version, run the script
  .\MyScript.ps1
}
```

**Comment by rahalan** [comment]
We should use the '#required' keyword to ensure correct PS version

**Comment by ChrisSidebotham** [comment]
Closing as linked to #2859
