### ISSUE TITLE
[Bug Report]: Correct incomplete resource removal

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#2486]
### Describe the bug

Since the migration to the new dependency approach, the removal seems to struggle with the LAWs deployed by the Diagnostic Tests. Often a Resource Group with just the LAW remains of the tests: 
![image](https://user-images.githubusercontent.com/5365358/208729730-f5a27cb0-6c8a-46f1-a321-383479311f7e.png)

### To reproduce

Run the tests

**Comment by AlexanderSehr** [comment]
Even with the new approach the issue is unfortunately not resolved an requires further investigation

**Comment by rahalan** [comment]
Issue is solved
