### ISSUE TITLE
[Feature Request]: Added support for publicNetworkAccess parameter in Microsoft.RecoveryServices/vaults module

### ISSUE THREAD

**Issue by juanandmsft** [Azure/ResourceModules#2495]
### Description

Added support for publicNetworkAccess parameter.
Enable or disable inbound network traffic from public clients using API 2022-09-30-preview.
https://github.com/Azure/ResourceModules/pull/2494

**Comment by ChrisSidebotham** [comment]
@juanandmsft - I see you also have PR in for this. Due to the requirement to fix static validation I have added this as part of a PR that is currently open as it is required for the new API Version. please see #2488
