### ISSUE TITLE
[Feature Request]: Extend VM module with Trusted Launch VM options

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2496]
### Description

Enable the VM module with [Trusted Launch VMs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fvirtual-machines%2Ftrusted-launch&data=05%7C01%7CErika.Gressi%40microsoft.com%7C461941fbbd27437f879808dae44df1b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638073320711139602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MRxjLn4erWtTlmCAGBsh9A%2BKDPrwMFg8g3E%2FFcpy0Hw%3D&reserved=0) configuration

- Allow [Generation-2](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fvirtual-machines%2Fgeneration-2&data=05%7C01%7CErika.Gressi%40microsoft.com%7C461941fbbd27437f879808dae44df1b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638073320711139602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y30uz5aRO3FRCs1ygegGrU4p9QKXlahFkXxqVZU3efA%3D&reserved=0) based [Trusted Launch VMs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fvirtual-machines%2Ftrusted-launch&data=05%7C01%7CErika.Gressi%40microsoft.com%7C461941fbbd27437f879808dae44df1b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638073320711139602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MRxjLn4erWtTlmCAGBsh9A%2BKDPrwMFg8g3E%2FFcpy0Hw%3D&reserved=0) or verify if all the related options are already configurable in the module
- Verify if the same can be done for the VMSS module
- Verify if in addition to extend the functionality, it makes sense to enable it by default. 
- Make sure the common tests deploy the functionality
- Update the API version if required by the feature

Additional details that may come useful

Feature Name | Description
-- | --
Secure Boot | Protects OS against the installation of malware-based rootkits and boot kits.
vTPM | It serves as a dedicated secure vault for keys and measurements, enabling attestation by measuring the entire boot chain of your VM
Guest VM Attestation | Guest attestation extension enables proactive attestation and monitoring the boot integrity of your VMs.

Trusted Launch VM security features allows customer to enable [Secured Core](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fgovernance%2Fpolicy%2Fsamples%2Fguest-configuration-baseline-windows%23secured-core&data=05%7C01%7CErika.Gressi%40microsoft.com%7C461941fbbd27437f879808dae44df1b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638073320711139602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JL1yQX%2F8OuY1XdGDE6vxxbxwU%2F9VO75XMRgviaHzj18%3D&reserved=0) settings of [Azure Compute Security Baseline](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fgovernance%2Fpolicy%2Fsamples%2Fguest-configuration-baseline-windows&data=05%7C01%7CErika.Gressi%40microsoft.com%7C461941fbbd27437f879808dae44df1b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638073320711139602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ob0l%2F%2F309qbPqC2KALYbz%2BTGrtwreO4TdrgTR0y8UwQ%3D&reserved=0)

Reference ARM template / Bicep file: [azure-quickstart-templates/quickstarts/microsoft.compute/vm-trustedlaunch-windows at master · Azure/azure-quickstart-templates (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-quickstart-templates%2Ftree%2Fmaster%2Fquickstarts%2Fmicrosoft.compute%2Fvm-trustedlaunch-windows&data=05%7C01%7CErika.Gressi%40microsoft.com%7C461941fbbd27437f879808dae44df1b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638073320711139602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xcrf5lUSDcit3QVSe8cdJv3RJ05V5LhjUBrb%2FRu9ypQ%3D&reserved=0)

**Comment by ChrisSidebotham** [comment]
Modules already allow for deployment of Trusted Launch VM & VMSS. Just need to change this to the default deployment method. @AlexanderSehr - Any reason the current tests may not like this?

**Comment by eriqua** [comment]
@ChrisSidebotham @AlexanderSehr @rahalan are we good to close this or should we port it to BRM? Are all the points listed Verified (including being tested by max/ being enabled by default)?

**Comment by eriqua** [comment]
@ChrisSidebotham I know 😄  
Hence the question: did we verify that all the points listed in the issue description are completed before closing?
