### ISSUE TITLE
Workflow job condition: skip removal if deployment does not run

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#250]
## Description

Skip removal job if deployment step does not run due to validation/unit test jobs failing.

Example of current behaviour
![image](https://user-images.githubusercontent.com/56914614/138426028-952e9ce1-6eb3-4014-be08-c09382ebee99.png)

**Comment by MrMCake** [comment]
Counterproposal: The removal stage should fail if the removal itself failed. However if it just cannot find a resource (because it was not deployed) the pipeline should probably be green.
The only thing to be careful with: Tags are not always found on ressource. So we may overlook a missing removal

**Comment by MrMCake** [comment]
This is done
