### ISSUE TITLE
[Bug Report]: Update Azure DevTest Lab Module to API Version '2018-10-15-preview' failing the Static tests

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#2518]
### Description

Current DevTest Lab Module is running on the latest published API version (2018-09-15). Both in the [Template Documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.devtestlab/2018-09-15/labs?pivots=deployment-language-bicep) and the [API Documentation](https://learn.microsoft.com/en-us/rest/api/dtl/labs). However, when attempting to update the module to the latest API version `2018-10-15-preview`. We have a couple of things that need to be fixed:

- Both the [Template Documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.devtestlab/2018-09-15/labs?pivots=deployment-language-bicep) and the [API Documentation](https://learn.microsoft.com/en-us/rest/api/dtl/labs) need to be updated to reference the latest published API version. 

- Bicep is also complaining about the API for not having types available. So it needs to reference the latest API as well.
```powershell
Warning BCP081: Resource type "Microsoft.DevTestLab/labs@2018-10-15-preview" does not have types available.
```

## Bug

- Our Static tests are failing for the latest API with the following message:
```powershell
[-] In [Microsoft.DevTestLab/labs] used resource type [labs] should use one of the recent API version(s). Currently using [2018-10-15-preview] 76ms (75ms|1ms)
   Expected '2018-10-15-preview' to be found in collection @('2018-09-15', '2016-05-15', '2015-05-21-preview'), but it was not found.
```

## Requirement

The API that is being used in the Azure Portal is `2018-10-15-preview`, which contains a lot more features than the latest published version `2018-09-15`. It includes the following:

- Support for system assigned managed identities.
- Use existing storage account for the Lab Artifacts instead of the default.
- Encryption using Customer managed keys using the Disk Encryption set.
- Browser Connect via Azure Bastion.
- Specifying a custom resource group for VM Creation.
- Isolation of lab resources. This changes the Storage accounts and key vaults to 'Selected networks only'
- Disabling auto upgrade of custom script extension.

![image](https://user-images.githubusercontent.com/28486158/210157763-732be055-bb9b-471b-8962-6cd742c08b81.png)
![image](https://user-images.githubusercontent.com/28486158/210157794-653903e9-6274-4c0f-87ad-c4deee72b720.png)
![image](https://user-images.githubusercontent.com/28486158/210157859-d1c227d1-2b75-411c-8780-2fae3320b447.png)

We need to update our module to support the above features.

**Comment by ahmadabdalla** [comment]
The API Specs List JSON, contains the `Microsoft.DevTestLab` resource provider, however it does not contain the latest API Version:

```json
    "Microsoft.DevTestLab": {
        "labs": [
            "2015-05-21-preview",
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/artifactsources": [
            "2015-05-21-preview",
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/costs": [
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/customimages": [
            "2015-05-21-preview",
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/formulas": [
            "2015-05-21-preview",
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/notificationchannels": [
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/policysets/policies": [
            "2015-05-21-preview",
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/schedules": [
            "2015-05-21-preview",
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/servicerunners": [
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/users": [
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/users/disks": [
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/users/environments": [
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/users/secrets": [
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/users/servicefabrics": [
            "2018-09-15"
        ],
        "labs/users/servicefabrics/schedules": [
            "2018-09-15"
        ],
        "labs/virtualmachines": [
            "2015-05-21-preview",
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/virtualmachines/schedules": [
            "2016-05-15",
            "2018-09-15"
        ],
        "labs/virtualnetworks": [
            "2015-05-21-preview",
            "2016-05-15",
            "2018-09-15"
        ],
        "schedules": [
            "2016-05-15",
            "2018-09-15"
        ]
    },
```

However, it does not contain the latest APIs. @AlexanderSehr .. Is the intent for us to 'manually' update this API specs file when we're adding new API versions? I can see the pipeline running weekly, but not sure on how it works, although I can see it referenced in our doco:

```markdown
In particular, each resource's API version is compared with those currently available on Azure. This test has a certain level of tolerance (does not enforce the latest version): the API version in use should be one of the 5 latest versions available (including preview versions) or one of the the 5 latest non-preview versions.

To test the API versions, the test leverages the file `utilities/src/apiSpecsList.json` file as a reference for all API versions available for any used Provider Namespace & Resource Type.

```

**Comment by AlexanderSehr** [comment]
> ever, it does not contain the latest APIs. @AlexanderSehr .. Is the intent for us to 'manually' update this API specs file when we're adding new API versions? I can se

Hey @ahmadabdalla, it is as you describe. The Api Specs file is created/updated weekly on a schedule and leverges the [APICrawlerModule](https://github.com/AlexanderSehr/AzureAPICrawler) to find and extract all API versions from the 'official' [Azure API specs](https://github.com/Azure/azure-rest-api-specs) GitHub repository and it does, in fact, not know this preview version.

Not sure what to do with it now. I also checked the `Get-AzResourceProvider -ListAvailable` function, it it does know the preview version:

```json
"ApiVersions": [
  "2018-10-15-preview",
  "2018-09-15",
  "2017-04-26-preview",
  "2016-05-15",
  "2015-05-21-preview"
]
```

We introduced the API crawler explicitely to get a more complete picture as `Get-AzResourceProvider` sometimes lacks years of API versions (e.g. for Resource Group, Tags, etc.). 

What I can try to do to mitigate this is to update the usage of the AzureAPICrawler module to essentially merge the results of both - what the API Specs repository returns, and what the `Get-AzResourceProvider` function returns. It's not something I'd have expected to happen.

This 'fix' would need to be implemented [here](https://github.com/Azure/ResourceModules/blob/main/utilities/tools/platform/Set-ApiSpecsFile.ps1) and ideally leverage the [original code](https://github.com/Azure/ResourceModules/blob/7ed7e76bb3764cf5a4fcdd3ad8ed2d43f8549705/utilities/pipelines/staticValidation/module.tests.ps1#L1200:~:text=%24ApiVersions%20%3D%20Get%2DAzResourceProvider%20%2DListAvailable).

I guess this should be handled in a dedicated bug?

**Comment by ahmadabdalla** [comment]
Thanks @AlexanderSehr. I've also raised an [issue - 22026](https://github.com/Azure/azure-rest-api-specs/issues/22026) in that repo regarding the missing API version for DevTest Labs. It should be in this [folder](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/devtestlabs/resource-manager/Microsoft.DevTestLab).

**Comment by ahmadabdalla** [comment]
@AlexanderSehr . The static tests are still failing due to some child resources not having the API versions published, including in the `Get-AzResourceProvider` response: 

![image](https://user-images.githubusercontent.com/28486158/210285015-bd85191d-d788-400c-82d2-e41e3ee53415.png)

Applicable to both `2018-09-15` version and the latest preview `2018-10-15-preview`. The only way to get around this is by downgrading all child resources in our module to the `2018-09-15` version as metadata from both the API specs doc and the external resource you implemented contains it all. I don't think there is much we can do right now as your script has the right logic in place, and the issues are happening elsewhere.

I would suggest keeping the child modules to the old API version but for the parent to use the latest `preview` version until the issue I raised gets resolved. Then we can uplift our module. Thoughts?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr . The static tests are still failing due to some child resources not having the API versions published, including in the `Get-AzResourceProvider` response:
> 
> ![image](https://user-images.githubusercontent.com/28486158/210285015-bd85191d-d788-400c-82d2-e41e3ee53415.png)
> 
> Applicable to both `2018-09-15` version and the latest preview `2018-10-15-preview`. The only way to get around this is by downgrading all child resources in our module to the `2018-09-15` version as metadata from both the API specs doc and the external resource you implemented contains it all. I don't think there is much we can do right now as your script has the right logic in place, and the issues are happening elsewhere.
> 
> I would suggest keeping the child modules to the old API version but for the parent to use the latest `preview` version until the issue I raised gets resolved. Then we can uplift our module. Thoughts?

Dang :-/ let's go with your suggestion, yes. Are we sure the children 'would' have the preview API version too? It happens that they diverge.

**Comment by ahmadabdalla** [comment]
@AlexanderSehr .. yep they do use the latest API as I've inspected the payloads when changing the configurations via the Azure portal using the developer tools browser method. It's unfortunate we have these issues. Also there are no feature uplifts on the child modules when using the latest API version so we're not missing out. The only one benefiting is the parent module.
