### ISSUE TITLE
Api Managment Service

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#253]
In the param clientId and clientSecret show as optional.

Line |
 205 |                          throw $PSitem.Exception.Message
     |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 15:32:34 - The deployment 'service-20211020T1410404512Z'
     | failed with error(s). Showing 1 out of 1 error(s). Status
     | Message: One or more fields contain incorrect values: (Code:
     | ValidationError)  - 'clientId' should not be empty.
     | (Code:ValidationError)  - 'clientSecret' should not be empty.
     | (Code:ValidationError)  - 'authority' must be between 1 and
     | 200 characters. You entered 0 characters.
     | (Code:ValidationError)   CorrelationId:
     | d11a63d3-da93-4645-9dbe-f58a71a72e2f

**Comment by rahalan** [comment]
@cacarroll  Will be fixed with https://github.com/Azure/ResourceModules/issues/338
