### ISSUE TITLE
[Bug Report]: Fix AVD ScalingPlans pipeline

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2536]
### Describe the bug

Static validation is failing for the Microsoft.DesktopVirtualization/scalingPlans validation pipeline. Verify the failing test and fix.
An API version update is needed.

### To reproduce

Rerun Microsoft.DesktopVirtualization/scalingPlans pipeline and verify the static validation logs

**Comment by ahmadabdalla** [comment]
@eriqua 

Having updated the API to the latest stable version `2022-09-09`. I see there are some limitations in relation to the region where that API is available., although it is documented in the [template reference doc](https://learn.microsoft.com/en-us/azure/templates/microsoft.desktopvirtualization/2022-09-09/scalingplans?pivots=deployment-language-bicep)


```powershell
  Status Message: No registered resource provider found for location 'westeurope' and API version '2022-09-09' for type 'scalingplans'. The supported api-versions are '2019-01-23-preview, 2019-09-24-preview, 2019-12-10-preview, 2020-09-21-preview, 2020-10-19-preview, 2020-11-02-preview, 2020-11-10-preview, 2021-01-14-preview, 2021-02-01-preview, 2021-03-09-preview, 2021-04-01-preview, 2021-05-13-preview, 2021-09-03-preview, 2022-01-12-privatepreview, 2022-02-10-preview, 2022-04-01-preview, 2021-07-12'. The supported locations are 'uksouth, ukwest, japaneast, australiaeast, canadaeast, canadacentral, northeurope, westeurope, eastus, eastus2, westus, westus2, westus3, northcentralus, southcentralus, westcentralus, centralus'. (Code:NoRegisteredProviderFound)
  
  Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)
   - {
    "error": {
      "code": "NoRegisteredProviderFound",
      "message": "No registered resource provider found for location 'westeurope' and API version '2022-09-09' for type 'scalingplans'. The supported api-versions are '2019-01-23-preview, 2019-09-24-preview, 2019-12-10-preview, 2020-09-21-preview, 2020-10-19-preview, 2020-11-02-preview, 2020-11-10-preview, 2021-01-14-preview, 2021-02-01-preview, 2021-03-09-preview, 2021-04-01-preview, 2021-05-13-preview, 2021-09-03-preview, 2022-01-12-privatepreview, 2022-02-10-preview, 2022-04-01-preview, 2021-07-12'. The supported locations are 'uksouth, ukwest, japaneast, australiaeast, canadaeast, canadacentral, northeurope, westeurope, eastus, eastus2, westus, westus2, westus3, northcentralus, southcentralus, westcentralus, centralus'."
    }
  } (Code:BadRequest)
```

Do we have a CARML defined preference on using an API that is available in most regions vs. just the latest version?

**Comment by eriqua** [comment]
@ahmadabdalla we don't, but it's a good point. We probably shouldn't consider API versions limiting regions in our Pester test if other versions exist without that limitation.
Is there any version able to pass the current test but also not limiting regions? A preview would be fine I think.

**Comment by ahmadabdalla** [comment]
@eriqua will enable the latest API that is available in all regions.
