### ISSUE TITLE
[Feature Request]: Standardize treatment of parameters that are defined as Strings but should be Booleans (By definition of the parameter)

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#2546]
### Description

On the back of the discussion here ==> https://github.com/Azure/ResourceModules/pull/2515#discussion_r1064626383 and #2515 

Currently some Resource provider - resource types are exposing parameters that look like a Boolean but are actually defined as strings. This brings confusion of the resource consumer and unnecessarily requires implementing an allow types on the parameter usage.

For example in the Network Manager Configuration Module:

```bicep
@allowed([
  'True'
  'False'
])
param deleteExistingPeering string = 'False'
```

This parameter is defined as a string, and that is correct according to the template reference [documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/networkmanagers/connectivityconfigurations?pivots=deployment-language-bicep#connectivityconfigurationproperties)

![image](https://user-images.githubusercontent.com/28486158/211410184-9d62078d-e6b0-4a13-86e6-f7104d608be1.png)
![image](https://user-images.githubusercontent.com/28486158/211409961-2599763a-f3aa-4ff2-8330-f4a1be42f302.png)

## Requirement

Discuss and implement an approach for handling the scenario with the following options in mind:
- Continue to align to the RP documentation and treat them as strings.
- Expose these parameters as Booleans (as a good CARML practice) and then convert the value to a string when sent to the API like `deleteExistingPeering : string(deleteExistingPeering )`

Keeping in mind this behavior also exists in the `Microsoft.ContainerService\managedClusters` resource type. Also we should have good guidelines in our wiki for contributors.

> **Note:** We should test for the different affected providers whether they accepts the boolean / string-to-boolean values (i.e., run all test pipelines) to make sure it works. If anything break and there is not obvious solution we can revisit this approach in a discussion.

**Comment by AlexanderSehr** [comment]
Following a discussion we opted to give the suggested implementation a spin as long as everything (about 4 modules) is successfully tested. If anything fails, we may need to revist this approach.

**Comment by AlexanderSehr** [comment]
Going full circle @ahmadabdalla. Given the spec in AVM, I guess we can close the issue for CARML and have the modules updated in AVM (where not yet happened)? 

@JPEasier, please note, your AKS module still needs to be updated as it uses the string parameter for boolean values still in quite a few locations.
For example:
```bicep
@allowed([
  'false'
  'true'
])
@description('Optional. Specifies the balance of similar node groups for the auto-scaler of the AKS cluster.')
param autoScalerProfileBalanceSimilarNodeGroups string = 'false'
```

**Comment by ahmadabdalla** [comment]
@AlexanderSehr agreed
