### ISSUE TITLE
[Feature request from Discussions] StorageAccount - Add LargeFileSharesState property

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2570]
### Discussed in https://github.com/Azure/ResourceModules/discussions/2568

<div type='discussions-op-text'>

<sup>Originally posted by **dibcar** January 13, 2023</sup>
Hi, the property 'LargeFileSharesState' is not in the storageaccount module. Is there another way to set this property to 'enable' or the property is just missing in the module ?
Thanks</div>

**Comment by ahmadabdalla** [comment]
@eriqua shall we also include `allowCrossTenantReplication` under this same feature request? 

It is a recommendation based on a [Policy Definition](https://www.azadvertizer.net/azpolicyadvertizer/92a89a79-6c52-4a7e-a03f-61306fc49312.html) and we can set it to false as default for security best practices.

Reference from the Storage template documentation:

allowCrossTenantReplication	Allow or disallow cross AAD tenant object replication. The default interpretation is true for this property.

**Comment by eriqua** [comment]
@ahmadabdalla nothing against that as completeness is what we should aim for. I think it just depends on how much more adding all missing properties would take compared to adding the one requested. 
We could also prioritize this feature and meanwhile open an issue to generally extend the resource with all missing properties.

**Comment by ahmadabdalla** [comment]
@eriqua .. created an issue for it https://github.com/Azure/ResourceModules/issues/2573
