### ISSUE TITLE
[Bug Report]: Publish Error on Microsoft.RecoveryServices\Vaults

### ISSUE THREAD

**Issue by Kschmidt0511** [Azure/ResourceModules#2581]
### Describe the bug

Publish Module To Template Specs error due to template name exceeding maxLength(90) 

The long file name restricts character count for naming conventions in the file path. Wondering if there is a solution to this, and if a maxLength of 90 is important for the name. The few solutions I can think of are unideal.

Thanks!

### To reproduce

Publishing Module To Template Specs with given template file path "microsoft.recoveryservices.vaults.replicationfabrics.replicationprotectioncontainers.replicationprotectioncontainermappings" creates this error. 

### Code snippet

```Bicep
Performing the operation "Publish" on target "Template spec [microsoft.recoveryservices.vaults.replicationfabrics.replicationprotectioncontainers.replicationprotectioncontainermappings] version [0.1.32-prerelease]".


Line |
  83 |              New-AzTemplateSpec @templateSpecInputObject -Force
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 'templateSpecName' exceeds maximum length of '90'

##[error]PowerShell exited with code '1'.
```

**Comment by eriqua** [comment]
Hi @Kschmidt0511, this is unfortunately a known issue, already filed in issue #1172

**Comment by rahalan** [comment]
Closed because of duplicate
