### ISSUE TITLE
[Failed pipeline] Network: NetworkInterfaces

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#2595]
failed run: https://github.com/Azure/ResourceModules/actions/runs/3975975740

**Comment by ahmadabdalla** [comment]
@AlexanderSehr I had a quick look and seems the new logic doesn't consider the use case where the RP name like ('network') is also included in the resource name (i.e. networkSecurityGroups), hence causing the substring length to be greater than string itself. 

```powershell
'networkmanagers'.Substring(7, 15)
```

**Comment by AlexanderSehr** [comment]
Correct @ahmadabdalla . Just updated the logic to bypass the provider entirely and it works like a charm
