### ISSUE TITLE
[Feature Request]: onboard CodeTour for VSCode users onboarding the CI Environment

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/ResourceModules#2606]
## What is VS Code Tour

CodeTour is a Visual Studio Code extension, which allows you to record and play back guided walkthroughs of your codebases. It's like a table of contents, that can make it easier to onboard (or re-board!) to a new project/feature area, visualize bug reports, or understand the context of a code review/PR change.

## Marketplace Link
[CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour)

**Comment by ChrisSidebotham** [comment]
## How we can adopt this

For contributors we can specify 'Tours' of the code for different actions, example I use a simple updating modules. Using the `extensions.json` file in the `.vscode` folder we can recommend the users to add the extensions to the workspace upon opening of the repository.

## CodeTour Example - Updating Modules

![image](https://user-images.githubusercontent.com/48600046/213923476-55731dd8-064b-4dfb-9e66-15db23b80598.png)

### Steps
![image](https://user-images.githubusercontent.com/48600046/213923518-47272ae0-7dfb-4b5f-8087-7e27fa483f14.png)

![image](https://user-images.githubusercontent.com/48600046/213923538-65c63a03-84fb-4e65-90ac-9bb47ba8802a.png)

![image](https://user-images.githubusercontent.com/48600046/213923549-ca21575b-80f6-477e-800e-b410592d399a.png)

![image](https://user-images.githubusercontent.com/48600046/213923555-58c924ca-1d29-4ce5-9659-0262b39fe041.png)

### Tour-as-Code
![image](https://user-images.githubusercontent.com/48600046/213923593-13ee3629-c59a-45d0-9867-e68e1e3e35c3.png)

### Recommended Extensions
![image](https://user-images.githubusercontent.com/48600046/213923614-27d9176a-bed1-4821-ade3-6e1239f9243c.png)

**Comment by ChrisSidebotham** [comment]
Agreement to Demo 3 CodeTours on 20/02/2023:

1. Introduction to Repositories
2. Configuring Settings.yml
3. Updating Modules for CI environments

**Comment by lsnoddy** [comment]
Added a settings.yml code tour to the 'users/csidebotham/sample-code-tour branch

**Comment by ChrisSidebotham** [comment]
Will open new issue in AVM for configuring codeTour @lsnoddy
