### ISSUE TITLE
[Bug Report]: InternalLoadBalancingMode allowed values are incorrect in ASEv3 module

### ISSUE THREAD

**Issue by willchoko** [Azure/ResourceModules#2622]
### Describe the bug

IntermalLoadBalancingMode allowed values for ASE v3 are 0, 3 whereas those values are set to None, Web and Publishing

### To reproduce

This module is not up-to-date for ILB ASEv3 deploying 
https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.Web/hostingEnvironments/deploy.bicep
Please, would it be possible to update the module to the latest version (2022-03-01) of ASEv3? Thanks

**Comment by ahmadabdalla** [comment]
@willchoko, I'm almost done publishing an update for ASE to use the latest API as per [documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/hostingenvironments?pivots=deployment-language-bicep). This will include all the new parameters in that document. However, wanted to clarify something quick, 

You've mentioned that the parameter `internalLoadBalancingMode` takes values 0,3. However as per the parameter properties in the documentation, the value is `string` and takes the values:
'None'
'Publishing'
'Web'
'Web, Publishing'

I've also created two ASEs, one internal and one external, and here are the values as per the API:

**Internal**
![image](https://user-images.githubusercontent.com/28486158/215400269-c986ca80-2a62-4732-9a2e-5a644f18f0ba.png)

**External**
![image](https://user-images.githubusercontent.com/28486158/215400362-f03c07c6-313c-4466-abef-f24176e52997.png)

Is the bug you're referring to related to the module not currently supporting the parameter `internalLoadBalancingMode` value `Web, Publishing`?

**Comment by willchoko** [comment]
Hello Ahmad,

You are right. The issue about InternalLoadBalancingMode was on the
combination "Web,publishing" missing among allowed values.
I Think we should have : ("none", "web", "publishing", "web,publishing").

Glad that you are updating the ASEv3 api version to the latest one. This
will allow me to deploy ASE and its customdomainsuffix within a same module.

Many thanks.

William B. Chokouago

**Comment by willchoko** [comment]
Nice !

**Comment by ahmadabdalla** [comment]
@willchoko the branch is ready for PR, but I would like you to test it out as well before we merge the changes in. Please use this branch:
https://github.com/Azure/ResourceModules/tree/users/ahmad/2622_AseV3/modules/Microsoft.Web/hostingEnvironments

It incorporates new properties for ASE, including managed identities, networking configuration and custom dns suffix.

**Comment by willchoko** [comment]
Hello Ahmad,
It seems like the property "identity" is not required in ASEv3 deployment. Please see attached files

![ASE-identity-type](https://user-images.githubusercontent.com/123717894/216110436-5d819f6e-e6f8-4f73-b819-8e0bc0d245fc.png)
![ASE-identity-var](https://user-images.githubusercontent.com/123717894/216110439-abdedd4a-7362-4881-bffd-4dcf5583d1e4.png)


Thanks

**Comment by ahmadabdalla** [comment]
That's ok. It's a common warning across many modules. He's property is supported.

**Comment by willchoko** [comment]
So everything is Ok
Thanks

**Comment by willchoko** [comment]
@ahmadabdalla, on the identity variable, the value Null is not expected. 
A suggestion is to replace it by {} as explained here:  https://github.com/Azure/bicep/issues/7295

![image](https://user-images.githubusercontent.com/123717894/216322205-170f4523-b098-4584-a83f-f036f4375f56.png)

![image](https://user-images.githubusercontent.com/123717894/216322370-3d049f8b-5774-400a-a992-f2dc8c8c6814.png)

**Comment by ahmadabdalla** [comment]
Right. Not sure why it wasn't showing like that before. I've updated it
