### ISSUE TITLE
Microsoft.ServiceBus/namespaces/topics - Param maxMessageSizeInKilobytes int = 1024 causes errror.

### ISSUE THREAD

**Issue by dannyD-11** [Azure/ResourceModules#2629]
Microsoft.ServiceBus/namespaces/topics - Param maxMessageSizeInKilobytes int = 1024. This value needs to be set to default 256. Else it will cause an error when deploying and using the default 1024 value.

https://github.com/Azure/ResourceModules/blob/d80714f7090564d1c2b05c48eefb66e60091ee49/modules/Microsoft.ServiceBus/namespaces/topics/deploy.bicep#L27

Error when deploying:
"details": [
    {
      "code": "MessagingGatewayBadRequest",
      "message": "<Error><Code>400</Code><Detail>SubCode=40000. Bad Request. To know more visit https://aka.ms/sbResourceMgrExceptions. . 

Regards,

**Comment by JPEasier** [comment]
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"MessagingGatewayBadRequest\",\r\n    \"message\": \"SubCode=40000. The property value for 'MaxMessageSizeInKilobytes' must be between 1024 and 102400 when the namespace 'carmlsbncom001' is using 'Premium' tier.\\r\\nParameter name: MaxMessageSizeInKilobytes\\r\\nActual value was 256. TrackingId:4b361e01-9a8e-4152-b8d1-c734e232d0e5_G3, SystemTracker:carmlsbncom001.servicebus.windows.net:carmlsbncomt001, Timestamp:2023-02-23T13:38:09\"\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by fblix** [comment]
Understood. As far as we were able to find out, you can only specify `maxMessageSizeInKilobytes` when using the premium tier.
Basic does not support topics at all and standard does not all for `maxMessageSizeInKilobytes` to be specified.

We'll have a look and update module accordingly.
