### ISSUE TITLE
[Failed pipeline] RecoveryServices: Vaults

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#2631]
failed run: https://github.com/Azure/ResourceModules/actions/runs/4048059923

**Comment by ahmadabdalla** [comment]
@rahalan pipeline didn't fail on this run.. thoughts?

**Comment by ahmadabdalla** [comment]
Should auto close based on second run

**Comment by rahalan** [comment]
successful run: https://github.com/Azure/ResourceModules/actions/runs/4048059923
