### ISSUE TITLE
[Failed pipeline] ContainerInstance: ContainerGroups

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#2635]
failed run: https://github.com/Azure/ResourceModules/actions/runs/4048059875

**Comment by ahmadabdalla** [comment]
There seems to be an issue with the deployment:

```json
  "details": [
    {
      "code": "ResourceDeploymentFailure",
      "message": "The resource provision operation did not complete within the allowed timeout period."
    }
```

![image](https://user-images.githubusercontent.com/28486158/215716121-59b9eb94-3d9b-4fe6-869f-efc909ee664c.png)
![image](https://user-images.githubusercontent.com/28486158/215716226-e407a2a3-44c6-44e5-802f-9b875a68996e.png)

**Comment by rahalan** [comment]
successful run: https://github.com/Azure/ResourceModules/actions/runs/4048059875
