### ISSUE TITLE
[Feature Request]: Add module for Azure Database for MySQL Flexible Server

### ISSUE THREAD

**Issue by janegilring** [Azure/ResourceModules#2647]
### Description

Add a module for provisioning Azure Database for MySQL Flexible Server (Microsoft.DBforMySQL/flexibleServers)

**Comment by ahmadabdalla** [comment]
Hi @janegilring this module is already available in the CARML library. Please see [link](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.DBforPostgreSQL/flexibleServers)

**Comment by janegilring** [comment]
@ahmadabdalla That resource is for PostgreSQL, not MySQL :)

**Comment by ahmadabdalla** [comment]
Oops. Sorry I missed that bit.
