### ISSUE TITLE
[Failed pipeline] Insights: DataCollectionRules

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#2651]
failed run: https://github.com/Azure/ResourceModules/actions/runs/4086938800

**Comment by rahalan** [comment]
failed run: https://github.com/Azure/ResourceModules/actions/runs/4095992200

**Comment by krbar** [comment]
Looks like a duplicate of #2776, which has been fixed by #2809. Probably the issue can be closed.

**Comment by krbar** [comment]
Fixed by #2809, closing.
