### ISSUE TITLE
[Feature Request]: Add flux support to AKS (managedClusters)

### ISSUE THREAD

**Issue by akata72** [Azure/ResourceModules#2656]
### Description

Add Flux support (gitops) in the managedCluster module.

Can the following modules be added as optional extensions and deployed together with the managedCluster:
- [Microsoft.KubernetesConfiguration/extension](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.KubernetesConfiguration/extensions)
- [Microsoft.KubernetesConfiguration/fluxConfigurations](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.KubernetesConfiguration/fluxConfigurations)

This would be similar to the approach taken with extensions on VMs in functionality from a VM deployment point of view, and NIC or Private Endpoint from an implementation point of view.

**Comment by MariusStorhaug** [comment]
https://learn.microsoft.com/en-us/azure/templates/microsoft.kubernetesconfiguration/fluxconfigurations?pivots=deployment-language-bicep

**Comment by MariusStorhaug** [comment]
Available here: 
https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.KubernetesConfiguration

So will use this issue to track the request incorporating these as cross-referenced modules of the managedCluster module.
