### ISSUE TITLE
[PSRule] Fix Rule Azure.Policy.AssignmentDescriptors

### ISSUE THREAD

**Issue by fabmas** [Azure/ResourceModules#2668]
### Rule Azure.Policy.AssignmentDescriptors

Error: AZR-000143: ***apasubmin001 failed Azure.Policy.AssignmentDescriptors. Policy assignments should use a display name and description.

:question: Validate with the team if the following actions are good:

1. Set "description" and "displayName" as mandatory parameters in the deploy.bicep file. 
2. Add the following parameters on the deploy.test.bicep:
 ```
description: '[Description] Policy Assignment at the management group scope'   
displayName: '[Display Name] Policy Assignment at the management group scope'
```
Above actions should be applied to the following files:

- ResourceModules/modules/Microsoft.Authorization/policyAssignments/.test/sub.min/deploy.test.bicep 
- ResourceModules/modules/Microsoft.Authorization/policyAssignments/.test/rg.min/deploy.test.bicep 
- ResourceModules/modules/Microsoft.Authorization/policyAssignments/.test/mg.min/deploy.test.bicep 
- ResourceModules/modules/Microsoft.Authorization/policyAssignments/deploy.bicep

**Comment by eriqua** [comment]
OPT 1: Configure the Rule to be ignored for files (i.e., exclusion)
OPT 2: Make the property mandatory and update the test cases to comply

Team decides for OPT1
