### ISSUE TITLE
[Failed pipeline] Compute - VirtualMachineScaleSets

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#2703]
failed run: https://github.com/Azure/ResourceModules/actions/runs/4168125273

**Comment by krbar** [comment]
I tried to reproduce this issue, but the workflows runs fine: https://github.com/Azure/ResourceModules/actions/runs/4198668446

**Comment by rahalan** [comment]
successful run: https://github.com/Azure/ResourceModules/actions/runs/4198668446
