### ISSUE TITLE
[Failed pipeline] KubernetesConfiguration - Extensions

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#2782]
failed run: https://github.com/Azure/ResourceModules/actions/runs/4172633174

**Comment by krbar** [comment]
I tested the module using GH workflow (https://github.com/Azure/ResourceModules/actions/runs/4198632594) and also locally, both test were successful. I suggest to close this issue.

**Comment by rahalan** [comment]
successful run: https://github.com/Azure/ResourceModules/actions/runs/4198632594
