### ISSUE TITLE
Add and run 'lock' test to all modules that support it

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#280]
We should test our locks implementation by using a 'noUpdate' lock. However, we have to make sure this does not cause issues with child-resources. Hence this has to be tested first, before rolling it out.

**Comment by eriqua** [comment]
A possible workaround that came out during an internal discussion today: apply a no deletion lock and then leverage the new removal approach using deployment names to first delete the lock and then proceed with resource removal. Feasibility needs to be tested.

**Comment by rahalan** [comment]
Maybe need to be split into multiple issues to test per resource provider
