### ISSUE TITLE
[Feature Request]: Discuss the implementation of strict versioning in the CARML CI

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#2808]
### Description

Related to issue #753 and the original discussion around a custom public registy (which would have required the same) #1645, this issue shall be used to discuss the required efforts and to plan the implementation of a strict versioning policy in the CARML CI. 

Currently, the versions in the `version.json` files are only intended to be used by those that set up the CARML CI for their own while we in this repository consider all modules as 'latest' unless they are part of a repository release.

Note: A lot of points are already documented in #1645

**Comment by rahalan** [comment]
Depending when/how CARML modules will be published into the PBR. After that, it needs to be revisited.

**Comment by AlexanderSehr** [comment]
> Depending when/how CARML modules will be published into the PBR. After that, it needs to be revisited.

Will close as this is currently under development
