### ISSUE TITLE
[Feature Request]: Add telemetry deployment to modules where it is missing

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#2810]
### Description

I noticed there are several modules that currently lack the telemetry deployment. 

To remediate this, we should go through all `deploy.bicep` files, add the missing deployments and corresponding control parameters (e.g. in parents)

**Comment by krbar** [comment]
I've checked that we currently don't have any modules without telemetry. However I discovered that there are a few module tests are not using the `enableDefaultTelemetry` parameter, which leads to usage of the default value.  I will fix this.
