### ISSUE TITLE
Bug: Output `principalId` needs fix in `diskEncryptionSet` 

### ISSUE THREAD

**Issue by Lddeiva** [Azure/ResourceModules#2854]
When the `SystemAssignedidentity` is not enabled, this line shows deployment time errors as it couldn't find the `principalId`.

https://github.com/Azure/ResourceModules/blob/6bf1b55d34d10574e15a360493dca6c239e81d07/modules/Microsoft.Compute/diskEncryptionSets/deploy.bicep#L128

The status of `PrincipalId` when `SystemAssignedidentity` is not enabled
![image](https://user-images.githubusercontent.com/61077834/222080312-dd07ef14-1103-4000-95b2-18edce4a79a9.png)

**Error: -**
![image](https://user-images.githubusercontent.com/61077834/222081681-ab702f2f-5554-4103-95b4-8ff39a7556f7.png)

**Comment by Lddeiva** [comment]
I didn't get the issue template as I opened this issue from code.

**Comment by ahmadabdalla** [comment]
@Lddeiva Thanks for raising the bug. I've opened a PR to address it
