### ISSUE TITLE
logic app workflow definition issue

### ISSUE THREAD

**Issue by ingio** [Azure/ResourceModules#2858]
Hi, I hope you can help.
I'm trying to deploy Logic App with the CARML bicep module that has http request with POST that then sends to event grid with connection.
I seem to be having issue with the connection part as its down to formatting or something as I can't see any examples in the document or from MS article. There are samples in JSON and I have also exported Logic App that was created in portal to template and converted to bicep template but no luck yet.

My `workflowTriggers` is working fine and deploys ok.
sample below:
```  
workflowTriggers: {
  manual: {
    type: 'Request'
    kind: 'Http'
    inputs: {
      method: 'POST'
```

The issue is either in the `workflowActions` or `workflowParameters`.
```
workflowActions: {
  Publish_Event: {
    runAfter: {}
    type: 'ApiConnection'
    inputs: {
      body: [
        {
            <...>
        }
      ]
      host: {
        connection: {
          name: '@parameters(\'$connections\')[\'azureeventgridpublish\'][\'connectionId\']'
        }
      }
      method: 'post'
      path: '/eventGrid/api/events'
    }
  }
}
workflowParameters: {
  azureeventgridpublish: {
    connectionId: '/subscriptions/<...>/providers/Microsoft.Web/connections/azureeventgridpublish'
    connectionName: 'azureeventgridpublish'
    id: '/subscriptions/<...>/providers/Microsoft.Web/connections/azureeventgridpublish'
  }
}
```

**Comment by AlexanderSehr** [comment]
Note: We should try to replicate the issue and if it turns out to be a bug, fix it. If not, add an example as part of the deployment test.
