### ISSUE TITLE
[Feature Request]: Enable auto-add to project workflows

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2873]
### Description

Setup and enable the `auto-add to project` workflow in both `Backlog` and `Bug` board projects.

This feature can replace the assign issue to project pipeline.
Combined with the change in PR #2696, this issue also allows to get rid of the custom PAT token created to manage issues

This feature is currently in Beta but tested successfully
![image](https://user-images.githubusercontent.com/56914614/223195795-dda7da9a-2e17-46b1-8883-cd1638f96580.png)

![image](https://user-images.githubusercontent.com/56914614/223199225-ed027900-6275-44b6-ac10-73503119e34e.png)

**Comment by AlexanderSehr** [comment]
As it is already active, we should think about disabling the original custom pipeline.
