### ISSUE TITLE
[Feature Request]: Leverage the ".?" operator for condition checks for objects

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#2874]
### Description

Based on a new Bicep feature referred to as the `.?` operator. It can be used to check if a value contains a particular property or element. We should align with this new model in our conditions in the repository. This is more prominent when we call child modules from the parent.

![image](https://user-images.githubusercontent.com/28486158/223224919-42f0cf4c-e2a2-4798-9252-eb2bda15efb9.png)

See screenshot for example

**Comment by AlexanderSehr** [comment]
We implemented this in many places now, during the migration to AVM and after. It's not implemented everywhere yet, though we could argue it's now up to the module owner to decide. Will hence close this at least here in CARML for now.
