### ISSUE TITLE
Application Gateway name length restriction

### ISSUE THREAD

**Issue by modbase** [Azure/ResourceModules#2894]
https://github.com/Azure/ResourceModules/blob/419e56a01661d34db7b28c6640f4fa5b1ed1c0fe/modules/Microsoft.Network/applicationGateways/deploy.bicep#L2

What is the reason for restricting the AGW name length to 24 even though according to the [Microsoft documentation](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftnetwork) it should be in the 1-80 range.

**Comment by AlexanderSehr** [comment]
Fixed as part of #3199
