### ISSUE TITLE
Add a  parent-resource scope to all templates where bicep demands it

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#294]
Right now we have a lot of cases (like `nested_rbac`) where bicep complains that we should use a `scope` property.

We can achive this by adding the parent (scoped) resource in question with the `existing` keyword. For example: 

![image](https://user-images.githubusercontent.com/5365358/139147741-19e498ea-1165-4241-842f-a898fba4c21a.png)

In ARM, this is just translated to something similar to:

![image](https://user-images.githubusercontent.com/5365358/139147808-e143ba8e-5a91-4703-b2b6-6dcae004db95.png)

**Comment by MariusStorhaug** [comment]
The PR for constructs is the only one left for /providers/ references that are failing.
