### ISSUE TITLE
[Feature Request]: Allow custom computerName for virtual machines

### ISSUE THREAD

**Issue by modbase** [Azure/ResourceModules#2988]
### Description

The virtualMachines module now uses the VM resource name as the computer name, but some of our customers have a naming convention where the Azure resource name does not match the name of the hostname.

Therefore it would be useful to have an optional parameter to specify the computerName and simply use the VM resource name as default value.

**Comment by khaliddermoumi** [comment]
I'm in the same situation - there is a resource naming convention which mandates the prefix "vm", see also: [Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations), but computer names need to be different of course.
