### ISSUE TITLE
Subnet module reports delta applicationGatewayIPConfigurations for --what-if

### ISSUE THREAD

**Issue by markdebruijne** [Azure/ResourceModules#3003]
When redeploying a subnet based on the `/Microsoft.Network/virtualNetworks/subnets/deploy.bicep` template, a delta is reported between
- my input template doesn't specify the `properties.applicationGatewayIpConfigurations`
- the existing subnet does have entries in that property (array) as result of an Application Gateway being using that subnet.

~I understand that a NSG that is missing as input, is being cleared when redeploying the subnet. As that is a configuration at the time you deploy a subnet. But the IP configuration of an Application Gateway is a result of a later deployment in which we deploy an AppGW with referencing such subnet. This leads the chicken and egg situation: AppGW needed to deploy the subnet, and the AppGW needs the subnet as input.~
**update**: run the deployment it didn't remove the AppGW IP configuration, so it is expected to be only a flaw in the `--what-if` validation (perhaps on ARM side?)

example values of a that `applicationGatewayIpConfigurations` array
```json
id: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgwresource/gatewayIPConfigurations/appGatewayIpConfig"
```

I think it should be similar to the `ipConfigurations` that are also added later to the subnet, when a VM joins it for example. Those are not reported as delta with the `--what-if` validation`

**Comment by rahalan** [comment]
That issue is out of the CARML scope. Please open an issue for it  here: https://github.com/Azure/arm-template-whatif
