### ISSUE TITLE
[Bug Report]: specify service endpoints not working as described

### ISSUE THREAD

**Issue by rfontijn** [Azure/ResourceModules#3007]
### Describe the bug

Specifying service endpoints cannot be done in the way it is described in the docs, like:
```
serviceEndpoints: [
    'Microsoft.EventHub'
    'Microsoft.Sql'
    'Microsoft.Storage'
    'Microsoft.KeyVault'
]
```
The way it DOES work:
```
serviceEndpoints: [
      {
        service: 'Microsoft.Storage'
      }
    ]
```

### To reproduce

Create a subnet with endpoints in this format:

```
serviceEndpoints: [
    'Microsoft.EventHub'
    'Microsoft.Sql'
    'Microsoft.Storage'
    'Microsoft.KeyVault'
]
```

results in an error

**Comment by rahalan** [comment]
@rfontijn thanks for the report. After a quick check, I could not find the described wrong description in the documentation. Can you please add a link to the incorrect documentation? Thanks!

**Comment by rfontijn** [comment]
Hi @rahalan, it's here: https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.Network/virtualNetworks/subnets#parameter-usage-serviceendpoints
