### ISSUE TITLE
[Feature Request]: module to do DNS resolver forwarding rules

### ISSUE THREAD

**Issue by GeraldGoldstein** [Azure/ResourceModules#3104]
### Description

add a module to add forwarding rules using Microsoft.Network/dnsForwardingRulesets and Microsoft.Network/dnsForwardingRulesets/forwardingRules

**Comment by AlexanderSehr** [comment]
Hey @GeraldGoldstein, please note that this module was added in the meantime, and eventuall even migrated to AVM. You can find it [here](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/network/dns-forwarding-ruleset),
