### ISSUE TITLE
[Feature Request]: userassignedidentities should output clientId

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/ResourceModules#3113]
### Description

Often clientId is needed from the user managed identity (to access kv, to pull images from ACR).
Please add output for the clientId, it can be found on the UMI `properties.clientId`

**Comment by AlexanderSehr** [comment]
Note, for RBAC assignments you'll need the `principalID` (i.e., the `objectID`). The `clientID` is the `applicationID`.

**Comment by AlexanderSehr** [comment]
When we update the output, we should be specific about the wording and use the one from the portal to differentiate the principal- vs the client-ID output accordingly.

**Comment by davidkarlsen** [comment]
@AlexanderSehr it's needed here:

```bicep
module appService 'br/dnb:bicep/modules/microsoft.web.sites:0.4.1227' = {
  name: '${fullResourceName}-as'
  params: {
    name: '${fullResourceName}-as'
     ...
    siteConfig: {
      linuxFxVersion: 'DOCKER|${acrRegistry}/${appImage}:${appVersion}'
      acrUseManagedIdentityCreds: true
      acrUserManagedIdentityID: user.properties.clientId <--
      ....
    }
    appSettingsKeyValuePairs: {
      WEBSITES_PORT: '8080'
      SPRING_CLOUD_AZURE_KEYVAULT_SECRET_PROPERTYSOURCES_0_ENDPOINT: keyVaultUrl
      SPRING_CLOUD_AZURE_KEYVAULT_SECRET_PROPERTYSOURCES_0_CREDENTIAL_CLIENTID: user.properties.clientId <-- 
      SPRING_CLOUD_AZURE_KEYVAULT_SECRET_PROPERTYSOURCES_0_CREDENTIAL_MANAGEDIDENTITYENABLED: 'true'
```

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr it's needed here:
> 
> ```bicep
> resource user 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' existing = {
>   name: userAssignedIdentity
> }
> 
> module appService 'br/dnb:bicep/modules/microsoft.web.sites:0.4.1227' = {
>   name: '${fullResourceName}-as'
>   params: {
>     name: '${fullResourceName}-as'
>      ...
>     siteConfig: {
>       linuxFxVersion: 'DOCKER|${acrRegistry}/${appImage}:${appVersion}'
>       acrUseManagedIdentityCreds: true
>       acrUserManagedIdentityID: user.properties.clientId <--
>       ....
>     }
>     appSettingsKeyValuePairs: {
>       WEBSITES_PORT: '8080'
>       SPRING_CLOUD_AZURE_KEYVAULT_SECRET_PROPERTYSOURCES_0_ENDPOINT: keyVaultUrl
>       SPRING_CLOUD_AZURE_KEYVAULT_SECRET_PROPERTYSOURCES_0_CREDENTIAL_CLIENTID: user.properties.clientId <-- 
>       SPRING_CLOUD_AZURE_KEYVAULT_SECRET_PROPERTYSOURCES_0_CREDENTIAL_MANAGEDIDENTITYENABLED: 'true'
> ```

Great, thanks for the example 😊 @eriqua, now we have our answer 😄
