### ISSUE TITLE
[Feature Request]: Add tags to VMSS extensions

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#3124]
### Description

Add tags input parameter to VMSS extensions as already done for VM extensions.

**Comment by oliverlabs** [comment]
Hi @eriqua, 

this input parameter does not exist in the current VMSS extensions API definition: https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachinescalesets/virtualmachines/extensions?pivots=deployment-language-bicep

**Comment by eriqua** [comment]
@oliverlabs good catch, 
The issue has been created quickly after PR #3115 with the intention of keeping VM and VMSS implementation aligned, since often their properties are the same.
It indeed seems tags are not yet available for VMSS extensions as they are for VM extensions.

Thanks for the heads up. Closing.
