### ISSUE TITLE
[BPR alignment] [Modules] ProviderNamespace-ResourceType folders must be aligned

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#3132]
The BPM tool must be able to cope with CARML's folder naming (i.e., casing, singular vs. plural names, etc.) - either by applying a different rule set, or not testing casing/naming in the first place.

## Decision

Align CARML to BPM.  Move from camelCase to lowercase with hyphens
Example: Microsoft.Network/virtualNetworks -> network/virtual-networks

## Solution

> Note: the removal of the `Microsoft.` prefix from the resouce provider folder name will be implemented as part of issue #3056 .

To implement it, we can use the script

<details>
<summary>Converstion script</summary>

```PowerShell
<#
.SYNOPSIS
Re-format the name of every CARML module to match the requirements of the Public Bicep Registry

.DESCRIPTION
The names are formatted as per the following rules:
- Add a '-' prefix to every upper-case character
- Make the entire name lower case

For example, it re-formats
- 'AppConfiguration\configurationStores\keyValues\deploy.bicep'
to
- app-configuration\configuration-stores\key-values\deploy.bicep

.PARAMETER ModulesFolderPath
Mandatory. The path to the modules who's folder names should be converted.

.EXAMPLE
Set-CARMLFoldersForPBR -ModulesFolderPath 'C:\dev\ip\Azure-ResourceModules\ResourceModules\modules'

Convert all folders in path 'C:\dev\ip\Azure-ResourceModules\ResourceModules\modules'

.NOTES
This script should only be run AFTER the 'Microsoft.' provider namespace prefix was removed.
Identifiers such as 'DBforPostgreSQL' becomes 'd-bfor-postgre-s-q-l' which should probably be manually reverted to 'db-for-postgre-sql'.
#>
function Set-CARMLFoldersForPBR {

    [CmdletBinding(SupportsShouldProcess = $true)]
    param (
        [Parameter(Mandatory = $true)]
        [string] $ModulesFolderPath
    )

    $relevantFolderPaths = (Get-ChildItem -Path $ModulesFolderPath -Recurse -Directory).FullName | Where-Object {
        $_ -notlike '*.bicep*' -and
        $_ -notlike '*.shared*' -and
        $_ -notlike '*.test*'
    } | Sort-Object -Descending

    foreach ($folderPath in $relevantFolderPaths) {

        $folderName = Split-Path $folderPath -Leaf

        if ($folderName -cmatch '[A-Z]+') {
            # Has upper case characters
            # Explanation:
            # (?<!^): This is a negative lookbehind assertion that ensures the match is not at the beginning of the string. This is used to exclude the first character from being replaced.
            # ([A-Z]): This captures any uppercase letter from A to Z using parentheses.
            $newName = $folderName -creplace '(?<!^)([A-Z])', '-$1'
        } else {
            # No upper case characters
            $newName = $folderName
        }

        $newName = $newName.ToLower()

        # Replace the name if the new name is not the same as the old
        if ($newName -ine $folderName) {
            if ($PSCmdlet.ShouldProcess(('Folder [{0}] to [{1}]' -f ((Split-Path $folderPath -Leaf)), $newName), 'Update')) {
                $null = Rename-Item -Path $folderPath -NewName $newName -Force
            }
        }
    }
}
``` 

</details>

> **Note:** This script will get us 99% of the way, but we will have to handle special cases like 'DBforPostgreSQL' manuall (otherwise it becomes 'd-bfor-postgre-s-q-l')

**Comment by eriqua** [comment]
Part 1 - Remove `Microsoft.` prefix:
1. Rename RP folders - PS 
     - `Get-ChildItem -Filter Microsoft.* -Directory | Rename-Item -NewName { $_.FullName -replace 'Microsoft.','' }`
1. Update workflow and pipelines - VSC Search&Replace 
     - `modules/Microsoft.` with `modules/` in .github and .azuredevops folders
1. Update module cross references - VSC Search&Replace  
     - ` ../Microsoft.` with `../` in modules folder

**Comment by AlexanderSehr** [comment]
Also note: We'll need to manually review affects on docs - so that e.g. `Web/sites` is replaced with `web/sites`

**Comment by eriqua** [comment]
Part 2 - Convert module folder casing from camelCase to kebab-case

- Rename RP and RT folders
- Update workflow and pipelines
- Update references and cross-references in modules
- Update Set-ModuleReadme utility to cope with linking the child module readmes to parameter objects/arrays in parent modules e.g.,
   >| `tableServices` | _[tableServices](table-services/README.md)_ object | `{object}` |  | Table service and tables to create. |
- Update Set-ModuleReadme utility to cope with new casing in deployment scripts automatic generation

**Comment by eriqua** [comment]
Special conversion handling

```powershell
@{
    AAAA              = 'aaaa'
    AAD               = 'aad'
    CAA               = 'caa'
    CDN               = 'cdn'
    CNAME             = 'cname'
    DBforMySQL        = 'db-for-my-sql'
    DBforPostgreSQL   = 'db-for-postgre-sql'
    DocumentDB        = 'document-db'
    MX                = 'mx'
    NS                = 'ns'
    PowerBIDedicated  = 'power-bi-dedicated'
    PTR               = 'ptr'
    publicIPAddresses = 'public-ip-addresses'
    publicIPPrefixes  = 'public-ip-prefixes'
    SignalRService    = 'signal-r-service'
    SOA               = 'soa'
    SRV               = 'srv'
    TXT               = 'txt'
}
```
