### ISSUE TITLE
[Question/Feedback from Discussions] Extend parameters from a template

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#3142]
### Discussed in https://github.com/Azure/ResourceModules/discussions/2876

<div type='discussions-op-text'>

<sup>Originally posted by **DanielHRio** March  7, 2023</sup>
Hello Team,

I can see a lot of parameters in .azuredevops/modulePipelines are duplicate. Would it be helpful if the parameters can be set in a seperated template? I can see [this feature request](https://developercommunity.visualstudio.com/t/Extend-parameters-from-a-template/1202473?from=email&viewtype=all&space=21&entry=suggestion+Visual+Studio+FeedbackVisual+Studio+Feedbackdevelopercommunity.visualstudio.com&q=parameters&ftype=idea) in VS Developer Community, but the number of votes is low. Would it be helpful if everyone can pump it up?</div>

**Comment by AlexanderSehr** [comment]
If all our pipelines share the same defaults (and hence could share the same template) AND if the feature would be available, we'd likely implement it to use the latest and greates ;)

We'll ask the team to upvote the issue from our end as well and close this issue here for the time being.
