### ISSUE TITLE
[Question/Feedback from Discussions] Module for topic/subscription - Azure ServiceBus Namespace

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#3145]
### Discussed in https://github.com/Azure/ResourceModules/discussions/3071

<div type='discussions-op-text'>

<sup>Originally posted by **amullersusu** March 31, 2023</sup>
For my project I need to add a subscription in my topic for Azure ServiceBus Namespace, and would like to add this in the parameter file when deploying via AzureDevops yml pipeline. 

It looks like this is not currently possible as I need to add the Subscription as an module in order to reference and deploy it. Is this something that is being worked on?</div>

**Comment by AlexanderSehr** [comment]
That would be #3281

**Comment by rahalan** [comment]
Yes, it it solved. The eventsubscriptions are now children of topics and systemtopics. See test folder how to use them.
