### ISSUE TITLE
[Feature Request]: Define how to track questions/feedback issues

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#3159]
### Description

Recently, a new issue template has been made available with the purpose of tracking questions and feedback. 
Currently, issues opened through that template are automatically assigned the 'question' label and the issue is auto assigned to the Backlog project, the same way as feature request issues are.

Discuss how to differentiate question issues from feature requests. Possible options:
- Track questions in a different project and triage it similarly to the backlog and bug board
- Add a new column or project tab to the backlog project to track questions' status
- ...

**Comment by rahalan** [comment]
Team decides, the current process will not be changed.
