### ISSUE TITLE
[Bug Report]: Remove extra } in Microsoft.EventHub\namespaces\eventhubs\.bicep\nested_roleassignments.bicep

### ISSUE THREAD

**Issue by akata72** [Azure/ResourceModules#3166]
### Describe the bug

There is an extra } at the end of line 58 in this file. (good-first-issue) :-)   This is causing the existing reference to fail during deployment.

### To reproduce

Use the module.

**Comment by AlexanderSehr** [comment]
Hey @akata72, thanks for sharing. By any chance, do you have a reference? 

If I check in current main it looks like this: 
https://github.com/Azure/ResourceModules/blob/369cfb4155fff8b197e235b6c150460ae687c118/modules/Microsoft.EventHub/namespaces/.bicep/nested_roleAssignments.bicep#L57-L59

Hence I'm a bit confused ;)

**Comment by akata72** [comment]
Hm..you are right. Looks like this was fixed at some point. Must be an issue with our fork (not being updated).

**Comment by AlexanderSehr** [comment]
No no @akata72, you're absolutely right. I was looking into the `namespaces/nested_roleassignments.bicep`, but you were referring to the `eventhubs` child module. There it IS actually wrong.
