### ISSUE TITLE
[Bug Report]: module path are not all updated to remove 'microsoft.' prefix in the folder names

### ISSUE THREAD

**Issue by tyconsulting** [Azure/ResourceModules#3192]
### Describe the bug

after the `'microsoft.` prefix was removed from all the top level folders, some modules are still referencing other modules with the name name. for example this is in the [ADF module](https://github.com/Azure/ResourceModules/blob/main/modules/DataFactory/factories/main.bicep#L275): 
![image](https://github.com/Azure/ResourceModules/assets/11845994/c591cdcf-f750-4ac6-9321-97a494f9068b)

### To reproduce

n/a

**Comment by eriqua** [comment]
Hey @tyconsulting, good catch ;)
This was introduced by part 1 of 2 PRs and will be addressed by #3189

**Comment by AlexanderSehr** [comment]
Also note the disclaimer on the [home page](https://github.com/Azure/ResourceModules#upcoming-breaking-changes). We're working through the changes as quickly as possible.

**Comment by AlexanderSehr** [comment]
@tyconsulting, we now merged also the 2nd PR and will now try to quickly fix any unexpected issue (e.g. the font page table + publishing). Note that there is at least one more major breaking change coming - as part of #3132 we have to push through.

If you encounter any further issues, please let us know. These breaking changes are very nasty.
