### ISSUE TITLE
[Bug Report]: Documentation not displaying (404)

### ISSUE THREAD

**Issue by annduda** [Azure/ResourceModules#3195]
### Describe the bug

Hi,

I was trying to have a look at module documentation and the link is not working displaying 404 file not found. It is happening for all the resources.

![image](https://github.com/Azure/ResourceModules/assets/95341017/3b5b87b9-062f-4b97-a247-d6e4190dab86)

### To reproduce

Click on any module from 

![image](https://github.com/Azure/ResourceModules/assets/95341017/38dc82cc-9adf-4a0d-bde1-75a62073df6c)

**Comment by AlexanderSehr** [comment]
Hey @annaduda, it should be fixed now :)
