### ISSUE TITLE
[Feature Request]: Create a new module for Service Endpoint Policy

### ISSUE THREAD

**Issue by tyconsulting** [Azure/ResourceModules#3244]
### Description

create a new module for `Microsoft.Network/serviceEndpointPolicies`

**Comment by tyconsulting** [comment]
Can someone please assign this to me? I already have the code for it

**Comment by tyconsulting** [comment]
PR Raised #3289

**Comment by AlexanderSehr** [comment]
Closing as linked PR was merged
