### ISSUE TITLE
[Feature Request]:  modules/web/sites/main.bicep  this module not allowing us to create apiapps (kind: 'api') 

### ISSUE THREAD

**Issue by venkatmamillapalli** [Azure/ResourceModules#3274]
### Description

We are trying to create apiapp (kind:'api') using this carml repo but it is  allowing us to create webapps,functionapps,logic apps only is there a way to create apiapp using this carml bicep modules.

Thanks,
Venkat

**Comment by AlexanderSehr** [comment]
Hey @venkatmamillapalli,
I just checked and in the current version of the module, there is quite a wide set of supported types :) You can find it (and being publish to the Public Bicep Registry) [here](https://github.com/Azure/bicep-registry-modules/blob/4116228208bd6d1f2cc21fa0fe1f82eaddd05c9f/avm/res/web/site/main.bicep#L13-L23).
