### ISSUE TITLE
[Feature Request]: Subscription module

### ISSUE THREAD

**Issue by annduda** [Azure/ResourceModules#3278]
### Description

Hi,

Hope I am not missing something but could we add module for subscription using:

resource alias 'Microsoft.Subscription/aliases@2021-10-01' = {}? 

I do not see it right now on the list of the modules

**Comment by eriqua** [comment]
Hello @annduda , thanks for opening the issue.

We currently have a blocker to continuously test this module in the validation environment. Please see issue https://github.com/Azure/ResourceModules/issues/868 and related draft PR https://github.com/Azure/ResourceModules/pull/1094.

In the meantime, you can check if the implementation in branch https://github.com/Azure/ResourceModules/tree/users/alsehr/868_alias/arm/Microsoft.Subscription/aliases is useful for you.

However, please also consider that the implementation is not aligned with the breaking changes developed to align with the PBR module structure (Ref issue #3131 ). Those changes are being worked on in main as we speak and not yet released.

**Comment by annduda** [comment]
Thanks Erika this was very helpful!

**Comment by rahalan** [comment]
Please have a look at https://github.com/Azure/bicep-lz-vending#bicep-landing-zone-vending-module-for-azure . That may solve your problem.
