### ISSUE TITLE
[Feature Request from Discussions] Automation account module don't pass all parameters for runbooks

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#3291]
### Discussed in https://github.com/Azure/ResourceModules/discussions/3282

<div type='discussions-op-text'>

<sup>Originally posted by **dibcar** May 27, 2023</sup>
Hi, 
Is there a reason why the automation account module don't pass every parameter to the runbook sub module ? The parameters scriptStorageAccountId and sasTokenValidityLenght are not passed to the runbook module.

Thanks,</div>

**Comment by AlexanderSehr** [comment]
This used to be a very nasty bug in the original module that was thankfully fixed in the meantime. The latest version can be found here: https://github.com/Azure/bicep-registry-modules/blob/86cfa8621eec707cba22912affb179b641960b92/avm/res/automation/automation-account/main.bicep#L238-L239

**Comment by AlexanderSehr** [comment]
Closing as per previous comment
