### ISSUE TITLE
[Feature Request]: Add CARML support for Hybrid Connections

### ISSUE THREAD

**Issue by jeremytbrun** [Azure/ResourceModules#3303]
### Description

Requesting the modules and submodules to support creating Hybrid Connections with Microsoft.Relay/namespaces/hybridConnections and the ability to link applications to them with Microsoft.Web/sites/hybridConnectionNamespaces/relays.

**Comment by rahalan** [comment]
@jeremytbrun Thanks for hinting it out. Do you have the bandwidth to work on that feature?

**Comment by jeremytbrun** [comment]
Yup, PR submitted and ready for review.
