### ISSUE TITLE
'Publish' 'changed' child-resources 

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#331]
For modules that align with the child-resource structure (i.e. use child-templates #236) we want to make sure the child-templates (e.g. `container/deploy.bicep`) are published the same way as their corresponding parent template is.

However, for that to work we have to make sure only templates that actually changed are included in the publish - not the entire module tree (i.e. parent + all rescursive children).

**Comment by MariusStorhaug** [comment]
Change to arm/<resourceProvider>/<resourceType>/<childResource> should publish new version of itself (only).
What is there is a major/minor change. Should parents also be updated with new version?
