### ISSUE TITLE
[Feature Request]: Module readme tables - show resourceType instead of module name

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#3316]
### Description

Show actual provider namespace and resource type instead of module name (kebab-case) in module readme tables. This is for
- the root README shown in the repo homepage
- the modules README
- the wiki module overview

**Comment by AlexanderSehr** [comment]
We decided to
- Revert the ProviderNamespace & ResourceType back to their original name in the table
- Leave the rest as is
