### ISSUE TITLE
[Feature Request]: Replace all .json parameter files with .jsonc

### ISSUE THREAD

**Issue by FallenHoot** [Azure/ResourceModules#3321]
### Description

BICEP accepts .jsonc ([JSON with Comments](https://code.visualstudio.com/Docs/languages/json#_json-with-comments)) 

This will allow the example parameter with // to work without the need to edit them. 

-- https://github.com/Azure/bicep/issues/10623

**Comment by lsnoddy** [comment]
https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files?tabs=Bicep

Bicep is also supporting Bicep parameter files, however as per the CARML libary we are currently working on aligning with the Bicep Public Registry for testing module structures. Therefore, we aren't planning to implement support for .jsonc files at this time.
