### ISSUE TITLE
[Bug Report]: PostgreSQL Flexible server configuration concurrent deployment will fail

### ISSUE THREAD

**Issue by tyconsulting** [Azure/ResourceModules#3324]
### Describe the bug

when there are more than 1 configurations specified for the PostgreSQL Flexible servers, the deployment will fail because the configurations are deployed at the same time.

### To reproduce

Passing in multiple configurations. i.e.

```json
    "postgreSqlConfigurations": {
      "value": [
        {
          "name": "require_secure_transport",
          "source": "user-override",
          "value": "OFF"
        },
        {
          "name": "connection_throttle.enable",
          "source": "user-override",
          "value": "ON"
        }
      ]
    }
```
You will get error:
![image](https://github.com/Azure/ResourceModules/assets/11845994/b4d85822-c359-4e5e-a37c-c3785f554dd4)

**Comment by rahalan** [comment]
Looks like it needs to be deployed in a serial manner using the batch command.
