### ISSUE TITLE
[Bug Report]: Resource imageTemplate's 'name' identifier is potentially nondeterministic due to its use of the 'utcNow' function

### ISSUE THREAD

**Issue by FallenHoot** [Azure/ResourceModules#3330]
### Describe the bug

When running Image Templates - The module throws errors about the image name having UTC. 

The fix is simply by removing the UTC and if needed the unnecessary string interpolation "'${name}'"

![image](https://github.com/Azure/ResourceModules/assets/19664186/6607199f-3240-45b3-b995-0d9ec25d01cd)

### To reproduce

Configure and run [Image Templates Module](https://github.com/Azure/ResourceModules/tree/main/modules/virtual-machine-images/image-templates) 

### Code snippet
Line 168-169:
```Bicep
resource imageTemplate 'Microsoft.VirtualMachineImages/imageTemplates@2022-02-14' = {
  name: '${name}-${baseTime}'
```
```

Example of the fix:
```Bicep
resource imageTemplate 'Microsoft.VirtualMachineImages/imageTemplates@2022-02-14' = {
  name: name
```
```

### Relevant log output

```Shell
Error: WARNING: /home/runner/work/azure_image_builder/azure_image_builder/carml/0.10.0/modules/Microsoft.VirtualMachineImages/imageTemplates/deploy.bicep(169,9) : Warning use-stable-resource-identifiers: Resource identifiers should be reproducible outside of their initial deployment context. Resource imageTemplate's 'name' identifier is potentially nondeterministic due to its use of the 'utcNow' function (imageTemplate.name -> baseTime (default value) -> utcNow('yyyy-MM-dd-HH-mm-ss')). [https://aka.ms/bicep/linter/use-stable-resource-identifiers]
```

**Comment by AlexanderSehr** [comment]
Hey @FallenHoot,
please note that it's actually a warning you're seeing, not an error (the error was unrelated).
The reason the base time was added to the name was because the image template resource is not idempotent. So you don't have much of a choice unfortuantely. Bicep however has a general recommendation for deterministic names and does not have a built-in exception for this resource type.
