### ISSUE TITLE
[Bug Report]: ACR version 0 already exists.

### ISSUE THREAD

**Issue by mpr555** [Azure/ResourceModules#3339]
### Describe the bug

After the initial creation of the module in azure container registry it errors when trying to push to version 0.  It wants a --force flag on it.

it does create a new number and push that.

### To reproduce

updated a module in my own project in Azure DevOps.  Imported yesterday fresh from this main github repo.

### Relevant log output

```Shell
VERBOSE: Performing the operation "Publish" on target "Private bicep registry entry [bicep/modules/compute.galleries.images] version [0] to registry [xxx]".
The module "br:xxx/bicep/modules/compute.galleries.images:0" already exists in registry. Use --force to overwrite the existing module.
VERBOSE: Publish complete
##[error]Script failed with exit code: 1
/usr/bin/az account clear
Finishing: Publish module to private bicep registry
```

**Comment by rahalan** [comment]
Needs investigation
