### ISSUE TITLE
[Bug Report]: Publishing of 'latest' versions is affected by cmdlet default behavior change

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#3383]
### Describe the bug

When scanning some [pipeline logs](https://github.com/Azure/ResourceModules/actions/runs/5405171554/jobs/9820722147#step:4:718) - I found the following warning: `The module "br:adpsxxazacrx001.azurecr.io/bicep/modules/web.sites.slots.hybrid-connection-namespaces.relays:0.1" already exists in registry. Use --force to overwrite the existing module.` 

It appears the default behavior of the publishing cmdlet changed and we need to append a `--force` parameter to re-establish the desired behavior. 

A small fix, but important.

### To reproduce

Run a pipeline that publishes.

**Comment by eriqua** [comment]
Also related to #3339
