### ISSUE TITLE
[Bug Report]: EventHub role assignment name not unique across EventHub namespaces and EventHub

### ISSUE THREAD

**Issue by sebbrochet** [Azure/ResourceModules#3439]
### Describe the bug

Hello,

if you apply the same kind of role assignments to 2 EventHubs from the same namespace, you'll bump into an error such as:

"Azure Deployment Error “Tenant ID, application ID, principal ID, and scope are not allowed to be updated".

It comes from the fact there's a bug when the **name** of the azure role assignment is forged in https://github.com/Azure/ResourceModules/blob/main/modules/event-hub/namespaces/eventhubs/.bicep/nested_roleAssignments.bicep

```
resource eventHub 'Microsoft.EventHub/namespaces/eventhubs@2022-01-01-preview' existing = {
  name: '${split(resourceId, '/')[8]}/${split(resourceId, '/')[10]}'
}

resource roleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = [for principalId in principalIds: {
  name: guid(split(resourceId, '/')[0], split(resourceId, '/')[1], principalId, roleDefinitionIdOrName)
```

That should be aligned as:

```
resource eventHub 'Microsoft.EventHub/namespaces/eventhubs@2022-01-01-preview' existing = {
  name: '${split(resourceId, '/')[8]}/${split(resourceId, '/')[10]}'
}

resource roleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = [for principalId in principalIds: {
  name: guid(split(resourceId, '/')[8], split(resourceId, '/')[10], principalId, roleDefinitionIdOrName)
```

### To reproduce

Apply the same kind of role assignments to 2 EventHubs from the same namespace

### Relevant log output

```Shell
"Azure Deployment Error “Tenant ID, application ID, principal ID, and scope are not allowed to be updated".
```

**Comment by AlexanderSehr** [comment]
Hey @sebbrochet,

good catch. I'd suggest to apply the approach we're also using for, for example, the Key Vault Secrets Role Assignments:

```Bicep
resource secret 'Microsoft.KeyVault/vaults/secrets@2022-07-01' existing = {
  name: '${split(resourceId, '/')[8]}/${split(resourceId, '/')[10]}'
}

resource roleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = [for principalId in principalIds: {
  name: guid(secret.id, principalId, roleDefinitionIdOrName)
  (..)
}
```

In other words: No split whatsoever in the Role Assignment name, but instead the full resource ID.
