### ISSUE TITLE
Trying to create an Express Route Gateway getting SKU error

### ISSUE THREAD

**Issue by jceval** [Azure/ResourceModules#349]
https://github.com/Azure/ResourceModules/blob/39d270089f4b8c504b80ef30599d6efe17781434/arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep#L347

Passing the following parameters to the module and receiving an error related to the SKU used.

```
module networkEGW '../../../arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep' = if (networkObject.peeredToHub==false) {
  name: 'networkEGW-${location}-${env}-${nameSuffix}'
  scope: resourceGroup(networkObject.subscriptionId, resourceGroupName)
  params: {
    virtualNetworkGatewayName: 'egw-${location}-${env}-${nameSuffix}'
    virtualNetworkGatewayType: 'ExpressRoute'
    virtualNetworkGatewaySku: 'ErGw1AZ'
    vNetId: networkVNET.outputs.virtualNetworkResourceId
    activeActive: false
    publicIpZones: []
  }

  dependsOn: [
    networkRG
    networkVNET
  ]
}
```

Error :  The deployed SKU is in the allowed SKU list in the error. Resource should be deploying with Standard Static PIP and Express Route Gateway Type , ErGw1AZ SKU , and no availability zone configuration since not available in canada east. 
```
{
    "status": "Failed",
    "error": {
        "code": "InvalidGatewaySkuSpecifiedForGatewayDeploymentType",
        "message": "Virtual network gateway Sku specified is not valid for gateway /subscriptions/<sub_id>/resourceGroups/rg-network-canadaeast-prod-connectivity/providers/Microsoft.Network/virtualNetworkGateways/egw-canadaeast-prod-connectivity with DeploymentType VMScaleSet. The allowed Skus are ErGw1AZ,ErGw2AZ,ErGw3AZ.",
        "details": []
    }
}
```

**Comment by jceval** [comment]
Similar to this thread : https://github.com/hashicorp/terraform-provider-azurerm/issues/9892

**Comment by ahmadabdalla** [comment]
@jceval For Canada East, as it doesn't support AZs yet, the parameters should deploy using either the (Standard, HighPerformance, UltraPerformance) SKUs. I've added them to the allowed list and this will convert the PIP to Basic and Dynamic as well.
