### ISSUE TITLE
[Bug Report]: Agent scheduled updates gives error 404 after deploying AVD host pool with host-pools module

### ISSUE THREAD

**Issue by ThojoUno** [Azure/ResourceModules#3523]
### Describe the bug

Default deployment of host pool using CARML host-pools module causes 404 error when accessing Agent scheduled updates. I have confirmed this is caused by an incomplete agentUpdate object in the main.bicep

@sys.description('Optional. The session host configuration for updating agent, monitoring agent, and stack component.')
param agentUpdate object = {
  useSessionHostLocalTime: true
}

### To reproduce

This can be reproduced by either deploying a "common" or "minimum" deployment of the host-pools module.

### Code snippet

```Bicep
@sys.description('Optional. The session host configuration for updating agent, monitoring agent, and stack component.')
param agentUpdate object = {
  useSessionHostLocalTime: true
}
```

**Comment by ThojoUno** [comment]
this can be resolved by updating the hosts-pools/main.bicep as follows. 

@sys.description('Optional. Enable scheduled agent updates, Default means agent updates will automatically be installed by AVD when they become available.')
@allowed([
  'Default'
  'Scheduled'
])
param agentUpdateType string = 'Default'

@sys.description('Optional. Update hour for scheduled agent updates.')
@minValue(1)
@maxValue(23)
param agentUpdateMaintenanceWindowHour int = 22

@sys.description('Optional. Update day for scheduled agent updates.')
@allowed([
  'Sunday'
  'Monday'
  'Tuesday'
  'Wednesday'
  'Thursday'
  'Friday'
  'Saturday'
])
param agentUpdateMaintenanceWindowDayOfWeek string = 'Sunday'

@sys.description('Optional. List of maintenance windows for scheduled agent updates.')
param agentUpdateMaintenanceWindows array = [
  {
    hour: agentUpdateMaintenanceWindowHour
    dayOfWeek: agentUpdateMaintenanceWindowDayOfWeek
  }
]

@sys.description('Optional. Time zone for scheduled agent updates.')
param agentUpdateMaintenanceWindowTimeZone string = 'Central Standard Time'

@sys.description('Optional. Whether to use localTime of the virtual machine for scheduled agent updates.')
param agentUpdateUseSessionHostLocalTime bool = false

@sys.description('Optional. The session host configuration for updating agent, monitoring agent, and stack component.')
param agentUpdate object = {
  type: agentUpdateType
  maintenanceWindows: agentUpdateMaintenanceWindows
  maintenanceWindowTimeZone: agentUpdateMaintenanceWindowTimeZone
  useSessionHostLocalTime: agentUpdateUseSessionHostLocalTime
}

**Comment by MaxValue** [comment]
Hello there!
