### ISSUE TITLE
[Feature Request]: Bicep module for Microsoft.Dashboard grafana

### ISSUE THREAD

**Issue by aadev1** [Azure/ResourceModules#3584]
### Description

Request for Bicep module for creating 'Azure Managed Grafana'.  We are currently utilising Bicep modules from this repository but can't seem to find one for 'Azure Managed Grafana' (Microsoft.Dashboard/grafana)

https://learn.microsoft.com/en-us/azure/templates/microsoft.dashboard/2022-08-01/grafana?pivots=deployment-language-bicep

**Comment by AlexanderSehr** [comment]
Hey @aadev1, the library is the result of contributions by the community and hence cannot claim completeness. However, it is an absolute fair ask and I'll add it to the backlog 👍
If you happen to implement the module on your end before we do, we'd appreciate the contribution 💪

**Comment by AlexanderSehr** [comment]
Hey @aadev1,
given the migration to AVM, I suggest to open an AVM module proposal for this given the completed migration. You can find the issue template [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose). As we're trying to move all issues to the corresponding location / have them triaged I'll go ahead and close this issue for this repository.
