### ISSUE TITLE
Create/Generate `Deploy to Azure` Button

### ISSUE THREAD

**Issue by segraef** [Azure/ResourceModules#36]
## Code

```markdown
[![Deploy to Azure](/docs/media/deploytoazure.svg?sanitize=true)](<https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FModules%2Fmain%2Farm%2FMicrosoft.AnalysisServices%2Fservers%2Fdeploy.json>)

[![Deploy To Azure US Gov](/docs/media/deploytoazuregov.svg?sanitize=true)](<https://portal.azure.us/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FModules%2Fmain%2Farm%2FMicrosoft.AnalysisServices%2Fservers%2Fdeploy.json>)

[![Visualize](/docs/media/visualizebutton.svg?sanitize=true)](<http://armviz.io/#/?load=https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FModules%2Fmain%2Farm%2FMicrosoft.AnalysisServices%2Fservers%2Fdeploy.json>)
```

[![Deploy to Azure](https://raw.githubusercontent.com/Azure/Modules/main/docs/media/deploytoazure.svg?sanitize=true)](<https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FModules%2Fmain%2Farm%2FMicrosoft.AnalysisServices%2Fservers%2Fdeploy.json>)

[![Deploy To Azure US Gov](https://raw.githubusercontent.com/Azure/Modules/main/docs/media/deploytoazuregov.svg?sanitize=true)](<https://portal.azure.us/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FModules%2Fmain%2Farm%2FMicrosoft.AnalysisServices%2Fservers%2Fdeploy.json>)

[![Visualize](https://raw.githubusercontent.com/Azure/Modules/main/docs/media/visualizebutton.svg?sanitize=true)](<http://armviz.io/#/?load=https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FModules%2Fmain%2Farm%2FMicrosoft.AnalysisServices%2Fservers%2Fdeploy.json>)

## References 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button
https://devblogs.microsoft.com/cse/2017/01/17/the-deploy-to-azure-button/
https://medium.com/@codeprincess/get-your-own-azure-button-now-8d79b1811061

**Comment by segraef** [comment]
azuredeploy.net is no option since it only accepts azuredeploy.json and parameters.json in the root.

**Comment by MrMCake** [comment]
done
