### ISSUE TITLE
UX: Advanced Portal Deployments with createUiDefinition.json

### ISSUE THREAD

**Issue by segraef** [Azure/ResourceModules#37]
## References

UI Definition Sandbox: https://portal.azure.com/?feature.customPortal=false&#blade/Microsoft_Azure_CreateUIDef/SandboxBlade

[createUiDefinition Overview](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/create-uidefinition-overview)

[createUiDefinition UI elements reference](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/create-uidefinition-elements)

[testing createUiDefinition](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/test-createuidefinition)

**Comment by MrMCake** [comment]
Blocked as Bicep is not supported in UI
