### ISSUE TITLE
[Feature Request]: Add module for Machine Learning Registry (Microsoft.MachineLearningServices/registries)

### ISSUE THREAD

**Issue by krbar** [Azure/ResourceModules#3779]
### Description

Add missing module for Machine Learning Registry (Microsoft.MachineLearningServices/registries)
Template reference: https://learn.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/registries?pivots=deployment-language-bicep

**Comment by AlexanderSehr** [comment]
Hey @krbar - I guess this should be closed and re-opened as a module proposal in AVM?

**Comment by krbar** [comment]
Yes, let's close it here
