### ISSUE TITLE
[Bug Report]: The workflow `.Platform: Update ReadMe Module Tables` fails

### ISSUE THREAD

**Issue by krbar** [Azure/ResourceModules#3872]
### Describe the bug

The workflow `.Platform: Update ReadMe Module Tables` (https://github.com/Azure/ResourceModules/actions/workflows/platform.updateReadMe.yml) fails. 

### To reproduce

Run https://github.com/Azure/ResourceModules/actions/workflows/platform.updateReadMe.yml

**Comment by AlexanderSehr** [comment]
Fixed by commit ['Fixed logic by introducing api name fetching'](https://github.com/Azure/ResourceModules/commit/ac4927c59b96d383e13704323bbe9d3cc0f06fe3).
