### ISSUE TITLE
[Bug Report]: The workflow `.Platform: Broken Links Check` fails on each run

### ISSUE THREAD

**Issue by krbar** [Azure/ResourceModules#3874]
### Describe the bug

The platform workflow `.Platform: Broken Links Check` fails on each run.

### To reproduce

Run https://github.com/Azure/ResourceModules/actions/workflows/platform.linkcheck.yml

**Comment by AlexanderSehr** [comment]
The errors are persistently:

> ### Errors in modules/document-db/database-account/mongodb-database/README.md
> * [ERR] [file:///home/runner/work/ResourceModules/ResourceModules/modules/document-db/database-account/mongodb-database/collections/README.md](file:///home/runner/work/ResourceModules/ResourceModules/modules/document-db/database-account/mongodb-database/collections/README.md) | Failed: Cannot find file

> ### Errors in modules/operational-insights/workspace/README.md
> * [ERR] [file:///home/runner/work/ResourceModules/ResourceModules/modules/operations-management/solutions/README.md](file:///home/runner/work/ResourceModules/ResourceModules/modules/operations-management/solutions/README.md) | Failed: Cannot find file

> ### Errors in modules/document-db/database-account/README.md
> * [ERR] [file:///home/runner/work/ResourceModules/ResourceModules/modules/document-db/database-account/gremlin-databases/README.md](file:///home/runner/work/ResourceModules/ResourceModules/modules/document-db/database-account/gremlin-databases/README.md) | Failed: Cannot find file
> * [ERR] [file:///home/runner/work/ResourceModules/ResourceModules/modules/document-db/database-account/mongodb-databases/README.md](file:///home/runner/work/ResourceModules/ResourceModules/modules/document-db/database-account/mongodb-databases/README.md) | Failed: Cannot find file

> ### Errors in modules/network/virtual-network/README.md
> * [ERR] [file:///home/runner/work/ResourceModules/ResourceModules/modules/network/virtual-network/subnets/README.md](file:///home/runner/work/ResourceModules/ResourceModules/modules/network/virtual-network/subnets/README.md) | Failed: Cannot find file
> * [ERR] [file:///home/runner/work/ResourceModules/ResourceModules/modules/network/virtual-network/virtual-network-peerings/README.md](file:///home/runner/work/ResourceModules/ResourceModules/modules/network/virtual-network/virtual-network-peerings/README.md) | Failed: Cannot find file

To me it is unclear why those are an issue (the paths are simply correct, they still show the plural) and consequently, where the action gets the incorrect paths from. I don't see a way to configure anything related. Maybe from a branch? But then it should affect all files.

**Comment by AlexanderSehr** [comment]
Fixed. The issue was related to embedded child-module readme references.
