### ISSUE TITLE
[Feature Request]: AAD authentication for MySQL missing

### ISSUE THREAD

**Issue by mschwit** [Azure/ResourceModules#3948]
### Description

I want to enable AAD authentication only and add AAD admins to the MySQL flexibleServers. This is currently not included.
Please make administratorLogin and administratorLoginPassword parameters optional as I want to set AAD authentication only. And a new parameter to pass AAD administrators.

**Comment by mschwit** [comment]
@ahmadabdalla , @AlexanderSehr
Thanks for implementing the feature request

**Comment by ahmadabdalla** [comment]
You're most welcome :)
