### ISSUE TITLE
Improve test files to cover more test cases

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#401]
- create for each module min, max and scenario parameter files to cover more testcases and test the deployment of every module aspect

- add checklist to PR template, to maintain parameter files (if new parameter is added)

**Comment by rahalan** [comment]
Split the issue into issues per namespace

**Comment by jontreynes** [comment]
I'm updating just the Azurefirewall one right now while I was updating it here #1328

**Comment by AlexanderSehr** [comment]
As modules are moved and partly enforced in AVM, closing this
