### ISSUE TITLE
[Feature Request]: Diagnostic Settings do not support resource specific Log Analytics tables

### ISSUE THREAD

**Issue by tyconsulting** [Azure/ResourceModules#4010]
### Description

Currently the diagnostic settings in the CARML modules do not support the [resource specific destination tables](https://learn.microsoft.com/en-au/azure/azure-monitor/essentials/resource-logs#resource-specific) feature for the applicable resources (i.e. RSV, AKS, ADF, Key Vault, etc.)

**Comment by AlexanderSehr** [comment]
Hey @tyconsulting,
I checked with @ahmadabdalla, and if I understand it correctly, the request is about the `logAnalyticsDestinationType` parameter, correct?
If so, we'll soon enable this by updating all CAMRL modules as per the Azure Verified Modules (AVM) specs defined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#diagnostic-settings).
