### ISSUE TITLE
[Bug Report]: Pester test Bicep test deployment files should invoke test like [`module testDeployment '../.*main.bicep' does not support for loop

### ISSUE THREAD

**Issue by tyconsulting** [Azure/ResourceModules#4018]
### Describe the bug

the Pester test [Bicep test deployment files should invoke test like [`module testDeployment '../.*main.bicep'](https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/staticValidation/module.tests.ps1#L1320C34-L1320C127) does not support for loop in the regex

### To reproduce

this Pester test will fail if my module deployment test is defined like this:

```bicep
module testDeployment '../../main.bicep' = [for (definition, i) in PolicyDefinitions: {
  xxxx
}]
```

**Comment by AlexanderSehr** [comment]
Hey @tyconsulting, thanks for the issue.
That should be relatively easy to fix by updating the regex. I'll move it into todo. Thanks :)
