### ISSUE TITLE
[Feature Request]: Bump API version and add additional parameters for Insights.PrivateLinkScopes

### ISSUE THREAD

**Issue by akata72** [Azure/ResourceModules#4035]
### Description

Please bump the API version (->2021-07-01-preview) of the microsoft.insights/privatelinkscopes and add support for the new properties. 

 ```
properties: {
    accessModeSettings: {
      exclusions: []
      queryAccessMode: 'Open'
      ingestionAccessMode: 'Open'
    }
  }
```

**Comment by johnlokerse** [comment]
@AlexanderSher Please assign me to this issue. I need this in my solution too. 😄

**Comment by johnlokerse** [comment]
@AlexanderSehr Please assign me to this issue. I need this in my solution too. 😄

**Comment by AlexanderSehr** [comment]
Resolved through linked PR
