### ISSUE TITLE
Align `network/public-ip-address` to AVM specs

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#4043]

**Comment by ChrisSidebotham** [comment]
PR Opened in AVM https://github.com/Azure/bicep-registry-modules/pull/554

**Comment by ChrisSidebotham** [comment]
This module has already been migrated to [AVM](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res). Only the AVM version is expected to receive updates / new features. Please do not work on improving this module in [CARML](https://aka.ms/carml).
