### ISSUE TITLE
[Feature Request]:  'Microsoft.Consumption/budgets@2021-10-01' does not support scope on resource group

### ISSUE THREAD

**Issue by Jackmt9** [Azure/ResourceModules#4170]
### Description

'Microsoft.Consumption/budgets@2021-10-01' should be able to support the creation of a budget on a resource group. Currently, it only allows the scope of subscription().

**Comment by AlexanderSehr** [comment]
Hey @Jackmt9, thank you for your issue. Please not that I ported it over to the Public Bicep Registry repository [issues](https://github.com/Azure/bicep-registry-modules/issues/859) and would close this feature in favor of tracking the issue there. We're currently migrating the library and Budgets was already moved :)
