### ISSUE TITLE
[Feature Request]: Nested User Defined Types to show up in the readme

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#4174]
### Description

Currently the readme that is generated for user defined types is that it supports 1 level for exposing the properties in the readme.

For example: if a UDT contains (A, B) properties, then the readme will expose A and B separately in the readme. Which is great.

However, if the UDT contains (A, B (B1, B2)) .. then (B.B1) and (B.B2) will not be shown in the readme.

Ideally we should be able to drill down in the nesting so that the guidance is clear for nested properties as well.

**Comment by AlexanderSehr** [comment]
Example:
![image](https://github.com/Azure/ResourceModules/assets/5365358/cbbead13-f058-4a09-93b2-63feda42a102)

[source](https://github.com/Azure/ResourceModules/pull/4167/files#diff-4c53c594e9b2cb645a95898e892a82f36c267a127df84515da6fdfeaa9a1ee80)
