### ISSUE TITLE
Security: Implement script that checks modules for compliance

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#418]
Next to the check of all modules for security compliance (#351) the idea was expressed to have one central configuration for 'compliance' rules for our resource types and implement a script that checks our modules against this set of rules.
This would give customers and their security teams a tool at hand to quickly check what the rules are we apply, add/set their own rules and check the modules themselves.

**Comment by rahalan** [comment]
Needs more scoping and better definition around the rule set

**Comment by MrMCake** [comment]
We won't be able to implement this in the forseeable future
