### ISSUE TITLE
[Feature Request]: Update modules not having a `e2e/defaults` and/or a `e2e/waf-aligned` test

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#4185]
## List of modules not having a `e2e/defaults` test
This list may include both the following:

1. modules not having a defaults (previously min) test
2. modules having multiple defaults test based on the scenario (e.g., compute\virtual-machine has defaults for both linux and windows)

In the first case, the default test should be added
In the second case, `*min` should be renamed to `*defaults`
>Example `modules\compute\virtual-machine\tests\e2e\linux.min` should be `modules\compute\virtual-machine\tests\e2e\linux.defaults`

- aad\domain-service
- authorization\lock
- authorization\policy-assignment
- authorization\policy-definition
- authorization\policy-exemption
- authorization\policy-set-definition
- authorization\role-assignment
- authorization\role-definition
- cdn\profile
- compute\disk-encryption-set
- compute\image
- compute\virtual-machine
- compute\virtual-machine-scale-set
- document-db\database-account
- insights\activity-log-alert
- insights\diagnostic-setting
- insights\metric-alert
- insights\scheduled-query-rule
- logic\workflow
- managed-services\registration-definition
- network\application-gateway
- network\application-gateway-web-application-firewall-policy
- network\application-security-group
- network\connection
- network\dns-resolver
- network\nat-gateway
- network\network-manager
- network\virtual-network-gateway
- policy-insights\remediation
- resources\deployment-script
- security\azure-security-center
- sql\server
- web\connection
- web\hosting-environment
- web\serverfarm
- web\site

## List of modules not having a `e2e/common` test

This list includes modules having multiple tests based on the scenario (e.g., compute\virtual-machine has a common test for both linux and windows)

In this case the common test should be renamed to `*max` and the value of the `serviceShort` parameter in main.test.bicep should be renamed from `*com` to `*max`
> Example: `modules\compute\virtual-machine\tests\e2e\linux` should be `modules\compute\virtual-machine\tests\e2e\linux.max`. 

Also, a waf-aligned test should be created by duplicating the max folder, naming it `*waf-aligned` and the value of the `serviceShort` parameter in main.test.bicep should be renamed from `*max` to `*waf`

- authorization\policy-assignment
- authorization\policy-definition
- authorization\policy-exemption
- authorization\policy-set-definition
- authorization\role-assignment
- authorization\role-definition
- compute\virtual-machine
- compute\virtual-machine-scale-set
- container-service\managed-cluster
- db-for-my-sql\flexible-server
- db-for-postgre-sql\flexible-server
- document-db\database-account
- insights\data-collection-rule
- net-app\net-app-account
- network\connection
- network\virtual-network-gateway
- operations-management\solution
- policy-insights\remediation
- resources\deployment-script
- resources\tags
- web\hosting-environment
- web\site

# Edit - Combined:
@AlexanderSehr

| Missing default | Missing common |
| - | - |
|	aad\domain-service	|		|
|	authorization\lock	|		|
|	authorization\policy-assignment	|	authorization\policy-assignment	|
|	authorization\policy-definition	|	authorization\policy-definition	|
|	authorization\policy-exemption	|	authorization\policy-exemption	|
|	authorization\policy-set-definition	|	authorization\policy-set-definition	|
|	authorization\role-assignment	|	authorization\role-assignment	|
|	authorization\role-definition	|	authorization\role-definition	|
|	cdn\profile	|		|
|	compute\disk-encryption-set	|		|
|	compute\image	|		|
|	compute\virtual-machine	|	compute\virtual-machine	|
|	compute\virtual-machine-scale-set	|	compute\virtual-machine-scale-set	|
|	document-db\database-account	|	document-db\database-account	|
|	insights\activity-log-alert	|		|
|	insights\diagnostic-setting	|		|
|	insights\metric-alert	|		|
|	insights\scheduled-query-rule	|		|
|	logic\workflow	|		|
|	managed-services\registration-definition	|		|
|	network\application-gateway	|		|
|	network\application-gateway-web-application-firewall-policy	|		|
|	network\application-security-group	|		|
|	network\connection	|	network\connection	|
|	network\dns-resolver	|		|
|	network\nat-gateway	|		|
|	network\network-manager	|		|
|	network\virtual-network-gateway	|	network\virtual-network-gateway	|
|	policy-insights\remediation	|	policy-insights\remediation	|
|	resources\deployment-script	|	resources\deployment-script	|
|	security\azure-security-center	|		|
|	sql\server	|		|
|	web\connection	|		|
|	web\hosting-environment	|	web\hosting-environment	|
|	web\serverfarm	|		|
|	web\site	|	web\site	|
|		|	resources\tags	|
|		|	operations-management\solution	|
|		|	net-app\net-app-account	|
|		|	container-service\managed-cluster	|
|		|	db-for-my-sql\flexible-server	|
|		|	db-for-postgre-sql\flexible-server	|
|		|	insights\data-collection-rule	|

**Comment by eriqua** [comment]
```powershell
$testPaths=(Get-ChildItem -Filter 'e2e' -Directory -Recurse).FullName
$missingMin = @()
$missingCommon = @()
foreach ($testPath in $testPaths){
	$childTestFolders = Get-ChildItem $testPath
	
	if (-not ($childTestFolders.Name -contains 'defaults' )) {
		$missingMin+=$testPath
	}
	
	if (-not ($childTestFolders.Name -contains 'common' )) {
		$missingCommon+=$testPath
	}
}
```

**Comment by eriqua** [comment]
Current count of tests folder (= count of parent level modules) : 137
Current count of max folder : 115
Current count of defaults folder : 101

Missing max folders: 22
Missing defaults folders: 36

```powershell
$missingDefaultsFolderPaths = (Get-ChildItem -Filter 'e2e' -Directory -Recurse).count - (Get-ChildItem -Filter 'defaults' -Directory -Recurse).count
$missingMaxFolderPaths = (Get-ChildItem -Filter 'e2e' -Directory -Recurse).count -(Get-ChildItem -Filter 'max' -Directory -Recurse).count
```

**Comment by AlexanderSehr** [comment]
@eriqua, should we deprecated this user story in favor of the migration or are there plans to implement the change on the CARML side still?

**Comment by eriqua** [comment]
Well it would be great to do that in CARML so that the review effort on AVM side is simplified, but last time I tried I didn't get so much excitement about that 😀 I'll try again and let's see what happens in a couple of weeks

**Comment by AlexanderSehr** [comment]
Hey @eriqua, I think this is done in AVM as all tests must have the 2 folders, right? If so, we should close this issue

**Comment by eriqua** [comment]
Closing
