### ISSUE TITLE
Readme Creation Script referencing non-existent helper script

### ISSUE THREAD

**Issue by senavar** [Azure/ResourceModules#419]
## Description

When running the ReadMe creation script, it is referring to a script -  Merge-FileWithNewContent.ps1 under .\ResourceModules\utilities\tools\helper\Merge-FileWithNewContent.ps1 but this helper scrip does not exist in the repo/path.

### Steps to reproduce

1. Run the ReadMe helper script using Set-ModuleReadMe -TemplateFilePath

### Screenshots

![image](https://user-images.githubusercontent.com/47188710/140565334-a9d43100-2ff5-4be3-ad7e-b302e8f8f7a4.png)

![image](https://user-images.githubusercontent.com/47188710/140565407-628adcb4-1813-4423-a364-dbeec0f3fafd.png)

**Comment by MrMCake** [comment]
Hey @senavar we got you covered. There the fix is part of this PR: https://github.com/Azure/ResourceModules/pull/407

Just waiting for somebody to review & merge it
