### ISSUE TITLE
[Bug Report]: paritionKey should be required by the container resource for a NoSQL database

### ISSUE THREAD

**Issue by carlin-q-scott** [Azure/ResourceModules#4278]
### Describe the bug

The [NoSQL Container resource](https://github.com/Azure/ResourceModules/tree/main/modules/document-db/database-account/sql-database/container) requires properties.resources.partitionKey but it isn't marked as required. The API rejects a container with a partition key with this error:
> A Partition key definition is not specified in the request.

### To reproduce

Deploy a container to a NoSQL database without specifying the partitionKey.

### Code snippet

```Bicep
param databaseAccountName string
param databaseName string
param containerName string

resource cosmosDbAccount 'Microsoft.DocumentDB/databaseAccounts@2023-09-15' existing = {
  name: databaseAccountName
}

resource alertDatabase 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases@2023-09-15' = {
  name: databaseName
  parent: cosmosDbAccount
  properties: {
    resource: {
      id: databaseName
    }
  }
}

resource alertSpecificationContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2023-09-15' = {
  name: containerName
  parent: alertDatabase
  properties: {
    resource: {
      id: containerName
    }
  }
}
```

**Comment by AlexanderSehr** [comment]
Hey @krbar, could you check this via the AVM [module](https://github.com/Azure/bicep-registry-modules/pull/667) you're working on. To do so, I guess we should have a test cases that does not provide the partition key (which should fail as per @carlin-q-scott's bug description) and then update the module accordingly before publishing.

Thanks for raising this @carlin-q-scott and sorry for the late response. The current migration to the Public Registry binds a lot of resources and we try to get through it as fast as possible.

**Comment by carlin-q-scott** [comment]
@AlexanderSehr I did not specify the partitionKey at all, so I'm guessing an empty array for the paths is what is not allowed by the resource provider. Their error message is a bit misleading I guess.

**Comment by krbar** [comment]
I will look at this issue together with @bryansan-msft 
Please note that the solution will be implemented in the [BRM Repo](https://github.com/Azure/bicep-registry-modules) as the module has already been migrated to AVM. I will drop a comment, once the fix is finished.

**Comment by bryansan-msft** [comment]
@AlexanderSehr could you close this one?

**Comment by AlexanderSehr** [comment]
I can @bryansan-msft (cc: @krbar), just before I do - was this covered in the meantime?
If not, I could also offer to migrate it to BRM instead and then handle it there :)

**Comment by bryansan-msft** [comment]
Yes, see the PR linked to this issue
________________________________
