### ISSUE TITLE
[Question/Feedback]: Could not see any bicep module for Azure Data Lake Storage Deployment 

### ISSUE THREAD

**Issue by AshTechieDevOps** [Azure/ResourceModules#4284]
### Description

[Question/Feedback]: Could not see any bicep module for Azure Data Lake Storage Deployment along with all of ADLS related resources as such “Account”, “File System”, “Directories”, “Files”, “Access Control” etc. is there the one that exists here and I have overlooked? Please suggest.

**Comment by tyconsulting** [comment]
are you talking about the Data Lake Gen 1? it's been replaced by Gen 2, which is just the storage account https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction

**Comment by AshTechieDevOps** [comment]
Thanks "Tao Yang" for sharing this information. I understand this is just a storage account with "supportsHierarchicalNamespace" property as "True" but what I was wondering if we already have a bicep module to deploy Azure Data Lake Storage along with all of the related resources as such “Account”, “File System”, “Directories”, “Files”, “Access Control”, encryption using CMKs, key and secret retiring from key vault and the required private endpoints etc.

**Comment by AlexanderSehr** [comment]
Hey @AshTechieDevOps,
as @tyconsulting mentioned, the original ADLS services transitioned into the Storage Account with HierachicalNamespace enabled (as described by you). That module supports a variety of services including CMK & Private Endpoints.
However, I guess you're asking for something different. Directories & Files on an DataLake store are consider Data-Plane operations and are 'usually' out-of-scope for IaC resources. Sometimes some operations exist, but usually you'd need to resport to other means like scripts to e.g. configure ACLs on the file system.

**Comment by AshTechieDevOps** [comment]
Thanks Tao.

**Comment by AlexanderSehr** [comment]
It has been a while, but I think this could now be handled by requesting for a corresponding Pattern module in [AVM](https://http://aka.ms/avm) (Azure-Verified-Modules).
Feel free to create a module proposal [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose).

**Comment by AlexanderSehr** [comment]
Closing as per previous comment
