### ISSUE TITLE
How to run Specific Network security Group module in azure bicep using Azure devops yaml pipe line

### ISSUE THREAD

**Issue by Satishlucky** [Azure/ResourceModules#4367]
### Description

How to run Specific Network security Group module in azure bicep using Azure devops yaml pipe line

**Comment by AlexanderSehr** [comment]
Hey @Satishlucky,
I'm not sure if I understand the question correctly, but fundamentally, you can use e.g. the [ResourceManagerTask](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=Azure-pipelines) to deploy a Bicep template by pointing to its local folder path.

**Comment by AlexanderSehr** [comment]
This has been open a while without a response. @Satishlucky, I'll go ahead and close this for now, but feel free to open it again and comment if it comes up again :)
