### ISSUE TITLE
Update Microsoft.Insights\privateLinkScopes to new child-resource structure Feature Request

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#443]
## Description

Update Microsoft.Insights\privateLinkScopes to new child-resource structure

**Comment by jontreynes** [comment]
just set up secrets to run the privatelinkscopes github action in my fork

**Comment by simonbMS** [comment]
@jontreynes during the daily we decided to re-assign this to try to close it before the tomorrow's milestone.
