### ISSUE TITLE
[Feature Request]: Selective Role Assignment Modification for Existing Storage Accounts

### ISSUE THREAD

**Issue by Jackmt9** [Azure/ResourceModules#4461]
### Description

Summary: Introduce a functionality within the storage account module (as well as others) that allows users to modify role assignments on existing storage accounts without requiring a full reconfiguration of the account settings. This feature is particularly essential for scenarios where the storage account is referenced by another service like Synapse, and role modifications are necessary post the initial creation.

Detailed Description:

Use Case: In cases where a storage account is created and subsequently referenced by a Synapse workspace, it becomes necessary to modify role assignments after the initial setup. Currently, altering role assignments requires calling the entire storage account module, involving reconfiguration of all settings, which is cumbersome and inefficient.
Proposed Solution: Implement a feature that enables calling the storage module with an option to solely update role assignments. This would streamline the process by allowing users to add or change roles without having to input all the other configurations again.
Expected Behavior:
Users should be able to call the storage module with a new parameter or method focused exclusively on role management.
This call would enable the addition, removal, or modification of roles associated with the storage account.
All other existing configurations of the storage account should remain unchanged unless explicitly specified by the user.
Benefits:
Enhanced flexibility and efficiency in managing role assignments for storage accounts.
Reduced risk of inadvertent configuration changes during role updates.
Better integration with services like Synapse, accommodating dynamic changes in role assignments post-initial setup.
Impact:

This feature would be a significant improvement for developers and administrators who manage cloud resources and require dynamic role management for storage accounts, especially in complex setups involving services like Synapse.

**Comment by AlexanderSehr** [comment]
Hey @Jackmt9, as per the other commented issue, please re-open in the Public Bicep Registry repository at https://github.com/Azure/bicep-registry-modules as the module was already migrated over. This will automatically notify the owner who can implment the feature accordingly :)
