### ISSUE TITLE
[Feature Request]: ResourceAccessRules on storage account

### ISSUE THREAD

**Issue by Jackmt9** [Azure/ResourceModules#4462]
### Description

When creating a storage account, I'd like to have the ability to pass:
          "networkAcls": {
            "resourceAccessRules": [
              {
                ....
              }
            ] 
        }

**Comment by AlexanderSehr** [comment]
Hey @Jackmt9, thank you for your issue. The Storage Account module was already migrated to the Public Bicep Registry repository at : https://github.com/Azure/bicep-registry-modules . Please open the issue over there so that the module owner is notified and can implement the issue :)
