### ISSUE TITLE
Network Watcher Platform Dependency Validation Failure

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#449]
| 18:13:35 - Error: Code=InvalidTemplateDeployment; Message=The
     | template deployment 'networkWatchers-20211107T1811062763Z' is
     | not valid according to the validation procedure. The tracking
     | id is 'd3aa4911-f0ff-4223-a8e0-7aa680e318ab'. See inner errors
     | for details.

This occurs when running the platform dependencies pipeline. (US Gov Tenant)

**Comment by rahalan** [comment]
@cacarroll can you please provide the detailed log for this correlation id?

**Comment by MrMCake** [comment]
Closing as there was no progress in 3 months
