### ISSUE TITLE
Align `management/management-group` to AVM specs

### ISSUE THREAD

**Issue by krbar** [Azure/ResourceModules#4496]

**Comment by mgrlabs** [comment]
Hi guys. I've noticed that `management/management-group` has been migrated to AVM but there's no `MOVED-TO-AVM.md` file in the module root yet. I assume that will be covered off in this issue? I'm using this file in some script logic to identify which modules have already been migrated so I don't push the equivalent CARML module to an ACR.

**Comment by krbar** [comment]
> Hi guys. I've noticed that `management/management-group` has been migrated to AVM but there's no `MOVED-TO-AVM.md` file in the module root yet. I assume that will be covered off in this issue? I'm using this file in some script logic to identify which modules have already been migrated so I don't push the equivalent CARML module to an ACR.

@mgrlabs you are right, the migration has been completed this week, I will add `MOVED-TO-AVM.md` and then close this issue.
