### ISSUE TITLE
Compute Images

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#451]
Expecting storage that is not deployed by Platform dependencies script. 

   | 12:34:53 - The deployment 'images-20211110T1211583728Z' failed
     | with error(s). Showing 1 out of 1 error(s). Status Message:
     | Storage account 'r0jskwdzcal7ss9okmxiyua3' not found. Ensure
     | storage account is not deleted and belongs to the same Azure
     | location as the VM. (Code:StorageAccountNotFound) 
     | CorrelationId: 4454623e-50ed-4152-abf0-d609901eeb06

**Comment by rahalan** [comment]
@cacarroll unfortunately the parameter needs to be changed after the storage account was created, as the name is "unpredictable" --> we will need to update the wiki to reflect that
