### ISSUE TITLE
SQL Servers

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#452]
VERBOSE: Performing the operation "Test" on target "Resource group level deployment".
VERBOSE: Using Bicep v0.4.1008
WARNING: ***
  "Code": "MultipleErrorsOccurred",
  "Message": "Multiple error occurred: NotFound,NotFound. Please see details.",
  "Target": null,
  "Details": null
***

Test-TemplateWithParameterFile: /home/runner/work/_temp/0f315800-90bb-49b2-9458-b8727dc32668.ps1:20
Line |
  20 |  Test-TemplateWithParameterFile @functionInput -Verbose
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Template is not valid.

**Comment by rahalan** [comment]
@cacarroll can you please add the detailed log?

**Comment by MrMCake** [comment]
Closing as there was no progress in 3 months
