### ISSUE TITLE
Azure Security Center

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#453]
| 12:52:41 - The deployment
     | 'azureSecurityCenter-20211110T1211298683Z' failed with
     | error(s). Showing 2 out of 2 error(s). Status Message: The
     | name 'AppServices' is not a valid name. Possible pricing
     | bundle names: VirtualMachines, SqlServers, StorageAccounts,
     | SqlServerVirtualMachines, KubernetesService,
     | ContainerRegistry, Dns, Arm, OpenSourceRelationalDatabases.
     | (Code:InvalidResourceName)  Status Message: The name
     | 'KeyVaults' is not a valid name. Possible pricing bundle
     | names: VirtualMachines, SqlServers, StorageAccounts,
     | SqlServerVirtualMachines, KubernetesService,
     | ContainerRegistry, Dns, Arm, OpenSourceRelationalDatabases.
     | (Code:InvalidResourceName)  CorrelationId:
     | 9a8fc2d0-c0df-40c6-b7d8-35dd0a9bda54

**Comment by rahalan** [comment]
@cacarroll  Is this a deployment in a government cloud?

**Comment by MrMCake** [comment]
Closing as there was no progress in 3 months
