### ISSUE TITLE
[Bug Report]: Add support for latest Microsoft.DocumentDB databaseAccounts/sqlDatabases/containers schema: 2023-11-15

### ISSUE THREAD

**Issue by andlommy** [Azure/ResourceModules#4530]
### Describe the bug

CARML module https://github.com/Azure/ResourceModules/blob/main/modules/document-db/database-account/sql-database/container/main.bicep uses 2023-04-15 schema and does not support version attribute for partition key described at https://learn.microsoft.com/en-us/azure/templates/microsoft.documentdb/2023-11-15/databaseaccounts/sqldatabases/containers?pivots=deployment-language-bicep

### To reproduce

NA

**Comment by AlexanderSehr** [comment]
Hey @andlommy, please note that this module has been migrated to [AVM / the public bicep registry](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res). If you can, please open the issue in this repository instead. :)
