### ISSUE TITLE
Storage Accounts

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#454]
API is not available in MAG yet.  This is an easy update. Please let me know if this is a non-bug and the expectation should be for the customer to update to a supported API version.

  | 12:56:28 - The deployment
     | 'storageAccounts-20211110T1211027128Z' failed with error(s).
     | Showing 2 out of 2 error(s). Status Message: No registered
     | resource provider found for location 'usgovvirginia' and API
     | version '2021-08-01' for type 'storageAccounts/blobServices'.
     | The supported api-versions are '2021-06-01, 2021-05-01,
     | 2021-04-01, 2021-02-01, 2021-01-01, 2020-08-01-preview,
     | 2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01,
     | 2018-03-01-preview, 2018-02-01, 2017-10-01, 2016-12-01,
     | 2016-05-01'. The supported locations are 'usgoviowa,
     | usgovvirginia, usgovtexas, usgovarizona, usdodeast,
     | usdodcentral'. (Code:NoRegisteredProviderFound)  Status
     | Message: At least one resource deployment operation failed.
     | Please list deployment operations for details. Please see
     | https://aka.ms/DeployOperations for usage details. (Code:
     | DeploymentFailed)  - ***   "error": ***     "code":
     | "NoRegisteredProviderFound",     "message": "No registered
     | resource provider found for location 'usgovvirginia' and API
     | version '2021-08-01' for type 'storageAccounts/blobServices'.
     | The supported api-versions are '2021-06-01, 2021-05-01,
     | 2021-04-01, 2021-02-01, 2021-01-01, 2020-08-01-preview,
     | 2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01,
     | 2018-03-01-preview, 2018-02-01, 2017-10-01, 2016-12-01,
     | 2016-05-01'. The supported locations are 'usgoviowa,
     | usgovvirginia, usgovtexas, usgovarizona, usdodeast,
     | usdodcentral'."   *** *** (Code:BadRequest)   CorrelationId:
     | 67fd6eb8-2f39-43b8-adc3-1d1eb88c7eb3

**Comment by rahalan** [comment]
no bug in CARML. But needs to be discussed in the future how to handle those issues.
