### ISSUE TITLE
[Bug Report]: Publicnetworkaccess

### ISSUE THREAD

**Issue by OussamaLarfaoui** [Azure/ResourceModules#4543]
### Describe the bug

I can't find the publicNetworkAccess parameter in the code at the path ResourceModules/modules/document-db/database-account/main.bicep.

In the old modules, the publicNetworkAccess parameter was present. This is crucial for us to disable public access and manage it via private endpoints.

### To reproduce

After deployement you found that the network Access enabled for public

**Comment by AlexanderSehr** [comment]
Hey @OussamaLarfaoui,
the module has been ported to AVM a while back. You can find the latest version of the module [here](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/document-db/database-account).

In it, you will find that you can set the `publicNetworkAccess` property via the `networkRestrictions` parameter :)

I'll close this issue for this repository. If the latest version in AVM does not work for you, please create an issue over there. The module's owner would then help you directly :)

**Comment by OussamaLarfaoui** [comment]
Thank you @AlexanderSehr  !!
