### ISSUE TITLE
[Module issue from Discussions] AVD Session Host Module

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#4545]
### Discussed in https://github.com/Azure/ResourceModules/discussions/3150

<div type='discussions-op-text'>

<sup>Originally posted by **FallenHoot** April 26, 2023</sup>
It is rare that you edit the Hostpool after it has been created, but you do modify the AVD Session Host a lot with new images, VM SKU, and much more. Dependency can be Hostpool, but AVD Session should be decoupled for easier management. 

Currently, CARML has https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.DesktopVirtualization:
![image](https://user-images.githubusercontent.com/19664186/234584706-50b96251-8b4e-4d4f-b7e1-d233ec8bef3f.png)

Example here: https://github.com/Azure/avdaccelerator/blob/main/workload/bicep/modules/avdSessionHosts/deploy.bicep
</div>

**Comment by eriqua** [comment]
Up for discussion if an avm ptn module may cover this one

**Comment by AlexanderSehr** [comment]
Agreeing with @eriqua's comment that this could/should be apattern module in AVM. I suggest to open an AVM module proposal for this given the completed migration. You can find the issue template [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose). As we're trying to move all issues to the corresponding location / have them triaged I'll go ahead and close this issue for this repository.
