### ISSUE TITLE
[Module proposal from Discussions] Microsoft.HybridCompute/privateLinkScopes

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#4548]
### Discussed in https://github.com/Azure/ResourceModules/discussions/4527

<div type='discussions-op-text'>

<sup>Originally posted by **Grant-Rc** March 17, 2024</sup>
Morning all 

Loving the modules as it alot of effort taken care of up front. I was woundering if anyone was working on Microsoft.HybridCompute/privateLinkScopes module? This is for the deployments of ARC and i dont seem to see this in any module </div>

**Comment by eriqua** [comment]
Hi @Grant-Rc, as mentioned in the original discussion, the team will further triage this issue and convert it to an Azure Verified Modules ([AVM](https://aka.ms/AVM)) GitHub issue if applicable.

**Comment by eriqua** [comment]
@AlexanderSehr this qualifies as a module proposal, so should be moved to AVM instead of to BRM.

**Comment by AlexanderSehr** [comment]
As per @eriqua's comment I suggest to open an AVM module proposal for this given the completed migration. You can find the issue template [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose). As we're trying to move all issues to the corresponding location / have them triaged I'll go ahead and close this issue for this repository.
