### ISSUE TITLE
Network Virtual WANS

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#455]
Successfully deployed but failed to remove the resource.

WARNING: Removal moved back for re-try. Reason: [InUseVirtualWanCannotBeDeleted : Cannot proceed with the operation because Virtual WAN has references. The WAN is referenced by 1 Virtual Hubs and 1 VPN Sites.
CorrelationId: 383c3ece-b0e1-4fc0-840c-88f2ecb3ba1b]
VERBOSE: ----------------------------------
VERBOSE: Re-try removal of remaining [1] resources. Round [3|3]
VERBOSE: ----------------------------------
VERBOSE: Performing the operation "Remove" on target "Resource [sxx-az-vw-x-001] of type [Microsoft.Network/virtualWans] from resource group [validation-rg9]".
WARNING: Removal moved back for re-try. Reason: [InUseVirtualWanCannotBeDeleted : Cannot proceed with the operation because Virtual WAN has references. The WAN is referenced by 1 Virtual Hubs and 1 VPN Sites.
CorrelationId: 938afc0e-6d4d-4425-90f4-9a3b260ee033]

**Comment by rahalan** [comment]
Closed because it is already in the backlog
