### ISSUE TITLE
Add (new) Microsoft Fabric

### ISSUE THREAD

**Issue by FlorisWaternet** [Azure/ResourceModules#4552]
### Description

Although there is a 'Service Fabric (Managed) Cluster', which originaly was named 'Microsoft Fabric'. Microsoft has introduced a new "Microsoft Fabric" as a complete different product.
Can/will and when will this new Microsoft Fabric Azure Resource added to the library?

**Comment by AlexanderSehr** [comment]
Hey @FlorisWaternet,
valid ask, wrong location 😉 

Please note that all original CARML modules have been updated, and migrated to [AVM](http://aka.ms/avm) as modules published in the [Public Bicep Registry](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res). This repository will continue to be maintained as a CI environment that we're working on making fully AVM compatible to maintain an inner-source option.

That being said, I'd ask you to just move the request to AVM by opening an issue via this [form](https://github.com/Azure/Azure-Verified-Modules/issues/new?assignees=&labels=Type%3A+New+Module+Proposal+%3Abulb%3A%2CNeeds%3A+Triage+%3Amag%3A&projects=Azure%2F529&template=module_proposal.yml&title=%5BModule+Proposal%5D%3A+%60MODULE_NAME_BETWEEN_BACKTICKS%60). 💪 

Will close the issue for this repository though 😉
