### ISSUE TITLE
VirtualMachineImages: Templates

### ISSUE THREAD

**Issue by cacarroll** [Azure/ResourceModules#456]
| 13:07:37 - The deployment
     | 'imageTemplates-20211110T1311450961Z' failed with error(s).
     | Showing 1 out of 1 error(s). Status Message: The resource
     | namespace 'Microsoft.VirtualMachineImages' is invalid.
     | (Code:InvalidResourceNamespace)  CorrelationId:
     | 62164194-e21a-41da-beee-f4088042ab4b

**Comment by rahalan** [comment]
@cacarroll Could you please give more context: 

- which parameters did you use? 
- which cloud did you deploy?
- which API version of the module did you use?
- can you attach the log of the correlation id?
- did you register the provider?
