### ISSUE TITLE
Add broken link checker to wiki sync engine

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#465]
## Description

To make sure that we publish working links in the wiki, we should add a broken link checker that runs as a static code checker for all MD files under /docs.

i.e.:
- https://github.com/marketplace/actions/broken-link-checker-action
- https://github.com/marketplace/actions/link-snitch

**Comment by ahmadabdalla** [comment]
Done some search on this and found: [lychee](https://github.com/lycheeverse/lychee) to be a helpful solution meeting our requirements

**Comment by ahmadabdalla** [comment]
Currently testing in my fork and I've using the following method:
- Create a .lycheeignore to put in all of the exclusions we do not want to check.
- Added it to the main linter workflow as `always()`

Pending:
- With the exclusions in place, we have about 40 errors we need to fix. But will raise this internally to see how we can tackle them as there is a dependency on the readme generation script component that creates URLs that do not exist as the ARM documentation is sometimes not up to date with the api version we are using in our bicep modules

**Comment by ahmadabdalla** [comment]
Had to change the internal links to use `.md` extension at the end so that they can be queried via the tools.
Removed it from the Linter into its own workflow

**Comment by rahalan** [comment]
@ahmadabdalla  Can we close this issue?

**Comment by MrMCake** [comment]
@ahmadabdalla , @MariusStorhaug

**Comment by ahmadabdalla** [comment]
We should be able to close it as we do have a capability now. @MariusStorhaug was there something specific we needed to implement besides the link check function we have today?

**Comment by MariusStorhaug** [comment]
I think we are good on this. Closing it.
