### ISSUE TITLE
Cognitive Services doesn't support restore flag

### ISSUE THREAD

**Issue by lmcconnell1665** [Azure/ResourceModules#468]
## The cognitive services account template is using API version 2017-04-18. This version does not support the "restore: true" flag. 

If you delete a cognitive services account it is soft deleted. You must purge it to re-use that name ever again. When you purge a name you can't use it again for 48 hours. If you want to re-create an account withour purging it you pass in a property called "restore" set to true.

### Steps to reproduce

1. Deploy a cognitive services account using the template
2. Delete this cognitive services account
3. Attempt to re-deploy the same template with the same name

### Screenshots
![image](https://user-images.githubusercontent.com/56060247/141605342-7d708241-1a62-4b4a-a112-ccc64854a11b.png)

**Comment by lmcconnell1665** [comment]
you can assign this one to me.

**Comment by lmcconnell1665** [comment]
@rahalan let me know who the best contact for this issue is...

While running the test workflows to validate a change, I am getting this error. I have added AZURE_CREDENTIALS to use a service principal pointed towards my dev/test Azure subscription. The resources deploy successfully (service principal has adequate permissions on the subscription). 

What do I need to have configured in the target Azure subscription to successfully run the tests?

![image](https://user-images.githubusercontent.com/56060247/142963144-6520b651-54a2-45eb-ba31-7f5d5f49bed6.png)

**Comment by rahalan** [comment]
@ahmadabdalla do you have time to investigate that one? Thanks, Rainer

**Comment by ahmadabdalla** [comment]
The only thing I can think of here is that it is an AuthZ issue.
@lmcconnell1665 does the principal ID: '00b24f79-083d-413b-a8bc-48e8453ce094' have access to the storage account created? We are working on a release soon to replace the Principal IDs with a token <<deploymentSpId>>. This should help removing IDs from being hardcoded.

**Comment by lmcconnell1665** [comment]
@ahmadabdalla the principal '00b24f79-083d-413b-a8bc-48e8453ce094' has both an Owner and Storage Blob Data Owner role at the resource group level. Would there be any other roles that are needed?

**Comment by ahmadabdalla** [comment]
@lmcconnell1665 we've just rolled out the token `<<deploymentSpId>>` to all Parameter files. This should get replaced on runtime with the GitHub Secret `DEPLOYMENT_SP_ID` as per the [Getting Started](https://github.com/Azure/ResourceModules/blob/main/docs/wiki/GettingStarted.md#github-specific-prerequisites). Can you fetch the latest into your fork and re-run the pipeline?
