### ISSUE TITLE
Token Replacement: Pilot Feedback and Enhancements

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#470]
Capture and address feedback from current Token Replacement Roll out [Pilot].
Rollout Tokens to All remaining pipelines

**Comment by ahmadabdalla** [comment]
* Wiki Documentation Link in Getting Started is broken.
* Token Documentation not visible in Wiki Content

**Comment by ahmadabdalla** [comment]
Bug in the documentation:
``pwsh
Set-AzKeyVaultSecret -Name $TokenName -SecretValue (ConvertTo-SecureString -AsPlainText $PSItem.Name) -
``

should be 
``pwsh
Set-AzKeyVaultSecret -Name $TokenName -SecretValue (ConvertTo-SecureString -AsPlainText $PSItem.Value) -
``

**Comment by ahmadabdalla** [comment]
Bug in the documentation:
``pwsh
Set-AzKeyVaultSecret -Name $TokenName -SecretValue (ConvertTo-SecureString -AsPlainText $PSItem.Name) -
``

should be 
``pwsh
Set-AzKeyVaultSecret -Name $TokenName -SecretValue (ConvertTo-SecureString -AsPlainText $PSItem.Value) -
``

**Comment by ahmadabdalla** [comment]
Bug in the documentation:
``pwsh
Set-AzKeyVaultSecret -Name $TokenName -SecretValue (ConvertTo-SecureString -AsPlainText $PSItem.Name) -
``

should be 
``pwsh
Set-AzKeyVaultSecret -Name $TokenName -SecretValue (ConvertTo-SecureString -AsPlainText $PSItem.Value) -
``

**Comment by ahmadabdalla** [comment]
- Need to generalize the scripts and improve readability.
- Update documentation 
  - Simplify where possible
  - address wrong links

- Maybe move away from Key Vault Token Name 'ParameterFileToken-' and just use the secret name as the token name, while relying on the 'ContentType'. This will improve the user experience for creating tokens and reduce errors, as we don't want a situation where all secrets are extracted from key vault because no prefixes are used. So enforce the content type instead

**Comment by MrMCake** [comment]
I'd suggest to trim the example in the wiki down a noch from

```PowerShell
#########[ Function Test-ModulesLocally.ps1 ]#############
cd path/to/clonedRepo
. .\utilities\tools\Test-ModuleLocally.ps1

# REQUIRED INPUT FOR TESTING
$TestModuleLocallyInput = @{
    ModuleName                    = 'Microsoft.Network\applicationSecurityGroups'
    PesterTest                    = $true
    DeploymentTest                = $true
    ValidationTest                = $false
    ValidateOrDeployParameters    = @{
        Location          = 'australiaeast'
        ResourceGroupName = 'validation-rg'
        SubscriptionId    = '12345678-1234-1234-1234-123456789123'
        ManagementGroupId = 'mg-contoso'
        RemoveDeployment  = $false
    }
    DeployAllModuleParameterFiles = $false
    GetParameterFileTokens        = $true
    #TokenKeyVaultName             = 'contoso-platform-kv'
    OtherCustomParameterFileTokens      = @(
        @{ Name = 'deploymentSpId'; Value = '12345678-1234-1234-1234-123456789123' }
        @{ Name = 'tenantId'; Value = '12345678-1234-1234-1234-123456789123' }
    )
}
> Note, the invocation is missing
```

to 

```PowerShell
$TestModuleLocallyInput = @{
    ModuleName        = 'Microsoft.Network\applicationSecurityGroups'
    PesterTest        = $true
    ValidationTest    = $true
    DeploymentTest    = $true
    Location          = 'australiaeast'
    ResourceGroupName = 'validation-rg'
    SubscriptionId    = '12345678-1234-1234-1234-123456789123'
    ManagementGroupId = 'mg-contoso'
    AdditionalTokens  = @{
        deploymentSpId = '12345678-1234-1234-1234-123456789123' 
        tenantId       = '12345678-1234-1234-1234-123456789123'
    }
}
Test-ModuleLocally @TestModuleLocallyInput
```

**Comment by ahmadabdalla** [comment]
@MrMCake default usage example has been trimmed to
```pwsh
$TestModuleLocallyInput = @{
    ModuleName                    = 'Microsoft.Network\applicationSecurityGroups'
    PesterTest                    = $true
    DeploymentTest                = $true
    ValidationTest                = $false
    ValidateOrDeployParameters    = @{
        Location          = 'australiaeast'
        ResourceGroupName = 'validation-rg'
        SubscriptionId    = '12345678-1234-1234-1234-123456789123'
        ManagementGroupId = 'mg-contoso'
    }
    AdditionalTokens      = @(
        @{ Name = 'deploymentSpId'; Value = '12345678-1234-1234-1234-123456789123' }
        @{ Name = 'tenantId'; Value = '12345678-1234-1234-1234-123456789123' }
    )
}
```
Not quite the above as it'll introduce more parameters. Change will be in the next PR for tokens
