### ISSUE TITLE
StorageAccount top-level properties must be expanded

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#484]
Right now, the storage account properties are passed down as one object - hence completely preventing any sort of parameter validatition.

```bicep
resource storageAccount 'Microsoft.Storage/storageAccounts@2021-06-01' = {
  name: storageAccountName_var
  location: location
  kind: storageAccountKind
  sku: {
    name: storageAccountSku
  }
  identity: {
    type: managedServiceIdentity
    userAssignedIdentities: (empty(userAssignedIdentities) ? null : userAssignedIdentities)
  }
  tags: tags
  properties: saProperties
```

The properties object should be expanded as per the [official documention](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?tabs=bicep#storageaccountpropertiescreateparameters)

**Comment by rahalan** [comment]
After discussion with @MrMCake we decided to abandon the issue
