### ISSUE TITLE
Exempt CARML testing subscription from Automanage DINE policies

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#486]
## Description

Several Automanage* DINE policies are applied to the testing environment causing conflicting deployments on resource dependencies.
The CARML testing environment should be exempted from those policies to allow modules to be tested in isolation.

Example:
_Automanage workspace assignment_ policy monitors workspace and ensures an automation account is linked. After a linked service is deployed on the dependency LAW, It's not possible to test a linkservice deployment to a different automation account.

### Steps to reproduce

1. Deploy a LAW
2. Wait for the DINE policy to be applied.

### Screenshots
![image](https://user-images.githubusercontent.com/56914614/142212959-64ad2852-c5b6-4157-858b-89cea8af0f68.png)

![image](https://user-images.githubusercontent.com/56914614/142213649-baa9b57d-fe9e-4e6b-88fd-25aa98dc7576.png)

**Comment by MrMCake** [comment]
@eriqua , this is resolved, right?

**Comment by eriqua** [comment]
After deleting the DINE policies and changing the automanage implementation we do not have DINE policies applied to the subscription anymore. Closing this issue, although the automanage automation account still gets created and linked to the LAW. Ref issue #965
