### ISSUE TITLE
RBAC Assignment Failing 

### ISSUE THREAD

**Issue by senavar** [Azure/ResourceModules#515]
## Description

When deploying a module with an RBAC assignment, it is resulting in the following error: "The location property is required for this definition." 

Currently seeing this while testing the Data Factory module. 

Bringing awareness to this as it may or may not be occurring with other modules 

### Steps to reproduce

1. Deploy a module with an RBAC assignment, like Data Factory
2. Currently Data Factory workflow is failing due to this

### Screenshots

![image](https://user-images.githubusercontent.com/47188710/142708713-c57cb269-694a-4545-b8a2-29d1d7c45f0f.png)

#### Possible Root Cause
I see that the RBAC module does a deployment of the parent (target) resource. It is missing the 'location' property. In an initial test, adding location: resourcegroup().location fixed the issue. 

![image](https://user-images.githubusercontent.com/47188710/142708827-53278faf-a091-45ad-984c-63010075b849.png)

#### Fix

![image](https://user-images.githubusercontent.com/47188710/142708987-39839603-8d6b-4a63-a071-1a166327af83.png)

![image](https://user-images.githubusercontent.com/47188710/142709072-e0c0b74a-8905-410e-a880-327d45e7ed49.png)

**Comment by eriqua** [comment]
Hi @senavar, thanks for raising this.

Strangely the **existing** keyword is missing for this rbac module. Could you try the following instead?

```
resource dataFactory 'Microsoft.DataFactory/factories@2018-06-01' existing = {
  name: resourceName
}

resource roleAssignment 'Microsoft.Authorization/roleAssignments@2020-04-01-preview' = [for principalId in roleAssignmentObj.principalIds: {
  name: guid(dataFactory.name, principalId, roleAssignmentObj.roleDefinitionIdOrName)
  properties: {
    roleDefinitionId: contains(builtInRoleNames, roleAssignmentObj.roleDefinitionIdOrName) ? builtInRoleNames[roleAssignmentObj.roleDefinitionIdOrName] : roleAssignmentObj.roleDefinitionIdOrName
    principalId: principalId
  }
  scope: dataFactory
}]
```

**Comment by senavar** [comment]
Yes @eriqua that was it! Thank you and @MrMCake for pointing it out. Will close out the issue but hopefully this helps others who may come across it :)
