### ISSUE TITLE
connectionMonitor readme.md parameter example error

### ISSUE THREAD

**Issue by bzabber** [Azure/ResourceModules#582]
## Description

The endpoint01 on line 44 of the arm\Microsoft.Network\networkWatchers\readme.md is incorrect. 

It should read: endpoint01(endpoint01-rg)

### Screenshots
![image](https://user-images.githubusercontent.com/31073790/143497444-d1385cb9-c82b-4f90-98b3-e5dbb8914e85.png)

**Comment by MrMCake** [comment]
Good catch, thanks @bzabber
