### ISSUE TITLE
Modules: Enable removal of remaining resources that need  a custom script

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#644]
Now that we switched the removal to deployment names there are less resources we cannot remove. However there are still a few that we need to tackle, such as:

- [x] Diagnostic Settings
- [x] Managed Services Registration Definitions
- [ ] Security Center
- [x] Locks

**Comment by eriqua** [comment]
Diagnostic Settings are included

**Comment by MrMCake** [comment]
@eriqua The PRs for Locks & RegistrationDefinition are in now. 

Regarding the Security Center I wonder if we shoud implement the removal. The SecurityCenter is somewhat 'global' and we could accidently remove legit settings. What do you think?

**Comment by eriqua** [comment]
I think is fine if we keep the SecurityCenter removal disabled by default, but we should probably anyway have the removal logic working in case the removal flag is enabled. Also we probably need to specify the reasons of the exception somewhere in the wiki (e.g. the removal section in the deployment validation page)

**Comment by eriqua** [comment]
See new issue #1524 for azure security center
