### ISSUE TITLE
Role Assignment Fails in Dependency Pipeline due to an existing name

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#669]
## Description

Role Assignment task fails in the dependency pipeline due to a role that already exists.

``` powershell
Exception: /home/runner/work/_temp/c15652b3-bd86-4903-88d8-0e6578b5b1de.ps1:33
Line |
  33 |    throw $res['Exception']
     |    ~~~~~~~~~~~~~~~~~~~~~~~
     | 19:29:44 - The deployment '-20211129T1911425766Z' failed with
     | error(s). Showing 1 out of 1 error(s). Status Message: The
     | role assignment already exists. (Code:RoleAssignmentExists) 
     | CorrelationId: 240d7e6a-2bee-4a3d-acb6-233ccd0b290d
```

The reason is that the latest module update for role assignments, we decoupled the location property from the role assignment GUID as it is not a dependency. Where a deployment might happen on a specific location, but then another location is introduced or being tested which causes issues and doesn't make the deployment idempotent. 

### Steps to reproduce

1. Deploy the dependency pipeline

### Solution
- Remove the role assignment from the principal ID: `cf33fea8-b30f-424f-ab73-c48d99e0b222`. This can be done via CLI or portal but requires permissions
- Rerun the dependency pipeline. 

### Possible side effects

- If other resources are deployed that require the user assigned managed identity to have the permissions and they are deployed before it in the dependency pipeline, that might fail the first time, until the identity has a role assigned to it

**Comment by eriqua** [comment]
Thanks for tracking the issue @ahmadabdalla.
The roleassignment has been deleted and redeployed successfully through the dependency pipeline.
Closing the issue.
