### ISSUE TITLE
DocumentDB (CosmosDB) has issue on systemassignd + userassigned managed identity

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#678]
## Description

Using both systemassigned and userassigned Managed Identity causes a failed deployment when using the module. Working fine with using one or the other.

### Steps to reproduce

1. Define both a systemAssignedIdentity and userAssignedIdentities. I.e.
```json
        "systemAssignedIdentity": {
            "value": true
        },
        "userAssignedIdentities": {
            "value": {
                "/subscriptions/<<subscriptionId>>/resourcegroups/validation-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/adp-sxx-az-msi-x-001": {}
            }
        },
```
2. Run the pipeline.

Result:
https://github.com/Azure/ResourceModules/runs/4358484625?check_suite_focus=true#step:5:371

![image](https://user-images.githubusercontent.com/17722253/144023856-2ae130db-b5c6-42c7-939a-797a32f5097f.png)

**Comment by lsnoddy** [comment]
This error stills occurs after removing the extra space and updating the api version. I created a support ticket for further investigation, and they confirmed they are able to reproduce the error. Support has escalated internally to the PG.

**Comment by lsnoddy** [comment]
Product group rolled out a fix for this issue on 7/22. I tested a deployment with both systemAssignedIdentity and userAssignedIdentities and no longer observe the error. No code change was required in the modules/parameters. Closing this bug.
