### ISSUE TITLE
RecoveryServicesVault: Issue with systemAssignedPrincipalId output

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#730]
## Description

Recovery Services Vault fails with the following error
`{"code":"DeploymentOutputEvaluationFailed","message":"Unable to evaluate template outputs: 'systemAssignedPrincipalId'. Please see error details and deployment operations. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"DeploymentOutputEvaluationFailed","target":"systemAssignedPrincipalId","message":"The template output 'systemAssignedPrincipalId' is not valid: The language expression property 'principalId' doesn't exist, available properties are 'type'.."}]}`

### Steps to reproduce

1. Run RSV deployment
2. Double check deployment in portal

### Screenshots
![image](https://user-images.githubusercontent.com/56914614/144721960-a740d42b-3a50-47ff-bf83-348dde3fc4ff.png)

**Comment by rahalan** [comment]
Looks like a one time problem. Another run was successful.

**Comment by MariusStorhaug** [comment]
Will look at this together with SA
