### ISSUE TITLE
Better documentation for inputs/outputs

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#752]
Some inputs and outputs have a vague description, making it hard for the user to understand, what they are used for. E.g. the description of workspaceId does not explain, that it is used for diagnostic settings. 

All descriptions for inputs and outputs should be scanned and if necessary adapted. Also the name of the parameter should be questioned and if necessary adapted to a more intuitive name.

**Comment by rahalan** [comment]
@rahalan needs more refinement

**Comment by MrMCake** [comment]
Moving back to triage and added 'needs further discussion' tag as @rahalan stated that the issue needs further refinement

**Comment by rahalan** [comment]
no open parameters/outputs at the moment

**Comment by rahalan** [comment]
no open parameters/outputs at the moment
