### ISSUE TITLE
Directory based deployment using Module deployment script only deploys the first file in the directory

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#757]
If we pass a directory (container) to the `parameterFilePath` parameter of the `New-ModuleDeployment.ps1` script, the logic detects the directory correctly, however it only deploys the first file in that directory.

Cause:
We have a `return` function being called at the end of the deployment, which exits the script
```pwsh
 return $deploymentName
```

Removing this line has implications on other steps as the output is being used elsewhere.

Need to investigate other methods to achieve the same outcome.

**Comment by MrMCake** [comment]
It should work following #768 . However, need to deliberatly test it
