### ISSUE TITLE
Bug Report - RBAC assignment error

### ISSUE THREAD

**Issue by NilssonCJ** [Azure/ResourceModules#762]
## Description
Looks like it removes the "-" between for the Service Principal which resolves into unable to assign the RBAC permissions, tried to look around where but can't figure it out, any good input?  
### Steps to reproduce

1. Running Resource Group (example) module as initial tryout, have the secrets set correctly.

### Github Action Output

 VERBOSE: Resource deployment Failed.. (1/3) Retrying in 5 Seconds.. 

VERBOSE: 14:58:15 - The deployment 'resourceGroups-20211207T1412389821Z' failed with error(s). Showing 1 out of 1 error(s).
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)
 - ***
  "error": ***
    "code": "PrincipalNotFound",
    "message": "Principal **3403a1323ee0455bb6607bee276dfdef** does not exist in the directory ***."
  ***
*** (Code:BadRequest)

**Comment by ahmadabdalla** [comment]
@NilssonCJ , can you please share the parameter file you're using with the bicep module.

**Comment by NilssonCJ** [comment]
Tried a few different parameter files.

Below is the current failing:
`{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "value": "rg-deploytryout-weu"
        },
        "tags": {
            "value": {
                "Keep": "Yes"
            }
        },
        "roleAssignments": {
            "value": [
                {
                    "roleDefinitionIdOrName": "Reader",
                    "principalIds": [
                        "9302439b-183f-460e-9c5c-75266ce5201b"
                    ]
                }
            ]
        }
    }
}`

I also tried the one where you have I guess? with "<<" & ">>" and that it's gonna get it from the secret in the github repo?
By the error message it looks like it remove the "-" between the service principal id and then can't resolve it?

**Comment by ahmadabdalla** [comment]
@NilssonCJ . I was able to simulate the error you are getting by doing the following:
- First time deployment ==> Used a valid Principal ID ==> Result is success
- Second time, I changed one character in that same Principal ID (**_made it invalid_**), and then I got the error you have above. 

The error you get above is not coming from the module (removed `-`), it is a response from the ARM API when it attempts to assign a role to an object (principal) that does not exist. Here is the error I got:

```pwsh
Exception: 
Line |
  23 |  Test-ModuleLocally @TestModuleLocallyInput -Verbose
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 9:55:07 AM - The deployment 'resourceGroups-20211209T0912272635Z' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Principal aae2fcdc805f4b659cbba053881cf033 does not exist in the directory efab98e8-ef90-4604-97b1-3756ad1b3380. (Code:PrincipalNotFound)
CorrelationId: 315b8054-c792-427c-ad2a-8bbd5c33e3aa
```

**Comment by NilssonCJ** [comment]
My bad. Thanks for the troubleshooting @ahmadabdalla 
Mixed up the application ID & Object ID.
