### ISSUE TITLE
Set default values to a secure value - Cognitive Services

### ISSUE THREAD

**Issue by elbatane** [Azure/ResourceModules#776]
All default values should comply with a security baseline, e.g. [NIST 800](https://docs.microsoft.com/en-us/azure/governance/policy/samples/nist-sp-800-53-r5)

The [build-in policies of Azure](https://github.com/Azure/azure-policy) can be used as a reference.

The task would be to scan over each of the following policies and make sure, that the module is per default complying to them.

The following policies are the NIST 800 ones:

- [x] \built-in-policies\policyDefinitions\Cognitive Services\CognitiveServices_CustomerManagedKey_Audit.json
- [x] \built-in-policies\policyDefinitions\Cognitive Services\CognitiveServices_DisableLocalAuth_Audit.json
- [x] \built-in-policies\policyDefinitions\Cognitive Services\CognitiveServices_DisablePublicNetworkAccess_Audit.json
- [x] \built-in-policies\policyDefinitions\Cognitive Services\CognitiveServices_EnablePrivateEndpoints_Audit.json
- [x] \built-in-policies\policyDefinitions\Cognitive Services\CognitiveServices_NetworkAcls_Audit.json

For Private Endpoint compliance, add the privateEndpoints parameter to the max parameters.json file and update the privateEndpoints parameter description in the bicep.json to indicate private endpoints should be used. For example:

```json
@description('Optional. Configuration Details for private endpoints. Cognitive Services accounts should use private endpoints.')
param privateEndpoints array = []
```

**Comment by MrMCake** [comment]
CMK implementation is current on hold until [this raised issue[(https://github.com/Azure/bicep/issues/7066) is sorted. I started implementing it in branch 'users/alsehr/776_cogSerCMK'.

**Comment by MrMCake** [comment]
Also, note that the feature seems still in Preview aus you have to fill out a form: https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/concepts/encryption-data-at-rest#customer-managed-keys-for-language-services
