### ISSUE TITLE
Set default values to a secure value - Virtual Network

### ISSUE THREAD

**Issue by elbatane** [Azure/ResourceModules#790]
All default values should comply with a security baseline, e.g. [NIST 800](https://docs.microsoft.com/en-us/azure/governance/policy/samples/nist-sp-800-53-r5)

The [build-in policies of Azure](https://github.com/Azure/azure-policy) can be used as a reference.

The task would be to scan over each of the following policies and make sure, that the module is per default complying to them.

The following policies are the NIST 800 ones:

\built-in-policies\policyDefinitions\Network\ASC_All_Internet_traffic_should_be_routed_via_Azure_Firewall.json

**Comment by MrMCake** [comment]
As the policy requests a certain subnet and we don't provide defaults for subnets this issue can be closed.
