### ISSUE TITLE
Set default values to a secure value - Image Templates

### ISSUE THREAD

**Issue by elanzel** [Azure/ResourceModules#795]
All default values should comply with a security baseline, e.g. [NIST 800](https://docs.microsoft.com/en-us/azure/governance/policy/samples/nist-sp-800-53-r5)

The [build-in policies](https://github.com/Azure/azure-policy) of Azure can be used as a reference.

The task would be to scan over each of the following policies and make sure, that the module is per default complying to them.

The following policies are the NIST 800 ones:
\built-in-policies\policyDefinitions\VM Image Builder\PrivateLinkEnabled_Audit.json

**Comment by MrMCake** [comment]
The required property `vnetConfig` is already implemented via the `subnetId` parameter. As we don't want to enforce the parameter (yet) this issue can be closed.
