### ISSUE TITLE
Discuss if aligning the purge code for all resources applying soft deletion

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#813]
## Description

Today's approach to purge resources applying soft deletion differs. Currently:
- Key vault: PS cmdlets
- Cognitive services: PS cmdlets
- API management: REST API
- RSV VM backup: PS cmdlets

API management purge is only feasible through REST API. Ref [here](https://docs.microsoft.com/en-us/azure/api-management/soft-delete#supporting-interfaces)

Discuss if aligning also other resources to leverage the same approach. e.g. for key vault (tested)

```powershell
'Microsoft.KeyVault/vaults' {
            $subscriptionId = $resourceId.Split('/')[2]
            $resourceName = Split-Path $ResourceId -Leaf

            # Fetch service in soft-delete
            $getPath = '/subscriptions/{0}/providers/Microsoft.KeyVault/deletedVaults?api-version=2019-09-01' -f $subscriptionId
            $getRequestInputObject = @{
                Method = 'GET'
                Path   = $getPath
            }
            $softDeletedService = ((Invoke-AzRestMethod @getRequestInputObject).Content | ConvertFrom-Json).value | Where-Object { $_.properties.vaultId -eq $resourceId }
            if ($softDeletedService) {
                # Purge service
                $purgePath = '/subscriptions/{0}/providers/Microsoft.KeyVault/locations/{1}/deletedVaults/{2}/purge?api-version=2019-09-01' -f $subscriptionId, $softDeletedService.properties.location, $resourceName
                $purgeRequestInputObject = @{
                    Method = 'POST'
                    Path   = $purgePath
                }
                if ($PSCmdlet.ShouldProcess(('API management service with ID [{0}]' -f $softDeletedService.properties.serviceId), 'Purge')) {
                    $null = Invoke-AzRestMethod @purgeRequestInputObject
                }
            }
        }
```

**Comment by AlexanderSehr** [comment]
Personally I'd prefer Powershell as it is much easier than REST. However, as the this is already the status quo, the issue apparently rather asks to change it all to REST. 
I updated now KVLT & CogntiveServices - but RSV will become a lot more complicates as it also requires a lot more individual REST calls. Are we really sure we want this?

**Comment by eriqua** [comment]
I think the intention of the issue is discussing, not implementing. Personally I think that we should consider this only if it leads to cleaner code and improved maintainability. If not, I agree we should skip it.

**Comment by AlexanderSehr** [comment]
Reference for KVLT & Cognitive Services: https://github.com/Azure/ResourceModules/compare/main...users/alsehr/813_alignPurge

**Comment by rahalan** [comment]
Unfortunately there is no "one size fits all". Sometimes PS is needed, in other cases Rest API calls. Team decides, it stays as is.
