### ISSUE TITLE
Discussion - Restructure Wiki

### ISSUE THREAD

**Issue by simonbMS** [Azure/ResourceModules#836]
Could be somehow connected to #19. 

## Description

Open a round table on if and how to restructure the Wiki content to make it easier for a user to consume

**Comment by eriqua** [comment]
Suggested TOC:
- Context
   - Infrastructure as Code
   - Where does this platform fit in?
- Getting started
   - Prerequisites
   - Setup environment
   - Token replacement
   - Dependency pipeline
- The library
   - Module design
   - Module usage
- CI environment
   - Pipeline design
      - Static validation
      - Deployment validation (includes removal)
      - Publishing
   - Pipeline usage  
- Interoperability
   - Bicep to ARM/JSON conversion
   - Register ADO pipelines
- Contribution guide
   - Readme generator script
   - Get formatted RBAC roles script
- Known Issues

**Comment by eriqua** [comment]
Scenarios (to be included in the getting started root page):

- Onboard modules (opt 1) all getting started subsections
- Consume modules (opt 2) download zip + only prereq
- Contribute (opt 4) depends on the contribution

**Comment by segraef** [comment]
What about Workload scenarios or is it more desirable to focus on the Modules?

**Comment by MrMCake** [comment]
> What about Workload scenarios or is it more desirable to focus on the Modules?

This would be part of Opt2 as far as I'm conserned
