### ISSUE TITLE
Add Microsoft.Subscription/Aliases module

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#868]
## Description

Create a bicep module to deploy a subscription using bicep.

Requirements:
- Provision a sub from MCA/EA billing account
- Management Group placement
- Tag CRUD operations
- RBAC CRUD operations

**Comment by MariusStorhaug** [comment]
I'm working on this in my own lab. Still awaiting the "official" billing accounts to use for testing.

**Comment by MariusStorhaug** [comment]
Alex is also working on this in a separate branch in this repo, [users/alsehr/bicep_subscription](https://github.com/Azure/ResourceModules/tree/users/alsehr/bicep_subscription/arm/Microsoft.Subscription/aliases)

**Comment by MariusStorhaug** [comment]
@elanzel is also doing some work on this. Added her to the issue.

**Comment by rahalan** [comment]
blocked: no permission to test @mblant

**Comment by smajchrz** [comment]
Is there any plan to develop this module?

**Comment by AlexanderSehr** [comment]
Closing this for now to be implemented another day if need be. The current code base if vastly outdated.
