### ISSUE TITLE
Create a list of missing Azure resource types for modules

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#869]
Although we have already a huge list of modules, there are still many missing. A list of necessary and missing Azure resource types need to be compiled.

**Comment by lsnoddy** [comment]
[CARMLModules.xlsx](https://github.com/Azure/ResourceModules/files/7938614/CARMLModules.xlsx)

**Comment by MrMCake** [comment]
Closing this issue as this is done and open a new issue to create new issues from the Excel #1319
