### ISSUE TITLE
Event Hub namespace default name Bug Report

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#877]
## Description

The event hub module generates a unique random name in case the name is not passed as a parameter. That is tested with the parameter file min.parameters.json.

The logic creating the unique name must comply with the eventhub namespace naming convention. In particular, the unique name must start with a letter. The current logic allows the generated unique name to start with a number and in that case the deployment fails.
> Example: https://github.com/Azure/ResourceModules/runs/4776425099?check_suite_focus=true#step:4:430

### Steps to reproduce

1. Run the event hub module until the logic generating the unique event hub namespace name creates a string starting with a number
2. The pipeline testing the min.parameters.json fails

### Screenshots

![image](https://user-images.githubusercontent.com/56914614/148963102-fe0f22ee-331e-423a-b002-8e131d3b24d2.png)

**Comment by rahalan** [comment]
Or discuss if we remove the auto-generate name functionality
