### ISSUE TITLE
Update CuaID implementation

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#882]
Change current implementation of the CuaID number implementation into a boolean & add a location to it to work around the 'one deploymentname per location' issue.

![image](https://user-images.githubusercontent.com/5365358/149180935-dd3dc7fd-6ac8-4cec-ba73-db94bb50c71e.png)

Call the boolean

**Comment by MrMCake** [comment]
Open question: Dedicated module that is shared across all modules, or implemented in each?

**Comment by MariusStorhaug** [comment]
Be aware of potential duplicate issue: #235
