### ISSUE TITLE
Add private endpoint parameter tests to all modules with implemented endpoint support

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#890]
Add private endpoint tests to all modules with implemented endpoint support.

Reference: [AutomationAccount](https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json)

**Comment by kavishshivhare** [comment]
List of private endpoint supported modules (with supported resource type) in the repo with private endpoint support implemented along with an updated parameters file as of today -

| Module | Status |
| - | - |
| App Configuration | ✅ |
| Automation Accounts | ✅ |
| Batch Accounts |  |
| Cognitive Services | ✅ |
| Container Registries | ✅ |
| Data Factories | |
| Event Grid Topics | ✅ |
| Event Hub Namespaces | ✅ |
| Key Vaults | ✅ |
| Machine Learning Workspaces | ✅ |
| Network Application Gateways | |
| Recovery Services Vaults | |
| Service Bus Namespaces | ✅ |
| SQL Servers | ✅ |
| Storage Accounts | ✅ |
| Azure Synapse Analytics | ✅ |
| Web/Function Apps | ✅

CC: @MrMCake.

**Comment by lsnoddy** [comment]
All modules with implemented private endpoint support within the repo have been verified to also have private endpoint test cases. Any that were missing have been added. See the comment above for the checklist of resources with implemented private endpoint support.
