### ISSUE TITLE
Improve Get-ResourceIdsOfDeployment script naming

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#900]
## Description

Discuss and propose a more intuitive naming for variables used by the [Get-ResourceIdsOfDeployment](https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/resourceRemoval/helper/Get-ResourceIdsOfDeployment.ps1) script. 
e.g. The outer function refers to `$deployments`, the inner one refers to a mix of `$deployments`, `$deploymentTargets`, `$resultSets`. The function name itself suggests the output should be resourceIds.

**Comment by MrMCake** [comment]
Done ;) @eriqua
