### ISSUE TITLE
The Platform update readme pipeline fails.

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#906]
## Description

The Platform update readme pipeline fails. See e.g. error https://github.com/Azure/ResourceModules/runs/4870230598?check_suite_focus=true#step:5:19

### Steps to reproduce

1. Run the Platform update readme pipeline manually or wait for that to be triggered by push to any deploy.bicep file in the arm folder

**Comment by MrMCake** [comment]
Fixed by authenticating the re-freshed PAT with the Azure Organization
