### ISSUE TITLE
Update locks API version to latest (202-05-01)

### ISSUE THREAD

**Issue by Msanzdelrio** [Azure/ResourceModules#916]
## Description

Update every module to leverage latest version from locks (2020-05-01): <https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/2020-05-01/locks?tabs=bicep>

**Comment by MrMCake** [comment]
Duplicate of #267 

> Note: The latest api version (2020-05-01) is NOT regognized in the cmdlet: 
> ```Powershell
> ((Get-AzResourceProvider -ListAvailable | Where-Object { $_.ProviderNamespace -like 'Microsoft.Authorization*' }).ResourceTypes | Where-Object { $_.ResourceTypeName -like 'lock*' }).ApiVersions
> ```
