### ISSUE TITLE
Add tests to verify module structure compliance

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#922]
## Description

Purpose: Ensure that all modules meet the repos module standards.
Specific finding: Modules are added with GitHub workflow, but not the corresponding ADO pipeline.

Add a global test that verifies the contents of modules (new and old alike). This should not be tied to a module's workflow/pipeline, as that is one thing that needs to exist in the first place. Should run successfully on pull_request trigger.

The test should:
- Identify a module based on a folder for resourceProvider/resourceType under the arm folder (non recurse, not starting with '.*')
- Each module must meet the following criteria:
  - module folder contains: 
    - deploy.bicep file
    - version.json file
    - readme.md file
    - .parameters folder with at least one parameters.json file
  - ADO pipeline file under '.azuredevops\modulePipelines'
  - GitHub workflow file under '.github\workflows'

**Comment by MrMCake** [comment]
TODO:

- [ ] Identify a module based on a folder for resourceProvider/resourceType under the arm folder (non recurse, not starting with '.*')

- [ ] module folder contains `deploy.bicep file`
- [ ] module folder contains `version.json file`
- [ ] module folder contains `readme.md file`
- [ ] module folder contains `parameters folder with at least one parameters.json file`

- [ ] ADO pipeline file under '.azuredevops\modulePipelines'
- [ ] GitHub workflow file under '.github\workflows'
