### ISSUE TITLE
Document prereq for ADO Universal Artifact Feed

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#927]
## Description

Document the prereqs for Azure DevOps Universal Artifact Feed (project/global).

As a consumer of this repo, what is required for me to setup azure artifact feed

**Comment by jontreynes** [comment]
I can document

**Comment by jontreynes** [comment]
https://github.com/Azure/ResourceModules/blob/users/jontreynes/927/docs/wiki/ADOUniversalArtifactFeed.md


Questions we need to answer as a team:
1. What ADO org would we use
2. Can we agree on naming the feed ResourceMoules
3. Is there reusable code for semvering our modules that we can use for artifacts
4. Is there reusable description of each module?
5. Is there reusable code that loops through each module

**Comment by jontreynes** [comment]
https://github.com/Azure/ResourceModules/wiki/Solution%20creation

**Comment by jontreynes** [comment]
Add paragraph here under Azure DevOps
https://github.com/Azure/ResourceModules/wiki/Getting%20started%20-%20Setup%20environment#32-setup-ci-environment-specific-configuration

**Comment by jontreynes** [comment]
for this documentation - I will simply show how to set it up in Azure DevOps Pipelines. In another issue, we can look into making this method extensible from github as well (because technically you can publish azure artifacts from github as well)

**Comment by jontreynes** [comment]
Note the custom method expects a bearer token
https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/resourcePublish/Publish-ModuleToUniversalArtifactFeed.ps1

We can later think about making this extensible to using the current account context with a project build service account https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#pipelines-permissions

**Comment by eriqua** [comment]
Updated link to added content https://github.com/Azure/ResourceModules/wiki/Getting%20started%20-%20Scenario%201%20Onboard%20module%20library%20and%20CI%20environment#325-azure-artifacts-universal-packages

**Comment by eriqua** [comment]
@jontreynes can this issue be closed?
