### ISSUE TITLE
Investigate and solve the Backup Management Service Object ID being hardcoded in the dependency pipeline

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#937]
## Description

Backup Management Service Object ID in Dependency Pipeline (KV Secrets) is hardcoded, and is unique per AAD Tenant. This will not function when CARML is being forked and deployed into another AAD tenant. 

## Ask

Find a mechanism to have this Principal ID (Object ID) being automated so that Key Vault Secrets Access Policy can assign the right permission.

**Comment by ahmadabdalla** [comment]
More context:
When deploying the dependency pipeline in my own tenant, and looking at the access policy for a KV. I can see that the principal ID being unknown:

![image](https://user-images.githubusercontent.com/28486158/152951734-4f36e130-f05b-4609-9320-2c869c6ae97f.png)

which maps to:

```json
        {
          "tenantId": "<<tenantId>>",
          "objectId": "bab643ad-2988-4560-9f2b-c8282ba345f0", // Backup Management Service needs access to back up the keys and secrets, along with the associated VMs
          "permissions": {
            "keys": [
```

**Comment by eriqua** [comment]
This is currently documented as a manual first step [here](https://github.com/Azure/ResourceModules/wiki/The%20CI%20environment%20-%20Pipeline%20usage#operate-the-dependencies-pipeline). Automation would require additional AAD permission for the deployment SPN.

**Comment by rahalan** [comment]
TODO: replace with Token from variables/settings

**Comment by eriqua** [comment]
To be rediscussed in the context of the new dependencies approach:
Which is the module using this dependency and how would this be implemented in the new scenario?

**Comment by rahalan** [comment]
@ahmadabdalla can you please check if this is still the case? We couldn't find it in the code anymore. Thanks!

**Comment by rahalan** [comment]
that issue is not relevant anymore
