### ISSUE TITLE
Version collision and downgrade

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#941]
## Description

Currently publishing supports different ways of working:

| Tech | Overwrite version | Downgrade |
|-|-|-|
| Bicep Reg | ✅ | ✅ |
| Template Spec  | ✅ | ✅ |
| ADO Feed | ❌ | ❌ |

Should we restrict the ability to 
- publish a downgrade
- publish same version as what exist

This means if we want to have packages being published for major and major.minor packages, we need a way to handle overwrites for the package versions we want to overwrite.

**Comment by rahalan** [comment]
Overwrite is already happening, but we are not so strict about publishing to lower versions
