### ISSUE TITLE
Reduce verbosity of publishing logic

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#961]
Currently, the publishing has an extensive vebosity. There are a few things that we could probably remove to reduce it to the relevant content:
- Filter the output of the entire diff to the folder path of the current module
- Remove debug outputs like `Git: Using git command 'git branch --show-current'`

**Comment by MariusStorhaug** [comment]
Will be fixed with the new PR for cleaning up and finalizing Publishing :D
