### ISSUE TITLE
PrincipalNotFound when using policyAssignments

### ISSUE THREAD

**Issue by kevinpz** [Azure/ResourceModules#981]
## Description

Hi! 

I've a customer which is trying to use the **policyAssignments** module to assign a policy with a RBAC. 
Each time they try to assign a policy, the bicep module doesn't found the principal and ends up in error the first time. 
After they restart the pipeline a few minutes later everything is fine.

### Steps to reproduce

1. Assign a policy which needs a RBAC
2. The deployment ends in error with the message: `PrincipalNotFound:
Principal xxxxx does not exist in the directory yyyyy`
3. Restart the deployment a few minutes later, everything is fine

Thanks!

**Comment by ahmadabdalla** [comment]
@kevinpz , this sometimes happens when AAD DB sync may have some delay when being queried for the same principal ID that has been created for the system managed identity for the policy. There should be a retry mechanism that attempts to redeploy when this happens and usually is successful on the next run. Can you please check if the logs for the deployment contains:
```pwsh
VERBOSE: Resource deployment Failed.. (1/3) Retrying in 5 Seconds.. 
```

**Comment by shanhyland** [comment]
Hello @ahmadabdalla ,
I'm working with @kevinpz on the issue, I've checked the logs and it doesn't contain 
`VERBOSE: Resource deployment Failed.. (1/3) Retrying in 5 Seconds.. `

Could you give us more details on how to implement a retry nechanism?
Thanks

**Comment by ahmadabdalla** [comment]
I am not sure what deployment mechanism you're using. The current pipelines use this [script](https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/resourceDeployment/New-ModuleDeployment.ps1) to deploy resources, which we've added a retry mechanism in there, set to 3 times as default.

**Comment by shanhyland** [comment]
Hello @ahmadabdalla,
Our deployement pipeline are yml file with Stages and Job, which call bicep files that then call the modules in the arm folder, which seems to be really different than the powershell script you're using.

Using YAML pipeline with Stage and Jobs, is there a way to add a retry on fail mechanism?
Here's an exemple of what our pipeline looks like:
`parameters:
- name: NameOfServiceConnection
  type: string
  default: ""
- name: scope
  type: string
  default: 'sub'
- name: location
  type: string
  default: 'TheRegion'
- name: environment
  type: string
  default: 'dev'
- name: templateFile
  type: string
  default: './.pipelines/test/main.bicep'
- name: mgmtGroupId
  type: string
  default: ''

stages:
  - stage: Validate_Bicep_Stage_${{ replace(replace(parameters.environment, '/', '_'), '-', '_') }}
    dependsOn: []
    displayName: "Validate [${{ parameters.environment }}]"
    jobs:
      - job: Validate_Bicep_Job
        timeoutInMinutes: 180
        displayName: "Validate Bicep [${{ parameters.environment }}]"
        steps:
        - checkout: self
        - template: ${{ parameters.scope }}.yml # Template reference
          parameters:
            action: 'validate'
            environment: ${{ parameters.environment }}
            azureServiceConnection: ${{ parameters.NameOfServiceConnection}}
            location: ${{ parameters.location }}
            templateFile: ${{ parameters.templateFile }}
            mgmtGroupId: ${{ parameters.mgmtGroupId }}
      - job: What_If_Bicep_Job
        timeoutInMinutes: 180
        displayName: "What-If Bicep [${{ parameters.environment }}]"
        steps:
        - checkout: self
        - template: ${{ parameters.scope }}.yml # Template reference
          parameters:
            action: 'what-if'
            environment: ${{ parameters.environment }}
            azureServiceConnection: ${{ parameters.NameOfServiceConnection}}
            location: ${{ parameters.location }}
            templateFile: ${{ parameters.templateFile }}
            mgmtGroupId: ${{ parameters.mgmtGroupId }}
  - stage: Create_Bicep_Stage_${{ replace(replace(parameters.environment, '/', '_'), '-', '_') }}
    displayName: "Create [${{ parameters.environment }}]"
    dependsOn:
      - Validate_Bicep_Stage_${{ replace(replace(parameters.environment, '/', '_'), '-', '_') }}
      # - Linter_Bicep_Stage_${{ replace(replace(parameters.environment, '/', '_'), '-', '_') }}
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    jobs:
      - deployment: Create_Bicep_Job
        timeoutInMinutes: 180
        displayName: "Create Bicep Job [${{ parameters.environment }}]"
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - template: ${{ parameters.scope }}.yml # Template reference
                parameters:
                  action: 'create'
                  environment: ${{ parameters.environment }}
                  azureServiceConnection: ${{ parameters.NameOfServiceConnection}}
                  location: ${{ parameters.location }}
                  templateFile: ${{ parameters.templateFile }}
                  mgmtGroupId: ${{ parameters.mgmtGroupId }}`

**Comment by ahmadabdalla** [comment]
The template:
```yaml
template: ${{ parameters.scope }}.yml # Template reference
```

Is that using a Powershell task within it to deploy? What I can think of at the top of my head is implementing a duplicate step that uses a condition **Example**
``` yaml
condition: and(failed(), eq(variables['Build.SourceBranchName'], 'main'))
```
which may work as a retry. I haven't tested this obviously, but it is a task that runs on failure, but not sure if that'll fail the pipeline if the previous step already failed.

**Comment by shanhyland** [comment]
Hello @ahmadabdalla ,
To your question: "Is that using a Powershell task within it to deploy?", the anser is no.
The Yaml file we have is calling a bicep file, and that bicep file is calling the modules in the arm folder.
So anyway to specify a retry step in our YAML pipeline files, that use Stage, Jobs, etc?

**Comment by ahmadabdalla** [comment]
@shanhyland , have a look at this [guidance](https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-195-update) and see if you can add that to the task?

**Comment by ahmadabdalla** [comment]
@azMantas , thank you and great suggestion and similar on [role-assignments](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/role-based-access-control/role-assignments-template.md#new-service-principal).  I've added this to the policy assignments module - role assignments and will raise a PR accordingly.

**Comment by ahmadabdalla** [comment]
@shanhyland , completing the PR closed the issue. Please have a look at the solution provided by @azMantas and add that to the module. I have also updated the policy assignment module to enforce the principal type so others can benefit from it.

**Comment by shanhyland** [comment]
> @shanhyland , have a look at this [guidance](https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-195-update) and see if you can add that to the task?

@ahmadabdalla  Sorry for the delay, and thanks for the link. 
The retry would probably work, but the problem doesn't "happen" in a Task, I'll look at the new code you Push.
Thanks
