### ISSUE TITLE
Publishing: Investigate diff comparison vs. main in ADO

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#990]
Currently, the publishing compares latest with latest-1 (Head vs Head-1). This has the unfortunate sideeffect that you would not be able to create a pre-release on a branch of the latest change was not a template-folder change. It would be great to instead compare with `main` always.

Apparently, this has a problem in ADO as the git commands to e.g. fetch the current branch return different results.

We should invetigate why this is the case, as it should come down to the agent - not ADO itself.

**Comment by MrMCake** [comment]
@MariusStorhaug That's already in `main`, correct?

**Comment by MariusStorhaug** [comment]
This is indeed fixed with the latest publish PR yes.
