### ISSUE TITLE
Wiki Documentation Module Dependencies Issue

### ISSUE THREAD

**Issue by bzabber** [Azure/ResourceModules#995]
## Description

I suggest the following changes to this section: https://github.com/azure/ResourceModules/wiki/TestingDesign#module-dependencies

"**"Resource"** Module dependencies
In order to successfully deploy and test all ARM/Bicep modules in your desired environment some modules require certain Azure resources to be deployed beforehand.

### Steps to reproduce

Documentation issue.

**Comment by MrMCake** [comment]
Good idea, thanks @bzabber . I updated the wiki.
