### ISSUE TITLE
RBAC Key Vault names are out of preview

### ISSUE THREAD

**Issue by SeSeicht** [Azure/ResourceModules#998]
## Description

The [KeyVault module](https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.KeyVault/vaults/.bicep/nested_rbac.bicep) uses the old "(preview)" names. So if you use the current name, the deployment fails.

The module should allow to use the preview AND the name without (preview)

https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli#azure-built-in-roles-for-key-vault-data-plane-operations

**Comment by MrMCake** [comment]
As a workaround you can use the non-preview name by providing it's ID. The table should be updated regardless.
